### ISSUE TITLE
Downloading One page from Mangatoon[bug]

### ISSUE THREAD

**Issue by saqlainartazz** [dazedcat19/FMD2#100]
**Prerequisite**
- [True] I'm using the latest version.
- [True] All website modules are up to date.

- [True] This is not temporary server issue.

**System information**
Windoiws 10 64bit Enterpise version 2004.

**Describe the bug**
FMD dowloads only one page from manga from mangatoon

**Comment by dazedcat19** [comment]
post the url

**Comment by S-Artaz** [comment]
https://mangatoon.mobi/en/detail/119/episodes

**Comment by saqlainartazz** [comment]
> post the url

https://mangatoon.mobi/en/detail/119/episodes

**Comment by saqlainartazz** [comment]
![fmd2](https://user-images.githubusercontent.com/68074135/92709125-160c1a00-f370-11ea-9d64-5d674e9e4dd0.PNG)
![fmd1](https://user-images.githubusercontent.com/68074135/92709290-389e3300-f370-11ea-8b30-36f58f8fc55f.PNG)

**Comment by dazedcat19** [comment]
can you even see them with a browser? because I can't. only a few earlier episodes. it seems the recent episodes only available through app. you can try the app and capture it with wireshark or something similar.

**Comment by saqlainartazz** [comment]
hmmm okay
