### ISSUE TITLE
[feature request] Downloads history

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#102]
**Is your feature request related to a problem? Please describe.**
Currently the history works is to sum it all.

**Describe the solution you'd like**
I'd like to make it a range view, example:
- Today = Range Between 0 Sec to 24 hours
- Yesterday = Range Between 25 Hours to 48 Hours
- One Week = Range Between 49 Hours to 7 Days
- One Month = Range Between 8 Days to 30/31 Days
- One Year = Range Between 1 Month to 12 Months
- Year Two = 12 to 24 Months
- Year Three = 25 to 36 Months
And so on.

**Describe alternatives you've considered**
Or also add a custom range view so the users can input the date manually. Something like this:
![image](https://user-images.githubusercontent.com/28888646/92814487-78573000-f3ed-11ea-8545-58e52a7a7b77.png)

**Comment by dazedcat19** [comment]
it follow history like firefox/chrome. I never look at it. but I remember there's used to be not this many selections (one year, two year...) I'll clean it up to
- Today
- Yesterday
- Last 7 days
- This month
- Older than 6 months
- Custom

**Comment by dazedcat19** [comment]
It will be looked like this. Custom date panel will be auto hide if non custom selected.
![img-20200912-115645](https://user-images.githubusercontent.com/59296763/92986659-1ed72a00-f4ef-11ea-99d7-4ab4453287c8.jpg)

**Comment by Slasar41** [comment]
Nice, I like it.
There's some bug when I choose a history and then search for a title, it'll break the choosen history.
Here's the recording: https://i.imgur.com/9pOEeP4.gifv
Is it fixed with this implemented feature?

**Comment by dazedcat19** [comment]
No. Make a new issue so people can search for it.
