### ISSUE TITLE
[bug] Wesbite Column is not showing the source website of the manga

### ISSUE THREAD

**Issue by Sakurahime08** [dazedcat19/FMD2#103]
**System information**
Windows 10

**Describe the bug**
Wesbite Column is not showing the source website of the manga. Happens on the Downloads Tab and Favorites Tab

**Screenshots**

![image](https://user-images.githubusercontent.com/35158146/92841626-262a0500-f415-11ea-91be-db6a5c7a25ed.png)

![image](https://user-images.githubusercontent.com/35158146/92841705-41951000-f415-11ea-8e91-64170c803d4b.png)

**Comment by dazedcat19** [comment]
That means there's no supported module. Create a new issue for website module request.

**Comment by Sakurahime08** [comment]
@dazedcat19 Are Mangahasu, mangadex, bato.to currently not yet supported here? These are the main ones I had imported from the other FMD. But I see them in the modules section?

![image](https://user-images.githubusercontent.com/35158146/92872299-71a1da80-f438-11ea-9053-bedc218be427.png)

**Comment by dazedcat19** [comment]
enable the log and make sure all modules loaded correctly

**Comment by Sakurahime08** [comment]
Is it this?
![image](https://user-images.githubusercontent.com/35158146/93011114-f40bd500-f5c5-11ea-8da2-6f25e829c4bb.png)

It has been checked ever since and still no changes when trying to check and uncheck. What else can I do? Thanks so much for the help!

**Comment by Sakurahime08** [comment]
if this helps: I tried adding one series again and it worked normally. so basically it can't recognize my imported favorites from the other FMD?
It also duplicated the entry from mangahasu instead of overwriting it.
It also means that when I try to View manga info from an existing series I have, it doesn't recognize the old chapters I already downloaded. (I have color-coded settings and customized the chapter rows to show a different color when they have already been downloaded. And the chapters in the screenshot hasn't been color-coded.)

![image](https://user-images.githubusercontent.com/35158146/93011233-0fc3ab00-f5c7-11ea-9eb7-c27491169ca1.png)

![image](https://user-images.githubusercontent.com/35158146/93011304-bdcf5500-f5c7-11ea-8427-c686345df05c.png)

**Comment by Slasar41** [comment]
Maybe you imported the data from FMD1 to FMD2 before FMD2 finish downloading all the modules?
Try importing the data from FMD1 to FMD2 again.

**Comment by dazedcat19** [comment]
it doesn't matter if the actual modules is present when converting the data. the converter tool is independent. it only needs `modules.txt` which contains `moduleid name`
make sure `modules.txt` is in the same directory when you running the converter tool. open `favorites.db` with any sqlite db explorer. look at the field `moduleid`. If it's still in a form of website name then it's not converted correctly. usually because missing `modules.txt`.

**Comment by Sakurahime08** [comment]
I seem to be missing the modules.txt indeed. Where do I get it?

**Comment by dazedcat19** [comment]
It's right in the release assets. beside the converter. https://github.com/dazedcat19/FMD2/releases/tag/2.0.21.0

**Comment by Sakurahime08** [comment]
Thanks! It's now working!
