### ISSUE TITLE
[feature request] Check if chapter already exist (pdf/etc..?) before downloading

### ISSUE THREAD

**Issue by Djaub** [dazedcat19/FMD2#104]
**Is your feature request related to a problem? Please describe.**
I changed from FMD to FMD2 and it download chapters of certains manga (not all) all over again despite chapters already existing in .pdf. I checked and it download pages per pages and erase the previous .pdf. 

**Describe the solution you'd like**
Before downloading a chapter it should check if the outcoming file (e.g.: "Chapter 13.pdf") already exist before downloading the pages.  
Alternatively it could be a new option on right click on a manga ("check all"?) to check if your manga isn't missing one or more chapters (speaking from FMD where I had crashes where my "in progress" list was deleted and I had to check manually which manga were missing a chapter or redownload everything).

**Additional context**
I don't know if this problem occur with other extensions (ZIP/CBZ/EPUB) and I'm not sure if it happen because I switched from FMD to FMD2 or if it's 'normal'. On FMD this problem also exist when "downloading all".
The converter was used without any problem, all my favorites and preferences were correctly saved.

**Comment by dazedcat19** [comment]
It's intended to not check the existing packed file. there's some website that update their chapter per page.
packed file (zip, cbz, pdf) is more of an extension. we don't really integrate it in the fmd core. we only track the actual image file. if it exist it will be skipped. for packed file, we have to unpacked it first to temp, copy it to working dir if necessary, remove it etc. which is expensive.
every download has a status flag for every chapter. if the status is finished fmd will skip it.
read `uDownloadsManager.pas`
