### ISSUE TITLE
[bug-website module] [Legion Asia] {cookie problem}

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#1043]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

W 10 21H1 x64

### Describe the bug

Suddenly the download system stops working. The Web is only working with cookies, but from time to time it stops working even if the cookies are changed again and it never downloads again. The information and library works fine, only the downloads.

Web: https://legionasia.com/
Languaje: Spanish

### Log

view-source:https://legionasia.com/

**Comment by rs3mk** [comment]
yapx, is the image service they use and this limits access. Only in Europe it seems to work well.

solution: open MangaShiro.lua and remove (line 251 to 254):

```
		for i = 0, TASK.PageLinks.Count - 1 do -- Bypass 'i0.wp.com' image CDN to ensure original images are loaded directly from host
			TASK.PageLinks[i] = TASK.PageLinks[i]:gsub("i%d.wp.com/", "")
			i = i + 1
		end 
```

work: https://i3.wp.com/i.yapx.ru/TV1MJ.jpg
not work: https://i.yapx.ru/TV1MJ.jpg
