### ISSUE TITLE
[bug] Search when selecting a history

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#106]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 2004 64-bit

**Describe the bug**
There's some bug when I select a history and then search for a title, it'll break the selected history.

**To Reproduce**
1. Select one of a downloads history
2. Search for a title
3. The selected history lost being applied

**Expected behavior**
The selected history should still being applied when searching for a title.

**Screenshots**
https://i.imgur.com/9pOEeP4.gifv

**Comment by dazedcat19** [comment]
already fixed in https://github.com/dazedcat19/FMD2/commit/fc2d39dd6807cf5c2adf341c5352888a2fdaf836
