### ISSUE TITLE
[bug] there's an error after I updated my FMD

### ISSUE THREAD

**Issue by echoPN** [dazedcat19/FMD2#107]
![new update](https://user-images.githubusercontent.com/38193321/93421741-65a49580-f8dc-11ea-91f3-78a44d4443e0.jpg)

**Comment by echoPN** [comment]
Solved....
There's some files in _userdata_ folder that not compatible with the newest version...
So, after update and you have the same problem go to FMD folder location go to _userdata_, **delete** all .json files...

**Comment by dazedcat19** [comment]
This is because of your saved selected index on "History" larger than the existed index. I did change the history selections. I forgot to add a check for index out of bounds.
To fix it, open `settings.json` and find a key "DownloadFilterSelect" and change it to "0".

**Comment by echoPN** [comment]
Ohh... 
So, that's the case...
Thanks for the respond...
