### ISSUE TITLE
[website module request] manhuasworld.com

### ISSUE THREAD

**Issue by zartzaku** [dazedcat19/FMD2#109]
Website Information

    Name: manhuasworld.com
    Root URL: https://manhuasworld.com
    Directory list URL: https://manhuasworld.com/manga/?m_orderby=alphabet
    Example manga info URL: https://manhuasworld.com/manga/azure-legacy-cang-yuantu/
    Example chapter URL: https://manhuasworld.com/manga/azure-legacy-cang-yuantu/chapter-1/

Additional context
path of sword and few manhua new chapter is only available on this web. i try looking on manganelo, readm and many other but the chapter available until 35, while at manhuasworld.com the chapter already available up to 52.

**Comment by dazedcat19** [comment]
@zartzaku  Please test and close if OK.
