### ISSUE TITLE
[bug] FMD2 keeps not respoding a keeps crashing

### ISSUE THREAD

**Issue by leoteesh** [dazedcat19/FMD2#110]
**Prerequisite**
- [ ] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Your operating system. 64-bit operating system

**Describe the bug**
Every time FMD2 finish updating it crashes - it stops responding, does not download and i lose the history for the day. The screen goes pale and nothing works. 
This has been occurring a few days now, since the update to the new version. 

![image](https://user-images.githubusercontent.com/21075197/93712591-ca672680-fb4e-11ea-9526-72dd53492ea5.png)

**To Reproduce**
1. Go to '...' started FMD2 as usual
2. While updating and where finished updating, it crashes and stops working.
**Expected behavior**
It should update and download automatically 

**Screenshots**

![image](https://user-images.githubusercontent.com/21075197/93712854-457d0c80-fb50-11ea-920b-d5f2b423aa35.png)

I was not sure which section this issue should be, so i am sorry if this is the wrong one.
I hope that you can advise?

Many thanks

**Comment by dazedcat19** [comment]
make sure to enable your log `options > misc > log`
when it crash, wait a moment until it write to the log file. Don't interact with the frozen window like repeatedly clicking it, it may trigger the os to force kill it. Except when stuck too long like 10min. then you can force kill it. make sure there;s something written in the log file. we can't investigate it without it.
attach your log file and your userdata folder. compress it into one file (zip/rar). we hate to be able to reproduce the same issue exactly as yours.

**Comment by leoteesh** [comment]
Thank you. 
please see attached as requested. Hopefully this is want you wanted.
[userdata-log.zip](https://github.com/dazedcat19/FMD2/files/5257523/userdata-log.zip)

Thanks again

**Comment by dazedcat19** [comment]
fixed in recent commit.
