### ISSUE TITLE
[bug-website module] KomikStation

### ISSUE THREAD

**Issue by MIRVOUS** [dazedcat19/FMD2#112]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7 32-bit

**Describe the bug**
Can't download full-image chapters, even if the download is complete

**Additional context**
I downloaded this manga: "Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?", Ch. 26 and the download is complete but when I open the folder. the picture looks less.(pls see the ss).

I used to download this manga on fmd and I always felt like the story was cut off.
then I tried to download it with Hakuneko and the results were different.

i hope this issue is fixed cause fmd is my main download manager

in fmd : 
![komikstation](https://user-images.githubusercontent.com/45929526/93963395-4481f000-fd87-11ea-8c4f-18b98009d29e.png)
downloaded with fmd : 
![komikstation2](https://user-images.githubusercontent.com/45929526/93963413-4c419480-fd87-11ea-8ddd-97b6552cd0e4.png)

downloaded with hakuneko :
![komikstation3](https://user-images.githubusercontent.com/45929526/93963461-6da28080-fd87-11ea-8291-f9bb1fc92698.png)

**Comment by dazedcat19** [comment]
User should post the related urls so we can test it right away without searching for it first.

**Comment by MIRVOUS** [comment]
> User should post the related urls so we can test it right away without searching for it first.

okay. next time i will
