### ISSUE TITLE
[bug-website module] MangaKyo

### ISSUE THREAD

**Issue by MIRVOUS** [dazedcat19/FMD2#114]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7 32-bit

**Describe the bug**
1. The website is changed url from 'www.mangakyo.com' to 'www.mangakyo.me'
![mangakyo2](https://user-images.githubusercontent.com/45929526/93968460-d5f75f00-fd93-11ea-9fe1-196503d07d6b.png)
2. They changed the url manga lists too
from : 
![mangakyo3](https://user-images.githubusercontent.com/45929526/93968664-5b7b0f00-fd94-11ea-9ec8-2a0e163774fa.png)
to : 
![mangakyo4](https://user-images.githubusercontent.com/45929526/93968732-7d749180-fd94-11ea-8726-71850a4cdde6.PNG)

**Additional context**
*the download feature has not been tried

**Comment by dazedcat19** [comment]
you can try to edit the lua file directly and make a pull request.

tips: 
runing fmd with `fmd.exe --lua-dofile` will execute the lua function directly from the file. so you can modify the lua source directly without the need to restart fmd.
you can also save the downloaded content and load them later when developing a module for faster execution.
for first load:
```lua
if not HTTP.GET(url) then return net_problem end
HTTP.Document.SaveToFile("mytemp.html")
```
then temporary disable the http request
```lua
--if not HTTP.GET(url) then return net_problem end
--HTTP.Document.SaveToFile("mytemp.html")
HTTP.Document.LoadFromFile("mytemp.html")
```
