### ISSUE TITLE
[website module request] "Mangastk" NEW

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#1167]
### Name

Mangastk

### Root URL

https://mangastk.net/

### Directory list URL

https://mangastk.net/manga/

### Example manga info URL

https://mangastk.net/manga/amo-del-tiempo/

### Example chapter URL

https://mangastk.net/manga/amo-del-tiempo/capitulo-17/

### Language

Spanish

**Comment by Lenoyr** [comment]
Dead Site bro

**Comment by xx255q** [comment]
#1225

**Comment by Lenoyr** [comment]
Dead Site
"Good evening/good day/good afternoon, please receive a warm greeting everyone. This message is to inform you that 'MANGASTK' is permanently closed. We reserve our privacy policy. Thank you and goodbye."
It is a message from your Telegram.

![imagen](https://github.com/dazedcat19/FMD2/assets/65477084/be0199f4-e323-434b-b8e3-0f3f9f3d89ac)
