### ISSUE TITLE
about manga-tr repo 

### ISSUE THREAD

**Issue by hitsumo** [dazedcat19/FMD2#12]
Hello
Manga-tr repo download but after empty repo. Can you update repo?

**Comment by dazedcat19** [comment]
Slazar just updated the manga-tr module. You can check that. If your problem is about the missing  database. You can build it yourself and make a pull request at https://github.com/dazedcat19/FMD2-DB

**Comment by Slasar41** [comment]
Currently I'm updating the database.
@dazedcat19 Manga-Tr use DDOS-GUARD protection so I've to use cookies workaround.
Could you add support for it?
![image](https://user-images.githubusercontent.com/28888646/83613140-9111a780-a5ad-11ea-8dac-75bdb88e9d33.png)

**Comment by dazedcat19** [comment]
I don't get the ddos-guard page. All download just fine. can you give me an example of the page with ddos-guard?

**Comment by Slasar41** [comment]
I get the ddos-guard when updating the manga list.
Looks like the protection only triggered when many connections happening.

**Comment by dazedcat19** [comment]
Actually it can be bypassed simply just by clearing the cookies. But the http cookies manager enforce the cookies, and there's no api to bypass it yet. I will add a new lua api later.

`HTTP.ClearCookies()` should clear all current cookies and disable httpcookiesmanager for current request.
~~`HTTP.DisableCookies()` disable storing/loading cookies.~~
~~`HTTP.EnableCookies()` enable storing/loading cookies.~~
`HTTP.EnabledCookies=[true/false]` control storing/loading cookies

I'll look at the ddos-guard later.

It's also a good idea to limit manga-tr connection by default.

**Comment by hitsumo** [comment]
> Slazar just updated the manga-tr module. You can check that. If your problem is about the missing database. You can build it yourself and make a pull request at https://github.com/dazedcat19/FMD2-DB

How can i build? i dont know programs language. And working manga-tr thanks.

**Comment by Slasar41** [comment]
@hitsumo I've updated the database.
You can use `Download manga list from server` now.

**Comment by hitsumo** [comment]
thank you @Slasar41
