### ISSUE TITLE
Workaround for cloudflare protected websites

### ISSUE THREAD

**Issue by dazedcat19** [dazedcat19/FMD2#120]
Using Firefox, node.js and selenium-webdriver
- Install [node.js](https://nodejs.org/en/download/current/)
- Install selenium-webdriver. open cmd and type `npm install -g selenium-webdriver`
- Download [geckodriver](https://github.com/mozilla/geckodriver/releases) into FMD2 directory
- Create a file named `use_webdriver` in `lua\websitebypass`

or

Using Firefox, python and selenium-webdriver
- Install [python](https://www.python.org/downloads/)
- Install selenium-webdriver, open cmd.exe and type `pip install selenium`
- Download [geckodriver](https://github.com/mozilla/geckodriver/releases) into FMD2 directory
- Download [cloudflare.py](https://raw.githubusercontent.com/dazedcat19/FMD2/master/extras/cloudflare.py) into `lua\websitebypass`
- Create a file named `use_webdriver` in `lua\websitebypass`

**Comment by molitar** [comment]
Ok I tested this and it worked but I did not create an empty file use_webdriver and it still worked.  I used winsize 2 to make the dos window that opens for it to a size of 1x1 so it's invisible and out of the way.

**Comment by dazedcat19** [comment]
You don't have the latest update don't you?
The latest cloudflare.lua will only use webdriver when there's "use_webdriver" file. I wrote it like that so user can prepare the dependencies first.
The latest update also use fmd's api 'RunCommandHide' which will not invoke cmd window. The lua execute or io.popen for windows use 'cmd /c'.

**Comment by molitar** [comment]
Ok sounds good.. no I do not have latest update as I had to wait a good 12 hours for the English sites to update all lists.  Man that is really slow.

**Comment by dazedcat19** [comment]
I mean the latest cloudflare.lua

**Comment by Sakurahime08** [comment]
How to make this work for mangahasu and bato.to? 

Currently, tried this workaround for both but doesn't look like it's working. 
- Mangahasu: Copy/pasting of cookies works instead
- Bato.to: can't find the clearance cookie in the website anymore. help?

To clarify, how to create an empty file? 

Thanks much!

**Comment by dazedcat19** [comment]
it doesn't matter if it's empty or not. open cmd from fmd directory and type `echo.>lua\websitebypass\use_webdriver`
make sure to disable the user-agent and cookies overrides first.

**Comment by molitar** [comment]
> 
> 
> How to make this work for mangahasu and bato.to?
> 
> Currently, tried this workaround for both but doesn't look like it's working.
> 
>     * Mangahasu: Copy/pasting of cookies works instead
> 
>     * Bato.to: can't find the clearance cookie in the website anymore. help?
> 
> 
> To clarify, how to create an empty file?
> 
> Thanks much!

You can just create a text file named use_webdriver than delete the extension .txt.  You now have an empty file titled use_webdriver.

**Comment by Fergie07** [comment]
I've tried using the python version of the workaround. This is the message that I am getting in the log when I attempt to use MangaFreak.

12:18:31:052 INFO: WebsitBypass[cloudflare]: using webdriver "node" "lua\websitebypass\cloudflare.js" "https://w11.mangafreak.net" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"
12:18:31:064 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://w11.mangafreak.net/Manga/Ao_No_Exorcist"

Looking at the LUA I noticed that it checks for the .js or .py file. For some reason I had both. I got rid of the .js file. I am now getting the same error except it says "python" instead of "node".

Any help is appreciated.

**Comment by Hecatom** [comment]
The cloudflare.py is down, it seems

**Comment by bahari15** [comment]
> Using Firefox, node.js and selenium-webdriver
> 
> * Install [node.js](https://nodejs.org/en/download/current/)
> * Install selenium-webdriver. open cmd and type `npm install -g selenium-webdriver`
> * Download [geckodriver](https://github.com/mozilla/geckodriver/releases) into FMD2 directory
> * Create a file named `use_webdriver` in `lua\websitebypass`
> 
> or
> 
> Using Firefox, python and selenium-webdriver
> 
> * Install [python](https://www.python.org/downloads/)
> * Install selenium-webdriver, open cmd.exe and type `pip install selenium`
> * Download [geckodriver](https://github.com/mozilla/geckodriver/releases) into FMD2 directory
> * Download [cloudflare.py](https://raw.githubusercontent.com/dazedcat19/FMD2/master/extras/cloudflare.py) into `lua\websitebypass`
> * Create a file named `use_webdriver` in `lua\websitebypass`

I've done everything that you instructed, tried both methods, yet still failed to load any manga from mangafreak, why is it?

**Comment by Renvix** [comment]
how to install selenium-webdriver. open cmd and type npm install -g selenium-webdriver?

**Comment by Renvix** [comment]
can anybody explain how to do this?
Using Firefox, node.js and selenium-webdriver

    Install node.js
    Install selenium-webdriver. open cmd and type npm install -g selenium-webdriver
    Download geckodriver into FMD2 directory
    Create a file named use_webdriver in lua\websitebypass

**Comment by Renvix** [comment]
>     * FMD2 directory

where FMD2 directory?

**Comment by Renvix** [comment]
After we do this, the manga web can be accessed directly on FMD or are there further steps that must be done?

Using Firefox, node.js and selenium-webdriver

    Install node.js
    Install selenium-webdriver. open cmd and type npm install -g selenium-webdriver
    Download geckodriver into FMD2 directory
    Create a file named use_webdriver in lua\websitebypass

**Comment by TeepoLurking** [comment]
Is there any further instructions for this? For example FMD2 can't list any chapters 
[https://reaperscans.com/comics/316621-the-great-mage-returns-after-4000-years](https://reaperscans.com/comics/316621-the-great-mage-returns-after-4000-years)

Performed these steps:
>     Install node.js
>     Install selenium-webdriver. open cmd and type npm install -g selenium-webdriver
>     Download geckodriver into FMD2 directory
>     Create a file named use_webdriver in lua\websitebypass
![image](https://user-images.githubusercontent.com/54867884/112668610-627bfa80-8e67-11eb-84f9-44de2e8b199e.png)

![image](https://user-images.githubusercontent.com/54867884/112668532-4b3d0d00-8e67-11eb-80f9-53ed61530788.png)

**Comment by Carnivalio** [comment]
Additional info for anyone who wants to use this with python

## Way 1 ■ Forcing FMD to use `Python` instead of `Node.JS`

- Rename `cloudflare.js` into anything but `clouflare.js` (e.g. `_cloudflare.js`) in `lua\websitebypass`
- Restart FMD
- When FMD asks to download it, just skip it

## Way 2 ■ Altering the code in `cloudflare.lua` (cleaner)

- Open `cloudflare.lua` in a text editor (`cloudflare.lua` could be found in `lua\websitebypass`)
- Go to __line 241__ (current build: 2.0.31.0)
- Edit block
```
if fileExist(js_cloudflare) then
	use_webdriver = true
	webdriver_exe = 'node'
	webdriver_script = js_cloudflare
elseif fileExist(py_cloudflare) then
	use_webdriver = true
	webdriver_exe = 'python'
	webdriver_script = py_cloudflare
end
```
  into
```
if fileExist(py_cloudflare) then
	use_webdriver = true
	webdriver_exe = 'python'
	webdriver_script = py_cloudflare
elseif fileExist(js_cloudflare) then
	use_webdriver = true
	webdriver_exe = 'node'
	webdriver_script = js_cloudflare
end
```
- Restart FMD

... and you're set, try going to any website you're having a problem with in FMD, and you should see Firefox will pop up after a while when you click on any titles

## Note

- Doesn't work on bato.to and some other sites (unresolved issues, I have no idea how to download from these sites)
- Some other site needs human verification instead of cookies (ReadComicOnline) in your browser, this way won't work on it

**Comment by TeepoLurking** [comment]
Does this mean I'm doing something wrong and node.js etc. is not set up correctly or the webdriver method just doesn't work for this site? 
I haven't seen any Firefox pop-ups with any titles in my FMD2 favorites.

![fmd2 cf bypass](https://user-images.githubusercontent.com/54867884/118558187-f1720880-b76e-11eb-968d-6003dc7ab5a4.png)

**Comment by molitar** [comment]
What is the command for uninstall the browser popping up is just starting to annoy me anymore.

**Comment by molitar** [comment]
Something strange started happening cloudflare will not get past the browser check when Firefox is in marionette mode. Can open it normally just fine but not marionette.

**Comment by ZeroCool940711** [comment]
Hey guys, any solution to this problem with Cloudflare? 
Right now 90% of the websites I use give the same error shown on the screenshot TeepoLurking shared before, I can't download anything from most of my favorites.

**Comment by xx255q** [comment]
is this still an issue?

**Comment by molitar** [comment]
I think it is many sites I tried did not work anymore.
