### ISSUE TITLE
[website module request] "Mhscans" NEW

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#1214]
### Name

Mhscans

### Root URL

https://mhscans.com/

### Directory list URL

https://mhscans.com/

### Example manga info URL

https://mhscans.com/manga/caminante-del-estigma/

### Example chapter URL

https://mhscans.com/manga/caminante-del-estigma/capitulo-4/

### Language

Spanish

### Website relationship

It is a web made in madara

**Comment by xx255q** [comment]
#1221
