### ISSUE TITLE
[bug-website module] Komikcast

### ISSUE THREAD

**Issue by riedhows** [dazedcat19/FMD2#122]
Prerequisite

 I'm using the latest version.
 All website modules are up to date.
 This is not temporary server issue.
System information
Windows 10 64 Bit

Describe the bug
The chapter lists is not displayed and the genre section is not work

![Untitled](https://user-images.githubusercontent.com/35851136/94341430-669f9a80-0033-11eb-94de-c9b6cd7543b7.png)

**Comment by dazedcat19** [comment]
it's cloudflare protected. please use workaround described here https://github.com/dazedcat19/FMD2/issues/120
