### ISSUE TITLE
[website module request] Kraw.me

### ISSUE THREAD

**Issue by enjoe842** [dazedcat19/FMD2#126]
**Website Information**
* **Name: Kraw** 
* **Root URL: https://kraw.me**
* **Directory list URL: https://kraw.me/all/**

* **Example manga info URL: https://kraw.me/series/a-nice-girl/**
* **Example chapter URL: https://kraw.me/s-mate/raw/episode-89/**

**Additional context**

**Comment by 27136773** [comment]
**@manga-download/hakuneko** => Do not implement
Website cannot be reached from US, DE, SG
[No DNS entry for domain](https://dnschecker.org/#A/kraw.me)
