### ISSUE TITLE
[bug] [TMO][TumangaOnline][LectorTMO] the pages of the chapters dont match

### ISSUE THREAD

**Issue by GATOQSECOMIO** [dazedcat19/FMD2#127]
under v2.0.28
All website modules are up to date.
Win7SP164

**Describe the bug**
the pages of the chapters (downloaded by FMD2 ) dont match the actual number of pages of the web

Manga section link: 
https://lectortmo.com/library/manga/27360/Ningyou-no-Kuni-APOSIMZ

chapters links:
chapter nº39
https://lectortmo.com/view_uploads/606723
chapter nº40
https://lectortmo.com/view_uploads/606728

detected pages chapter:
lectortmo > chapter 39 > 26 pages (web) > only 19 pages downloaded by FMD2
lectortmo > chapter 40 > 27 pages (web) > only 19 pages downloaded by FMD2

Sorry for my bad english
congrats for the project

**Comment by dazedcat19** [comment]
It works fine here.

![img-20200929-122041](https://user-images.githubusercontent.com/59296763/94512363-747d3780-024e-11eb-8e87-2251d81c860f.jpg)

**Comment by GATOQSECOMIO** [comment]
It must be my problem, it was solved today. Maybe it's because of the instability in my network (I use Wi-Fi connection)


In the pre-loading of images it appears the same as yesterday. The results of the pre-load are correct.
![2020-09-29 16_38_05-Free Manga Downloader v2 0 28 0](https://user-images.githubusercontent.com/19736343/94574244-321a2180-0273-11eb-8b3d-61ea5cdc8c4d.jpg)

But the result (the downloaded images) was different.
Today everything seems correct, it must be due to a network instability problem.
![2020-09-29 16_44_11-Capítulo 040 00  KirishimaFansub](https://user-images.githubusercontent.com/19736343/94574621-a228a780-0273-11eb-9a76-3a3a8dccfd4a.jpg)

Sorry for my bad english.
Thanks for the support. This issue is solved.
