### ISSUE TITLE
[bug] Some chapters not updating on Fanfox by check favorites button but works by right click check

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD2#131]
**Prerequisite**
- [x ] I'm using the latest version.
- [ ] All website modules are up to date.

- [x ] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Some chapters will not update in background by pressing the check favorites button or the background check running. But right click on any of these chapters and select update and it works fine.

**To Reproduce**
Save any of these 4 manga as favorite from Fanfox and check for updates it will fail with 0 chapters.

* Yuricam - Yurika no Campus Life
* Iya na Kao Sarenagara Opantsu Misete moraitai: Yo wa Pantsu ga Mitai zo
* Dorakon!
* Maou no Hajimekata

Slasar tested with some other manga and found same problem on Fanfox.   Since I only have the 4 manga I am favorites and following on Fanfox it's the only site I am finding this problem so far.

**Comment by dazedcat19** [comment]
working fine here.

![img-20201005-113945](https://user-images.githubusercontent.com/59296763/95038001-94ee3b80-06ff-11eb-945d-e54abc371e63.jpg)

**Comment by Slasar41** [comment]
If I set the connection number for favorites check to 1, then it'll become like this:
![image](https://user-images.githubusercontent.com/28888646/95114839-bfc3a880-076e-11eb-9adb-9366551ac9b2.png)
If I set it to 8 like the total fanfox favorites, then it'll be fine:
![image](https://user-images.githubusercontent.com/28888646/95115021-06190780-076f-11eb-82d8-d34d038757ea.png)
