### ISSUE TITLE
[bug-website module] Batoto

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#133]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 2004 64-bit

**Describe the bug**
Can't download. Example: https://bato.to/series/80296

**Log**
[https://bato.to/chapter/1523591](https://github.com/dazedcat19/FMD2/files/5337009/chapter1523591.txt)

**Comment by dazedcat19** [comment]
@Slasar41  are other mangas also broken or just this particular manga?
I didn't check the other mangas. please check it.

**Comment by Slasar41** [comment]
Not sure, I tested with just that manga before the fixes.
After the fixes, I tested with 5 random titles and all fine.
But now they changed the code for showing the chapter list so need to be fixed.
