### ISSUE TITLE
Help with fmd2 compile.

### ISSUE THREAD

**Issue by STharanga** [dazedcat19/FMD2#136]
Windows 10.0.19041.488 (2004) x64 
Lazarus-2.0.10 r63526 x64
fpc - 3.2.0
installed all packages according to Build instructions.

I'm new and don't know how to,
**"Make sure to add ssl_openssl to the uses list of Synapse and compile the package again."**
so I missed it. Can you explain how to do it

while building, got this error.
**`BaseThread.pas(21,15) Error: There is no method in an ancestor class to be overridden: "TerminatedSet;"`**

I commented like this (just to check fmd compile,not to fix)
`  // {$ifdef FPC_FULLVERSION>30202}`
`  // procedure TerminatedSet; override;`
`   // {$else}`
`  public`
`    procedure Terminate;`
`   // {$endif}`

then got
**`XQueryEngineHTML.pas(8,22) Fatal: Cannot find xquery used by XQueryEngineHTML. Check if package internettools is in the dependencies.`**
internettools package is installed without error

![fmd2](https://user-images.githubusercontent.com/2016015/95415574-3b2f8080-094e-11eb-8ffa-a92c00d9593a.jpg)
![fmd2-2](https://user-images.githubusercontent.com/2016015/95415576-408ccb00-094e-11eb-8d8d-8999a8b715aa.jpg)

**Comment by dazedcat19** [comment]
TerminatedSet should available in 3.2.2 which is not released yet.
https://bugs.freepascal.org/view.php?id=37388
what is the value of your FPC_FULLVERSION?
![img-20201008-185911](https://user-images.githubusercontent.com/59296763/95450379-ca618600-0998-11eb-9415-705b8c96faba.jpg)

make sure internettools library output in your library path. project options > show options. this is a directory where the *.ppu and *,o files located.
try to use `run > build` or `run > cleanup and build`. to force recompile all missing packages.

**Comment by STharanga** [comment]
fpc fullversion is 30200 .
added internettools path to library path and cleanup and build, still gives the error.

**Comment by dazedcat19** [comment]
Are you using internettools trunk?
I notice there's regression https://github.com/benibela/internettools/commit/809710a81880cd931d462232984f20fb4c85ee97#diff-b098001455c5f403f5ee0e8c7ce22aea
The author removed the unit output dir, maybe by mistake.
Just added them back. Open internettools package and add `lib\$(TargetCPU)-$(TargetOS)` in unit output directory.

**Comment by STharanga** [comment]
Thank you for your help.

I reinstalled lazarus+fpc trunk version and installed internettools with unit output dir fix, and worked.
