### ISSUE TITLE
[bug-website module] "Data" folder files from FMD1 to FMD2?

### ISSUE THREAD

**Issue by traitorAIZEN** [dazedcat19/FMD2#140]
How to migrate/convert my "data" folder files from FMD1 to FMD2?
Since it doesn't have the same naming format.

**Comment by Slasar41** [comment]
Use converter tool.

**Comment by traitorAIZEN** [comment]
isn't that only for the userdata?

**Comment by Slasar41** [comment]
@dazedcat19 I think the converter tool should give an error when `modules.txt` file is missing.
