### ISSUE TITLE
[website module request] !!New Web Reader¡¡ [Hatsuki Manga]

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#148]
**Website Information**
* **Name:** Hatsuki Manga
* **Root URL:** https://hatsukimanga.com/#
* **Directory list URL:** https://hatsukimanga.com/generos

* **Example manga info URL:** https://hatsukimanga.com/biblioteca/obra?id=151
* **Example chapter URL:** https://hatsukimanga.com/biblioteca/viewer?id_capitulo=2910

**Screenshot**

![Screenshot](https://user-images.githubusercontent.com/70826672/96961996-1fd28280-14c3-11eb-8230-bf1204b6f727.png)

**Additional context**
The Web is new as you can see, there are no modules of it in FMD2

**Comment by Slasar41** [comment]
I'm not implementing manga list because there's no easy way to do it.
Just copy the manga link from browser to download with FMD.
