### ISSUE TITLE
[bug-website module] [Hitomi]

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#149]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 Pro 64-bits
32 Ram
Intel Core i9

**Describe the bug**
I have not been able to download the images from hitomi.la correctly, I always get the message [ Failed, try resuming this task! ].

**Screenshot**
![Captura de pantalla (408)](https://user-images.githubusercontent.com/70826672/96963112-4a253f80-14c5-11eb-934c-b47140c5107d.png)

**Additional context**
**Name:** Hitomi
**URL:** https://hitomi.la/

**Log and Downloads.db**
[downloads and Log.zip](https://github.com/dazedcat19/FMD2/files/5427663/downloads.and.Log.zip)

**Comment by gooreat** [comment]
I have the same problem with the site since the last few days and was about to make the same post lol. The download speed keeps going between 0 - 323 Bps and won't go over it and then after a while the "Failed, try resuming the task!" error pop out.

**Comment by Slasar41** [comment]
Should be fixed.
