### ISSUE TITLE
WuxiaWorld can't open

### ISSUE THREAD

**Issue by Qizmo** [dazedcat19/FMD2#150]
Hi, I can open the website WuxiaWorld and look at their manga without any problem. However when I try opening it in Free Manga Downloader V2.0.30.0 I can't see anything.
I can use "update manga list" without problem.
However when I use "Update manga list from server" it will show as "Failed to finish: WuxiaWorld: 404 not found"

All the manga list show below can't be open too. Also if I double-click on any of the manga name, it will turn into "N/A (0)"

**Comment by Slasar41** [comment]
I've added the database to server.
I'm only got a few "N/A" data and it's because the titles can't be found in the website too. Everything else is fine.
