### ISSUE TITLE
[bug] https://1stkissmanga.com/ isnt showing chapter list

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD2#153]
**Prerequisite**
- [ ] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Your operating system.
win 7

**Describe the bug**

im not getting the chapter list from the site https://1stkissmanga.com/manga/reverse-villain/
it works on the old fmd still, but not on this one

![4n6465wn56nes](https://user-images.githubusercontent.com/52017476/97105066-adee6a80-1675-11eb-8fff-9450d71b5068.png)

**Comment by Slasar41** [comment]
Works fine on my end:
![image](https://user-images.githubusercontent.com/28888646/97115305-a76cfb00-1728-11eb-943c-77ff28fa6a70.png)

**Comment by zartzaku** [comment]
I am on win 7 using latest fmd version. work fine on me.
![fmd](https://user-images.githubusercontent.com/14165907/97171655-66282a00-17c0-11eb-82e7-8d83a0ec6abc.png)

**Comment by CloudBladed** [comment]
Download the Modules
