### ISSUE TITLE
[bug] Downloads not pausing anymore after dragging the link?

### ISSUE THREAD

**Issue by gooreat** [dazedcat19/FMD2#156]
**Prerequisite**
- [ ] I'm using the latest version.
- [ ] All website modules are up to date.
- [ ] This is not temporary server issue.

**System information**
Windows 7 Pro

**Describe the bug**
Not sure if this a bug or the feature was simply removed. So when you drag/drop a link to the "Downloads" tab, the link will automatically started where in FMD1 it will paused and you can resume it manually. Not really a big deal, but personally, I'd prefer it that way, especially when you dragging lots of stuff to it and just want to start the download after that.

**To Reproduce**
Just drag any gallery links

**Expected behavior**
Downloads paused automatically (like in FMD1) after dragging the link 

Thanks! :)

**Comment by Slasar41** [comment]
You can change it with this option in Manga Info tab.
![image](https://user-images.githubusercontent.com/28888646/97340230-162b8f00-18b6-11eb-9619-5853f371e33c.png)

**Comment by gooreat** [comment]
@Slasar41 OMG I knew there's an option for it. How did I missed that lmao 

Thanks man. Issue closed!
