### ISSUE TITLE
[bug-website module][mangadex]

### ISSUE THREAD

**Issue by inheritno** [dazedcat19/FMD2#157]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 version 2004

**Describe the bug**
I can't download certain manhwas  from mangadex
https://mangadex.org/title/37071
https://mangadex.org/title/43292
https://mangadex.org/title/33691
https://mangadex.org/title/46790
https://mangadex.org/title/42244

**Screenshots**
![fmd2g](https://user-images.githubusercontent.com/56203943/97616033-b1427700-1a24-11eb-8805-17d989b6c479.jpg)

![fmd2gs](https://user-images.githubusercontent.com/56203943/97616248-fb2b5d00-1a24-11eb-8fe8-623e2aed8374.jpg)

**Additional context**
 TTaskThread, download failed. "The Duchess With an Empty Soul" "The Duchess With an Empty Soul - Ch. 054 [WW]" "/chapter/1083083"

**Comment by Slasar41** [comment]
You need to log in with your account in FMD.
