### ISSUE TITLE
Exhentai/E-hentai issuing IP bans on automated requests from download managers

### ISSUE THREAD

**Issue by serveral1** [dazedcat19/FMD2#160]
This is not a bug but more of a PSA (Here's a thread I made regarding the issue https://forums.e-hentai.org/index.php?showtopic=242879) but as the title says, any requests made are being met by IP bans. Already confirmed this behavior with JDownloader which fetches the galleries via automated requests as well, and just like FMD those requests are resulting with the user's IP getting banned.
Might want to develop a work around, get in touch with Tenboro or just disable the feature to avoid potential user harm.

**Comment by Slasar41** [comment]
Maybe lower the max connections number. I've not tested it.

Edit: Just tested downloading 3 random titles from E-Hentai without lowering the connection number (The connection number is already hard coded to 2) and I'm not getting banned.

**Comment by serveral1** [comment]
Doesn't seem to be a download issue, but a fetch issue because I haven't downloaded anything yet. The requests get rejected/don't load and once that is done if you try to load the site in any browser you're met by a blank page.
I know I'm not alone since I've seen more reports of this behavior happening in other places but for some reason the tests I've done with the fetches have been the most "consistent" to some extent. Still, there seems to be something else that's resulting in these blank pages appearing for me and other users.
Also, thank you for testing, that gave me some insight in regards to the problem and I may close this issue depending on what else I find.

**Comment by Slasar41** [comment]
I've never use JDownloader so I don't know the process of that extension/program that will cause the ban.

**Comment by serveral1** [comment]
I got the server to trigger another ban for trying to fetch a gallery with FMD as well so that's why I originally created the issue, but there seems to be something else that's causing the bans to pop. I'll close the issue for now.
