### ISSUE TITLE
[bug] Mangahasu.se downloads keep failing 

### ISSUE THREAD

**Issue by ExusDragon** [dazedcat19/FMD2#164]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ExusDragon** [comment]
I'm trying to use mangahasu.se/appetite-v9-p30061.html but the download keeps failing

**Comment by Slasar41** [comment]
You've to open any chapter in browser and then do cloudflare workaround:
![image](https://user-images.githubusercontent.com/28888646/98036910-61f9ad80-1e4d-11eb-97c5-983ca94f0d81.png)
Then it'll download just fine.

**Comment by ExusDragon** [comment]
> You've to open any chapter in browser and then do cloudflare workaround:
> ![image](https://user-images.githubusercontent.com/28888646/98036910-61f9ad80-1e4d-11eb-97c5-983ca94f0d81.png)
> Then it'll download just fine.

How do I do that? You guys are out of my league when it comes to this.

**Comment by Slasar41** [comment]
- Open any manga in browser -> press F12 -> Network tab, leave it for now.
- Open any chapter -> select the first one that appear in Network tab.
![image](https://user-images.githubusercontent.com/28888646/98154788-e14bb780-1f07-11eb-9598-8e9da6ea6695.png)
- Search for `Cookie` and `User-Agent` in the right pane, copy all both of them.
![image](https://user-images.githubusercontent.com/28888646/98155181-68992b00-1f08-11eb-8332-541e1b73e7b0.png)
- In FMD, go to Options -> Websites -> Advanced -> mangahasu, change Enabled option to True, paste the cookies and user-agent from browser
![image](https://user-images.githubusercontent.com/28888646/98155262-86ff2680-1f08-11eb-818f-f46f02d2ea1d.png)
then press Apply
