### ISSUE TITLE
[website module request] Web Reader with permissions from the authors to publish their works [Hatsuki Manga]

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#165]
**Website Information**
* **Name:** Hatsuki Manga.
* **Root URL:** https://hatsukimanga.com/
* **Directory list URL:** It does not have, only by gender.

* **Example manga info URL:** https://hatsukimanga.com/biblioteca/obra?id=256
* **Example chapter URL:** https://hatsukimanga.com/biblioteca/viewer?id_capitulo=6294

**Additional context**
New Web Reader with legal works with permissions of the authors translated into Spanish

**Comment by Slasar41** [comment]
You've made the same website request: https://github.com/dazedcat19/FMD2/issues/148
