### ISSUE TITLE
[bug-website module] Batoto needs user login for now

### ISSUE THREAD

**Issue by HiP1** [dazedcat19/FMD2#166]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Windows 10 64bit

**Describe the bug**
some websites closing down lately have caused batoto to be heavily overloaded, they now require user login to prevent people like us to download :D

**Additional context**
Mangadex also has user login requirement, so it might be good as a long term solution for batoto and other related websites like mangapark and mangawindws. I think they use the ACG module.

**Log**

**Comment by Slasar41** [comment]
I tested with random title and FMD can download it.
