### ISSUE TITLE
[bug] import list favoris

### ISSUE THREAD

**Issue by DarkShadowBlood** [dazedcat19/FMD2#168]
Je voudrais importer facilement  ma liste de favoris de FMD 1.3.3.0 a FMD 2.0.30.0 avec les chapitre complet si possible.

I would like to easily import my favorites list from FMD 1.3.3.0 to FMD 2.0.30.0 with full chapters if possible.

Thank

**Comment by Slasar41** [comment]
Use converter tool.
Get it from [here](https://github.com/dazedcat19/FMD2/releases/tag/2.0.21.0).

**Comment by DarkShadowBlood** [comment]
converter_1386-win32.7z + modules.txt = userdata

downloadedchapters.db and settings.json

not  favorites.db and downloads.db

**Comment by Slasar41** [comment]
Looks like the converter 32-bit has a bug.
Do you have Windows 32-bit only? If not, you can try to use converter 64-bit.

**Comment by DarkShadowBlood** [comment]
converter 64-bit = userdata + data

4dc19ea882d046c2a7ac385757e0a514.db + 9d37501925e94fa8a447c0aa34914db6.db + 41867fa36f2f49959df9fef8aa53ffb5.db

converter tool fonctionne pas pour moi, je vais le faire manuellement ... 400 favoris.

converter tool not work for me, i will do it manually ... 400 favorites.

**Comment by DarkShadowBlood** [comment]
bug résolut, retélécharger FMD 1.3.3.0 x64 propre et fait la conversion.

bug solved, re-download clean FMD 1.3.3.0 x64 and do the conversion.
