### ISSUE TITLE
[website module request] Shueisha MangaPlus

### ISSUE THREAD

**Issue by HiP1** [dazedcat19/FMD2#17]
**Website Information**
* **Name:** Shueisha MangaPlus
* **Root URL:** https://mangaplus.shueisha.co.jp/
* **Directory list URL:** https://mangaplus.shueisha.co.jp/manga_list/all

* **Example manga info URL:** https://mangaplus.shueisha.co.jp/titles/100020
* **Example chapter URL:** https://mangaplus.shueisha.co.jp/viewer/1006657

**Additional context**
I saw that HaruNeko found a way to download chapters from MangaPlus.
maybe FMD can also duplicate the site access and download ?
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/ShueishaMangaPlus.mjs

**Comment by Vodes** [comment]
[Tachiyomi also has an Extension](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus) for it which might help
