### ISSUE TITLE
[bug] MangaSWAT doesn't view manga list

### ISSUE THREAD

**Issue by alhatmy** [dazedcat19/FMD2#172]
**Prerequisite**
- [x] I'm using the latest version.
- [x ] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Getting Pop-up error - Failed to finish: MangaSwat: 404 Not Found

**To Reproduce**
1. Go to 'Manga Info'
2. Click on 'MangaSwat' to view manga list
3. Click on 'Do you want to download manga list from the server'

**Expected behavior**
To view then download the list

**Screenshots**

![0202](https://user-images.githubusercontent.com/17156241/98819480-58240b80-2446-11eb-9749-925242888d1f.PNG)

**Comment by Slasar41** [comment]
Database has been added to server.

**Comment by alhatmy** [comment]
> Database has been added to server.

The list works now, but can't view the chapters list nor download anything ..

**Comment by Slasar41** [comment]
Do this: https://github.com/dazedcat19/FMD2/issues/164#issuecomment-721907783
