### ISSUE TITLE
[bug-website module] [Hitomi] [Hentainexus]

### ISSUE THREAD

**Issue by myst771** [dazedcat19/FMD2#176]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Windows 10 Enterprise 64-bits

**Describe the bug**
I have not been able to download the images from these sites correctly:  Hentainexus.com and Hitomi.la, I always get the message [ Failed, try resuming this task! ].

**Additional context**
URL https://hentainexus.com/
URL https://hitomi.la/

**Log**
[fmd log and page source.zip](https://github.com/dazedcat19/FMD2/files/5530866/fmd.log.and.page.source.zip)

**Comment by Slasar41** [comment]
HentaiNexus works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/99004846-52c3df80-2572-11eb-91f3-5d36bd28220f.png)

HitomiLa issue has been reported: https://github.com/dazedcat19/FMD2/issues/149

**Comment by Hecatom** [comment]
I have the same issue.
I downloaded some hours ago some mangas on hentainexus without a problem. (I was using the old FMD)
Then saw some hours later they updated and uploaded 30 new mangas and decided to download them.

The program failed to load the urls.
Jumped online to see if there was some report, saw that there was a FMD2, downloaded it, but this while attempts to add the url, it only load [] () as the name for the folders, and if it tries to download anything, it fails.

Something that i noticed is that now the site is showing the cloudfire anti ddos page before loading the site when i enter to hentainexus, so i suspect it has something to do with that.

**Comment by zillafox** [comment]
I had the same issue as the above. The other manga webs seems to work fine. but when i tried to download from hentainexus, the fmd failed to download and give me the same message as to try to resume the tasks.

However it's true that old fmd seems to work fine on this website.

**Comment by Slasar41** [comment]
Please provide an example link for HentaiNexus.

**Comment by zillafox** [comment]
example link: https://hentainexus.com/view/5392

The sample of the failed downloading progress
![Capture](https://user-images.githubusercontent.com/24423458/101673007-2aec6c80-3a89-11eb-98b8-767205be82f6.PNG)

**Comment by Slasar41** [comment]
Are you sure you can download it just fine with FMD1?

**Comment by zillafox** [comment]
> Are you sure you can download it just fine with FMD1?

Nah, I just tried it. Seems now I cant. It worked fine to me in FMD1 couple days ago when FMD2 got the same error happened at that time. I am not sure what the issue but my browser can browse the website just fine.

**Comment by Slasar41** [comment]
I'm not sure why FMD1 worked fine couple days ago but FMD2 is not. I checked the lua module and it is the same.

I've found the issue but couldn't fix it.
Need someone else who know more about javascript.

**Comment by ramzh** [comment]
Came here to report the same issue. Still happening

**Comment by Hecatom** [comment]
I want to report that i cant access HentaiNexus with FMD2 and now i also cant with FMD1.
It only creates the folders, but fails to download the images.

**Comment by Slasar41** [comment]
HentaiNexus should be fixed.

**Comment by Slasar41** [comment]
HitomiLa should be fixed.
