### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by inheritno** [dazedcat19/FMD2#178]
**Prerequisite**
- [x ] I'm using the latest version.

**System information**
Windows 10 

**Describe the bug**
Swiching between FMD and firefox or explorer cause FMD to freeze and the pop window is showing up.

![errr](https://user-images.githubusercontent.com/56203943/99417617-c82d0880-2902-11eb-8066-1758af1344ec.jpg)

**Additional context**
[log.log](https://github.com/dazedcat19/FMD2/files/5542224/log.log)

**Comment by Slasar41** [comment]
Does this still happen?

**Comment by inheritno** [comment]
No
