### ISSUE TITLE
[bug-website module] BacaManga is not working

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#18]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 2004 64-bit

**Describe the bug**
Manga info and download doesn't work.
Example title: https://bacamanga.co/manga/the-last-human/

**Additional context**

**Log**
Attach your log file containing the issue if available. Also attach the page source if you can. It will help us solve the issue faster. You can get the page source by opening the particular chapter you're unable to download from your browser with right-click > view page source.

**Comment by dazedcat19** [comment]
it force the new challenge for cloudflare which I can't solve yet.
