### ISSUE TITLE
[bug] Can't add a title to favorites

### ISSUE THREAD

**Issue by Geese1** [dazedcat19/FMD2#181]
**Prerequisite**
- [ x] I'm using the latest version.
- [ x] All website modules are up to date.

- [x ] This is not temporary server issue.

**System information**
Windows 10 Home

**Describe the bug**
Using MangaDex, if I try to add the title "Getsuyoubi no Tawawa" to my favorites, it doesn't add it. I already have the one at the address: 

https://mangadex.org/title/19947/getsuyoubi-no-tawawa-twitter-webcomic

 in my favorites, and that's been working fine for a while now, but they recently started a full serialization, located at this address: 

https://mangadex.org/title/57605/getsuyoubi-no-tawawa

and although I can see it in the program (and with the correct address), it won't let me add it to favorites, although I can download chapters from the Manga Info tab. 

**To Reproduce**
1. With the MangaDex library loaded up on the Manga Info tab, use the search function to search for Getsuyoubi no Tawawa, and choose the correct title. Alternately, use the copy the direct website address and paste it into the address bar on the Manga Info tab.
2. Click on the "Add to Favorites" button. The button gets grayed out as if it was successfully added.
3. Go over to your favorites tab, and the title has not been added. 

**Additional context**
At first I thought it was due to the titles being the same, but each of the titles has the correct (read: different) website address for MangaDex, so it should read these as separate titles. Not sure why it's not letting me add this particular title to my favorites list. 

Any help would be appreciated!

**Comment by Slasar41** [comment]
The database need to be updated, the old one added `(Twitter Webcomic)` to the title.
If you paste the new link directly to FMD, you should be able to click on the "Add to Favorites" button.

**Comment by Geese1** [comment]
> The database need to be updated, the old one added `(Twitter Webcomic)` to the title.
> If you paste the new link directly to FMD, you should be able to click on the "Add to Favorites" button.

This worked, but kind of indirectly.

I ultimately had to delete the old favorite, which still just read Getsuyoubi no Tawawa, and at that point I could add the new serialization. I then went and used the address for the original webcomic and pasted that into the search on the program to bring up the re-named original series, and then could add that back in to my favorites as well. So now both are sitting in my favorites and all is well!

Thanks for the help!

**Comment by Slasar41** [comment]
I've updated the manga list database, please download it from server.
It'll bring the correct title and added more new titles.
