### ISSUE TITLE
[website module request] heaventoon.com

### ISSUE THREAD

**Issue by zartzaku** [dazedcat19/FMD2#185]
**Website Information**
* **Name: heaventoon.com/
* **Root URL: https://ww4.heaventoon.com/
* **Directory list URL: https://ww4.heaventoon.com/manga-list/
* **Example manga info URL: https://ww4.heaventoon.com/gosu-the-master/
* **Example chapter URL: https://ww4.heaventoon.com/gosu-the-master-chap-0

**Additional context**
this site got a few up to date manhwa such as Gosu (The Master).

**Comment by Slasar41** [comment]
It's already supported as HeavenManga.
I'll change the name and update the domain.
