### ISSUE TITLE
[feature request] "downloaded" flag option

### ISSUE THREAD

**Issue by myst771** [dazedcat19/FMD2#186]
**Is your feature request related to a problem? Please describe.**
I've been searching for a feature that allows to mark some of the chapters or manga as "downloaded", but couldn't find any.

**Describe the solution you'd like**
As mentioned, I would like to mark some of the mangas or chapters like "downloaded" inside the program. Some sites are very picky, even when the workaround on cloudflare sites is implemented, so I have to download "manually", but I forget (most of the time) that I've already downloaded that particular chapter/manga.

**Describe alternatives you've considered**
The option, besides add to favorites, to add to the "downloaded" section, thus in the future I know that manga is already in my library. Also the option of a pop-up message (like the one that appears when FMD identifies one already downloaded)

**Additional context**

**Comment by Slasar41** [comment]
There's already a highlight for the chapters that have been downloaded.
![image](https://user-images.githubusercontent.com/28888646/100603678-04fff300-3338-11eb-9310-6375a75093ba.png)
And if you trying to download the chapters that have been downloaded, FMD will detect the files already on your folder and skipped that chapter.

**Comment by myst771** [comment]
Thanks for the info!
