### ISSUE TITLE
[dev] Changing of pre-loaded libraries

### ISSUE THREAD

**Issue by dazedcat19** [dazedcat19/FMD2#19]
Currently we load all pascal libraries to lua vm right away. This cost some resources.
To reduce it, I'd like to move most of the rarely used libraries to luapackage. So, to load it we can use `require()`.
To implement it we may need to change many of website modules that require them. `luabaseunit` most likely to be the only one left as pre-loaded library.

@Slasar41

**Comment by Slasar41** [comment]
Okay, what should I do?
Could you give me the example?

**Comment by dazedcat19** [comment]
look at `luasynautil.pas, luasynacode.pas, luacrypto.pas ...` inside `baseunits\lua`
there's many libraries that never used by website modules. the most used I think is `luabaseunits.pas`.
instead of loading all of them at lua_open, we can move those libraries to luapackage which register a lua loader.
so if we want to use `EncodeURLElement()` we should load it first with `require "synautil"`.
or load it to a table `synutil = require "synautil"`.
what do you think, should we load it to a global table or a local table?

**Comment by dazedcat19** [comment]
this is an example of fanfox which use fmd and mangafoxwatermark.
```lua
...
	local m = AddWebsiteModule('0d3653a8d9b747a381374f32e0a1641e', 'FanFox', 'https://fanfox.net', cat)
	local fmd = require 'fmd'
	local slang = fmd.SelectedLanguage
	local lang = {
		['en'] = {
			['removewatermark'] = 'Remove watermark',
			['saveaspng'] = 'Save as PNG'
		},
		['id_ID'] = {
			['removewatermark'] = 'Hapus watermark',
			['saveaspng'] = 'Simpan sebagai PNG'
		},
		get =
			function(self, key)
				local sel = self[slang]
				if sel == nil then sel = self['en'] end
				return sel[key]
			end
	}
	m.OnAfterImageSaved = 'AfterImageSaved'
	m.AddOptionCheckBox('mf_removewatermark', lang:get('removewatermark'), true)
	m.AddOptionCheckBox('mf_saveaspng', lang:get('saveaspng'), false)
	
	local mf = require 'mangafoxwatermark'
	mf.LoadTemplate(fmd.LuaDirectory .. 'extras\\mangafoxtemplate')
end
...
function AfterImageSaved()
	if MODULE.GetOption('mf_removewatermark') then
		local mf = require 'mangafoxwatermark'
		mf.RemoveWatermark(FILENAME, MODULE.GetOption('mf_saveaspng'))
	end
	return true
end
```

**Comment by Slasar41** [comment]
I see, it's fine I guess.
So if a website use a library that rarely used, then just need to add `require 'library'`.
That way the library only loaded when needed by that website.
We need to list the most used libraries so no need to change them.

**Comment by dazedcat19** [comment]
I already changed most rarely used library. I will push it to master after new release, since it will break the modules.
only these left `LuaBaseUnit, LuaSynaUtil, LuaSynaCode, `.
maybe `luaStrings` too. for TStrings.Create.
`LuaSynaCode` and `LuaCrypto` can be merged I think.
Most used are `LuaBaseUnit and LuaSynaUtil`. I think I will just leave them as global function register.
But not adding them as a package is such a waste. It register a lot of  functions. and not all modules actually use them.
The way fmd works is when calling a lua function, it may use a new lua_state which only used to call that function alone. There's a module with a function that doesn't use them. So, it's a waste to register everything. 
The most used libraries is luabaseunit. It has MaybeFillHost, IncStr, etc. But there's also a function that never use it. But adding them as package requires to add `require 'baseunit'` as the first line in every lua function. 
Maybe split them between what most used and rarely used.
Can you look at the website modules and list what mostly used. Maybe it's faster to use sed or some search utility.
- MaybeFillHost
- FillHost
- IncStr

**Comment by Slasar41** [comment]
Sorry, I'm still not quite understand.
Like this?
- 8Muses.lua: RemoveURLDelim, MaybeFillHost, Add, Create, Count, GET, ToString,
- 9ekor.lua: MaybeFillHost, InvertStrings, Trim, Add, Create, GET, ToString,

FillHost only used in YoungAceUp module.
What's the different between MaybeFillHost and FillHost?

**Comment by dazedcat19** [comment]
MaybeFillHost will add root url if there's none.
FillHost will add root url or replace it if exist.

No, I mean the global function pushed by luabaseunit, luasynautil ...
Add, Create, GET, ToString is owned by class object. they're pushed along by the object. So it's not a problem.

If I remove them from preloaded libraries then the website module has to load it first before using it.
eg:
```lua
function GetInfo()
  require 'fmd.base'
  u = MaybeFillHost(
```

Look at luabaseunit.pas, these are the global function pushed to lua vm.
```pascal
  luaPushFunctionGlobal(L, 'Pos', @lua_pos);
  luaPushFunctionGlobal(L, 'Trim', @lua_trim);
  luaPushFunctionGlobal(L, 'ExtractFileName', @lua_extractfilename);
  luaPushFunctionGlobal(L, 'ExtractFileNameOnly', @lua_extractfilenameonly);
  luaPushFunctionGlobal(L, 'MaybeFillHost', @lua_maybefillhost);
  luaPushFunctionGlobal(L, 'FillHost', @lua_fillhost);
  luaPushFunctionGlobal(L, 'GetHostURL', @lua_gethosturl);
  luaPushFunctionGlobal(L, 'RemoveHostFromURL', @lua_removehostfromurl);
  luaPushFunctionGlobal(L, 'SplitURL', @lua_spliturl);
  luaPushFunctionGlobal(L, 'InvertStrings', @lua_invertstrings);
  luaPushFunctionGlobal(L, 'MangaInfoStatusIfPos', @lua_mangainfostatusifpos);
  luaPushFunctionGlobal(L, 'AppendURLDelim', @lua_appendurldelim);
  luaPushFunctionGlobal(L, 'AppendURLDelimleft', @lua_appendurldelimleft);
  luaPushFunctionGlobal(L, 'RemoveURLDelim', @lua_removeurldelim);
  luaPushFunctionGlobal(L, 'RemoveURLDelimLeft', @lua_removeurldelimleft);
  luaPushFunctionGlobal(L, 'HTMLDecode', @lua_htmldecode);
  luaPushFunctionGlobal(L, 'HTMLEncode', @lua_htmlencode);
  luaPushFunctionGlobal(L, 'URLDecode', @lua_urldecode);
  luaPushFunctionGlobal(L, 'IncStr', @lua_incstr);
  luaPushFunctionGlobal(L, 'StreamToString', @lua_streamtostring);
  luaPushFunctionGlobal(L, 'StringToStream', @lua_stringtostream);
  luaPushFunctionGlobal(L, 'Round', @lua_round);
  luaPushFunctionGlobal(L, 'TrimStrings', @lua_trimstrings);
  luaPushFunctionGlobal(L, 'GetCurrentTime', @lua_getcurrenttime);
  luaPushFunctionGlobal(L, 'EncryptString', @lua_encryptstring);
  luaPushFunctionGlobal(L, 'DecryptString', @lua_decryptstring);
  luaPushFunctionGlobal(L, 'Base64Encode', @lua_Base64Encode);
  luaPushFunctionGlobal(L, 'Base64Decode', @lua_Base64Decode);

  luaPushFunctionGlobal(L, 'SerializeAndMaintainNames', @lua_SerializeAndMaintainNames);
```

the other pre-loaded libraries is in luabase.pas
```pascal
procedure LuaBaseRegister(const L: Plua_State);
begin
  luaPushFunctionGlobal(L, 'print', @luabase_print);
  luaPushFunctionGlobal(L, 'Sleep', @luabase_sleep);

  luaBaseUnitRegister(L);
  luaSynaUtilRegister(L);
  luaSynaCodeRegister(L);

  luaClassRegisterAll(L);
end;        
```

It push a lot of function that never used. Maybe it's a good idea to split them to a new package.
so, `require fmd.base` will only load the essentials
- MaybeFillHost
- IncStr
...
The rest would be in `fmd.baseutils`.
Or just replace them with native lua solution?
MaybeFillHost, IncStr, can be done with `string.gsub()`

**Comment by dazedcat19** [comment]
development moved to dev branch
