### ISSUE TITLE
[website module request] mangasusu

### ISSUE THREAD

**Issue by enjoe842** [dazedcat19/FMD2#191]
**Website Information**
* **Name:** mangasusu
* **Root URL:** https://www.mangasusu.pw/
* **Directory list URL:** https://www.mangasusu.pw/manga-list

* **Example manga info URL:** https://www.mangasusu.pw/manga/a-knowing-sister
* **Example chapter URL:** https://www.mangasusu.pw/manga/a-knowing-sister/chapter-01

**Additional context**

**Comment by Slasar41** [comment]
It's already supported, but need to update the domain.
