### ISSUE TITLE
[website module request] [Mangas.in]

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#192]
**Website Information**
* **Name:** Mangas.in
* **Root URL:** https://mangas.in
* **Directory list URL:** https://mangas.in/manga-list

* **Example manga info URL:** https://mangas.in/manga/i-am-the-sorcerer-king
* **Example chapter URL:**  https://mangas.in/manga/i-am-the-sorcerer-king/112-1i49a/1

**Additional context**
![Screenshot](https://user-images.githubusercontent.com/70826672/101123289-2243f400-35ba-11eb-971b-b0d256a7cce4.png)

**Comment by Slasar41** [comment]
It's already supported.
Do you have any issue?

**Comment by CloudBladed** [comment]
> It's already supported.
> Do you have any issue?

Ah, I thought it was that I was not, well, yes. It doesn't carry anything.
![Captura de pantalla (16)](https://user-images.githubusercontent.com/70826672/101197519-d334a800-3627-11eb-9aa6-c320fd128004.png)

**Comment by Slasar41** [comment]
There's already an open issue for it: https://github.com/dazedcat19/FMD2/issues/86
