### ISSUE TITLE
[bug-website module] HeroScan

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#194]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 20H2 64-nit

**Describe the bug**
Some chapters can't be downloaded. Example: https://heroscan.com/manga-youngest-princess.html
It can be downloaded with FMD1 just fine.

**Additional context**
I noticed the image link isn't secure, is it related?
![image](https://user-images.githubusercontent.com/28888646/101212870-0587e900-36ac-11eb-9581-28d03841854e.png)

**Log**
[https://heroscan.com/read-youngest-princess-chapter-1.html](https://github.com/dazedcat19/FMD2/files/5645365/tempfile.log)

**Comment by Inareous** [comment]
`isekaiscan.b-cdn.net` doesn't accept illegal header (referer) and will return 403. However, even after removing referer it seems that the cdn timeout on multiple traffic.

**Comment by Slasar41** [comment]
I see. FMD1 doesn't have this issue because the referer isn't being applied to all websites.
