### ISSUE TITLE
[bug-website module] BacaKomik

### ISSUE THREAD

**Issue by miawaw** [dazedcat19/FMD2#201]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win-7 32

**Describe the bug**
Failed to finish download the manga list on https://bacakomik.co/
Example: 
![eng bug bacakomik](https://user-images.githubusercontent.com/75097226/101522693-286f1180-39ba-11eb-8a3d-e59fc7e32b79.png)

**Comment by Slasar41** [comment]
That's because the manga list database isn't in the server yet.
I've uploaded the database, you should be able to download it now.
