### ISSUE TITLE
fmd2 roto al usar converter para pasar lista de favoritas de fmd original[bug]

### ISSUE THREAD

**Issue by Jacobo-Estanol-Hernandez** [dazedcat19/FMD2#205]
**Prerequisite**
- [yes] I'm using the latest version.
- [yes] All website modules are up to date.

- [not ] This is not temporary server issue.

**System information**
windows 10 1909
**Describe the bug**
FMD2 deja de funcionar 
**To Reproduce**
1. usar converter.exe
2. copiar el resultado de la operación en FMD2
3. abrir FMD2 ir a favoritos
4. intentar buscar actualizaciones 
5.- ver el error no hace nada
6.- si pides ver información no hace nada 

**Expected behavior**
que hiciera lo mismo que FMD mostrarme los nuevos capítulos y dejarme descargarlos

**Additional context**
al usar converter.exe en FMD para pasar mi lista de favoritos a FMD2 me creo un par de carpetas como dice el tutorial
pero al pegarlos en FMD2 este dejo de funcionar 
me muestra la lista de favoritos pero no puedo buscar actualizaciones de los mangas 
y tampoco me muestra la información de los sitios 
ademas quitaron el soporte para samurai scan 

espero exista un modo de mudar mi lista de favoritos y que FMD2 sigua funcionando

**Comment by Slasar41** [comment]
Make sure you also downloaded `modules.txt` and place along side with `converter.exe`.

**Comment by kuso-ge** [comment]
Make sure to also use the right converter.exe

**Comment by Slasar41** [comment]
No further response.
Closed.
