### ISSUE TITLE
[bug-website module] [Es.Niadd]

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#207]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
W 10 Pro 2004

**Describe the bug**
The problem lies in the download, I load well all the information in the Manga, but only that does not download the chapters and the library does not work, but that is relative because it works with the URLs.

**Screenshot**
![Captura de pantalla (20)](https://user-images.githubusercontent.com/70826672/101955935-53c54c80-3bc4-11eb-9432-9e4bb100b431.png)
![Captura de pantalla (18)](https://user-images.githubusercontent.com/70826672/101955937-54f67980-3bc4-11eb-942a-1f866878eb8c.png)

**Log**
view-source:https://es.niadd.com/manga/The_Descent_to_Earth_of_The_Great_Pussy_Virgin/chapters

**Comment by Slasar41** [comment]
Just tested and all of it works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/101959589-2c0fcc00-3c38-11eb-93ac-833274e95eca.png)
