### ISSUE TITLE
[bug-website module] Neox Scanlator url change

### ISSUE THREAD

**Issue by ayanamichie** [dazedcat19/FMD2#208]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
I was checking for new chapter and noted it failed to find any, so i pasted on the browser, same happened. 
Then a simple google check i found out the site url changed.

Site changed url from: https://neoxscan.net/manga/release-that-witch-br/
to: https://neoxscans.net/manga/release-that-witch/

seems like the domain changed

**Comment by Slasar41** [comment]
I couldn't access the new url.
![image](https://user-images.githubusercontent.com/28888646/101993324-368b9d80-3cec-11eb-8835-13ada6921ac5.png)

**Comment by ayanamichie** [comment]
maybe region lock? i can:
![image](https://user-images.githubusercontent.com/48865118/102001520-03d4ab80-3cd2-11eb-9e82-384c3a5df0e4.png)
I am from Brazil so that may be why.
the older one really don't work:
![image](https://user-images.githubusercontent.com/48865118/102001560-54e49f80-3cd2-11eb-993a-a78d2b10d994.png)

**Comment by Slasar41** [comment]
Please test and close if ok.

**Comment by ayanamichie** [comment]
Yep its working thanks
