### ISSUE TITLE
new mangadex DDOS 

### ISSUE THREAD

**Issue by fales13** [dazedcat19/FMD2#209]
**Prerequisite**
- [v ] I'm using the latest version.
- [v ] All website modules are up to date.

- [v ] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Can't download from mangadex, 

**Additional context**
probably had any thing todo with this,
![image](https://user-images.githubusercontent.com/37041682/101979944-10d2aa00-3c94-11eb-95f5-4870913a5f25.png)

**Comment by fales13** [comment]
> Yes, FMD can't solve the captcha automatically. Need users interactions.
> If it still happen, try this: [#187 (comment)](https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964)

thanks for your reply...

i stop all request to mangadx from all my device for one hour, limit task to 1 and thread to 2, and FMD worked fine

**Comment by Slasar41** [comment]
Looks like MangaDex disabled the verification and FMD can access the website normally again.
