### ISSUE TITLE
„Suppordet Websites“ links to old Wiki without a list of supported websites

### ISSUE THREAD

**Issue by jfml** [dazedcat19/FMD2#211]
Hi, just wanted to try this out and I saw that in the section „About FMD“ clicking on „Supported Websites“ (Links is https://github.com/fmd-project-team/FMD/wiki/Supported-Websites ) redirects to the Main Page of the Wiki ( https://github.com/fmd-project-team/FMD/wiki ).

**Comment by Slasar41** [comment]
I will just removed it.
