### ISSUE TITLE
[bug-website module] Mangalib.me

### ISSUE THREAD

**Issue by makharius** [dazedcat19/FMD2#219]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 64-bit Build 19042

**Describe the bug**
FMD stopped receiving the list of chapters and manga info from mangalib.me
![2020-12-17_211715](https://user-images.githubusercontent.com/49916865/102527561-4f120400-40ae-11eb-9bb9-c2f6525ed2b0.jpg)

Example: [https://mangalib.me/100-nin-no-eiyuu-o-sodateta-saikyou-yogensha-wa-boukensha-ni-natte-mo-sekaijuu-no-deshi-kara-shitawarete-masu](url)

**Additional context**
Log show ERROR: WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet.
After trying the solution from [https://github.com/dazedcat19/FMD2/issues/120](url) it show 
21:13:30:114 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)

**Log**
[fmd1.log](https://github.com/dazedcat19/FMD2/files/5711417/fmd1.log)
[fmd2.log](https://github.com/dazedcat19/FMD2/files/5711420/fmd2.log)
[source.txt](https://github.com/dazedcat19/FMD2/files/5711458/source.txt)

**Comment by Slasar41** [comment]
Try this: https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964

**Comment by makharius** [comment]
Unfortunately it didn't help.

**Comment by Slasar41** [comment]
I can't test it myself.
![image](https://user-images.githubusercontent.com/28888646/102531985-d9219300-40d5-11eb-977a-b44f94e64848.png)

**Comment by makharius** [comment]
Maybe it's a regional block? The site opens from Russia. I tried cookies before and after login in my account, but log still show the same ERROR: WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet.

**Comment by makharius** [comment]
I also tried using Python instead of node.js and now in the log I get
 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://mangalib.me" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
21:45:54:548 ERROR: WebsitBypass[cloudflare]: webdriver can't find cookie 'cf_clearance'

**Comment by Baltazar500** [comment]
Win7 x64 SP1, fmd_2.0.31.0_i386-win32, all website modules are up to date. I am getting the same error in the log

>18:59:32:016 ERROR: WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet

Through BURP I got this html and headers  : 

[FMD2+mangalib+cloudflare-530.txt](https://github.com/dazedcat19/FMD2/files/7292398/FMD2%2Bmangalib%2Bcloudflare-530.txt)

How do I change HTTP/1.1 to HTTP/2? This works for bypass cloudflare in some cases

**Comment by Slasar41** [comment]
@Baltazar500 Maybe you can discuss it with people that know about it in the Discord server: https://discord.com/invite/cXKKgw3

**Comment by Baltazar500** [comment]
@Slasar41, My English is bad (and I use google translate for help), replies in the messenger will be slow and will only be textual (I speak much worse English). Better to write in a thread. Or is it a private dialogue? Maybe an email?
