### ISSUE TITLE
[bug-website module] Mangadex

### ISSUE THREAD

**Issue by HiP1** [dazedcat19/FMD2#22]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Your operating system.
Windows 10
**Describe the bug**
It was working fine just earlier today. but now, I can't download from mangadex anymore.
i can browse mangas and their chapters, though.

**Additional context**

**Log**
[pagesource.txt](https://github.com/dazedcat19/FMD2/files/4767642/pagesource.txt)
[fmd.log](https://github.com/dazedcat19/FMD2/files/4767633/fmd.log)

**Comment by HiP1** [comment]
i thought i was banned by the site at first, but as it works on a normal web browser, with the same user agent, it seems something else happened

**Comment by Thrieze** [comment]
I downloaded from them fine about 10 min ago. I have a login set in FMD for mangadex, thats all thats different.

**Comment by HiP1** [comment]
I use a login too.
I tried with cookies, but no luck.

**Comment by HiP1** [comment]
@Slasar41 thanks for the fix!
