### ISSUE TITLE
[bug-website module] PojokManga

### ISSUE THREAD

**Issue by miawaw** [dazedcat19/FMD2#220]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win 7-32

**Describe the bug**
Before updating manga list, it can't display manga title and chapter list.
Example :
![pm](https://user-images.githubusercontent.com/75097226/102542480-72f03c80-40e4-11eb-888c-a39401dc75ba.png)

After I checked the website, the web url has changed.

Example : https://pojokmanga.com/manga/martial-peak/ changed to https://pojokmanga.com/komik/martial-peak/

**Update Website Information**
* **Name:** **PojokManga**
* **Root URL:** https://pojokmanga.com/
* **Directory list URL:** https://pojokmanga.com/komik/

* **Example manga info URL:** https://pojokmanga.com/komik/martial-peak/
* **Example chapter URL:** https://pojokmanga.com/komik/martial-peak/chapter-659/

Please fix it. Thank you.

**Comment by Slasar41** [comment]
You just need to fresh update the manga list.
I've updated the manga list database with the new link so you can get it with `Download from server`.
