### ISSUE TITLE
[website module request] ComicKiba

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD2#221]
**Website Information**
* **Name:** ComicKiba
* **Root URL:**https://comickiba.com
* **Directory list URL:**https://comickiba.com/manga

* **Example manga info URL:**https://comickiba.com/manga/cultivator-against-hero-society
* **Example chapter URL:**https://comickiba.com/manga/cultivator-against-hero-society/chapter-53

**Languages**
List of languages supported by the website

**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...")

**Additional details**
Add any other context details that you may have found (like template to reuse)

Can you add support for this site? It should be easy to do because template design was very similar to other site

**Comment by Slasar41** [comment]
Already supported: https://github.com/dazedcat19/FMD2/commit/9cba458d827009b3d9e29e76992d66e6ed1ba1b5
