### ISSUE TITLE
[bug-website module] Toonily

### ISSUE THREAD

**Issue by Worrend** [dazedcat19/FMD2#222]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 

**Describe the bug**
From this evning using  FMD2 on toonily.com I can view manga info without problems but when I try to download something it alwyas fail. It will start, try and then appear "Failed, try resuming this task!".

**Additional context**
Using a normal web browser it is working just fine.

**Log**
From the log it seem to be a cloudflare problem? I attach it.
[fmd.log](https://github.com/dazedcat19/FMD2/files/5718713/fmd.log)

**Comment by Krabbyos** [comment]
I had this issue too. For some reason, Toonily downloads fail if '/' is missing from the end of the referer header (maybe related to toonily now serving from a cdn subdomain).

Tracked the problem down to function BeforeDownloadImage() in Madara.lua
Changing the line from 
`HTTP.Headers.Values['referer'] = MODULE.RootURL`
to
`HTTP.Headers.Values['referer'] = MODULE.RootURL .. '/'`
fixes downloads from toonily. Dunno if adding it fucks up other sites using the Madara module though. (dunno whether it's better to just special case toonily or always add it *shrugs*)

**Comment by Slasar41** [comment]
I'll change it for all the websites in Madara.
I just tested with 3 Madara websites and all working fine.
If I received multiple reports from other websites, then I'll change it for Toonily only.
