### ISSUE TITLE
tumangaonline update?

### ISSUE THREAD

**Issue by angeltonio** [dazedcat19/FMD2#227]
I have the last version, but when I want to find one or two manga that i watch, i can't find it, but on the web are there, maybe it's about the update??

**Comment by Slasar41** [comment]
You can copy the link from browser to FMD.

**Comment by angeltonio** [comment]
And what it's the problem with download??...i can't download any manga from TuMangaOnline..always it's a error..

**Comment by Slasar41** [comment]
If it broken then please create the proper issue template `Website module report`.
