### ISSUE TITLE
[website module request] doujindesu.info

### ISSUE THREAD

**Issue by myth-riel** [dazedcat19/FMD2#228]
**Website Information**
* **Name:** Doujindesu 
* **Root URL:**
* https://doujindesu.info/
* **Directory list URL:**
* https://doujindesu.info/komik-list/

* **Example manga info URL:**
* https://doujindesu.info/manga/a-wonderful-new-world/
* **Example chapter URL:**
* https://doujindesu.info/2020/12/21/a-wonderful-new-world-chapter-80/

**Languages**
Indonesia

**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...")

**Additional details**
wp mangastream ??

**Comment by ebot-ui** [comment]
Hhvh

**Comment by reyhan3663** [comment]
Halo
