### ISSUE TITLE
ManhuaUS blocked by cloudflare. Must use cookies+user agent walkaround

### ISSUE THREAD

**Issue by spamtaztik** [dazedcat19/FMD2#230]
**Prerequisite**
- [Y ] I'm using the latest version.
- [ Y] All website modules are up to date.

- [ Y] This is not temporary server issue.

**System information**
Windows 10 Pro

**Describe the bug**
From about 5-6 hrs ago my copy of FMD can no longer download from manhuaus. I can't even open manga info. When opened from browser it showed the "cloudflare protection" page. I have to use the cookies & user_agent walkaround to be able to access the site normally. LUA update needed maybe?

**Comment by kuso-ge** [comment]
Have you checked #120 ?

**Comment by spamtaztik** [comment]
Yes, I have, but I just haven't gotten around to actually doing it. I just thought it -might- be solved with an lua update.
I'll try to get to it tonight.
