### ISSUE TITLE
[bug] minor-Stopped counter not updating automatically from Manga Info

### ISSUE THREAD

**Issue by kuso-ge** [dazedcat19/FMD2#231]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 Home 20H2(19042.685)
16GB 2133 MHz RAM
i5-6300HQ
FMD2 v2.0.30.0

**Describe the bug**
From [Manga Info] Tab, if you checked the [Add to download list as stopped task], and hit the download button, the [Stopped (#)] tasks counter isn't updated automatically and stays [Stopped (0)]. 

**To Reproduce**
1. Go to 'Manga Info' Tab
2. Load any manga on the URL
3. Select any/all chapters to download
4. Click on the checkbox 'Add to download list as stopped task' 
5. Hit download
6. Go back to Downloads Tab and check Stopped (#) tasks counter not updating

**Expected behavior**
The Stopped (#) tasks should correctly updates its counter when you add manga download as stopped task from Manga Info Tab.

**Screenshots**
![Screenshot (89)_LI](https://user-images.githubusercontent.com/12083007/102891354-fe791d00-4498-11eb-88ca-d42eba546e12.jpg)

**Comment by Slasar41** [comment]
Yeah I think it's not registered as downloads task yet.
If you resume and then stopped it, the counter will be updated.

**Comment by brazenvoid** [comment]
It is indeed an annoying issue.
