### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by CCentaur** [dazedcat19/FMD2#232]
**Prerequisite**
- [ x] I'm using the latest version.
- [ x] All website modules are up to date.

- [ x] This is not temporary server issue.

**System information**
Your operating system.
Windows 7 64
8gb ram
1tb spinning rust
i3-3227u
**Describe the bug**
Not sure if this is a FMD2 problem or not. FMD2 doesn't seem to be able to save files to the HD from any site.
**To Reproduce**
select any manga site, select any chapter and hit download, chapter shows up on download que, trys to down load and fails. same for any favorites.

log shows this error for all the attempted jpg downloads

18:54:22:336 SaveImageStreamToFile.WriteToFile Failed! C:\Users\Tech\Desktop\dd\Manga\Arafoo Shachiku No Golem Master\Chapter 017 Recruiting Failure!!\001.jpg (13 Items)
  EFCreateError - Unable to create file "C:\Users\Tech\Desktop\dd\Manga\Arafoo Shachiku No Golem Master\Chapter 017 Recruiting Failure!!\001.jpg": Access is denied.
    $0000000100053CFC
    $0000000100053BC5
    $000000010003C828  SAVEIMAGESTREAMTOFILE,  line 2297 of ../baseunits/uBaseUnit.pas
    $000000010003CA07  SAVEIMAGESTREAMTOFILE,  line 2333 of ../baseunits/uBaseUnit.pas
    $00000001000411BC  DOWNLOADIMAGE,  line 395 of ../baseunits/uDownloadsManager.pas
    $00000001000413E8  DODOWNLOAD,  line 438 of ../baseunits/uDownloadsManager.pas
    $0000000100040D00  EXECUTE,  line 320 of ../baseunits/uDownloadsManager.pas
    $000000010005C219
    $0000000100004356
    $0000000100015741
    $000000007719570D
    $00000000773F385D
 
**Expected behavior**

**Screenshots**

**Additional context**
history. i'm attempting to move up to FMD2 from FMD. i ran the converter copied the directorys from FMD directory to the FMD2 directory.

FMD still works and saves files
so i may have missed a step, and this my not even be an FMD2 issue

**Comment by Slasar41** [comment]
Maybe you've activated Controlled folder access in Windows Defender and haven't whitelist FMD2?

**Comment by CCentaur** [comment]
i don't use windows defender

**Comment by Slasar41** [comment]
Try saving the manga not to your user folder.
Maybe to FMD folder or D: drive.

**Comment by CCentaur** [comment]
ok, not sure what permission setting that i changed to fix the problem. But i deleted all users in the security tap and re-added them. then i took ownership instead of the administrators group.

sorry Slasar41 i didn't get a chance to see your post before i had done the other.
