### ISSUE TITLE
[bug-website module] LHTranslation

### ISSUE THREAD

**Issue by Trollam** [dazedcat19/FMD2#24]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 64-bit

**Describe the bug**
I can't download any chapters from LHTranslation, some manga are not displayed in the manga list and when I copy/paste the url the info load correctly but not the chapters list.
-Sono Mono. Nochi ni…(Nariie Shinichirou) : chapters list not loaded/updated
-Yankee Wa Isekai De Seirei Ni Aisaremasu. : chapters list not loaded/updated
-Tensei Shitara Ken deshita : can't download
-Nise Seiken Monogatari: Osananajimi no Seijo o Uttara Michizure ni Sareta : can't download

[downloads.zip](https://github.com/dazedcat19/FMD2/files/4772865/downloads.zip)

**Additional context**
For the manga with a problem on the chapters list, maybe it's related to the punctuations in the name/url ?
I also tried the workaround suggested here : https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation, but it does not work.

**Log**
[fmd.log](https://github.com/dazedcat19/FMD2/files/4772847/fmd.log)
[view-source_https___lhtranslation.net_read-sono-mono.-nochi-ninariie-shinichirou-chapter-18.txt](https://github.com/dazedcat19/FMD2/files/4772849/view-source_https___lhtranslation.net_read-sono-mono.-nochi-ninariie-shinichirou-chapter-18.txt)
[view-source_https___lhtranslation.net_read-yankee-wa-isekai-de-seirei-ni-aisaremasu.-chapter-31.txt](https://github.com/dazedcat19/FMD2/files/4772851/view-source_https___lhtranslation.net_read-yankee-wa-isekai-de-seirei-ni-aisaremasu.-chapter-31.txt)
[view-source_https___lhtranslation.net_read-tensei-shitara-ken-deshita-chapter-37.txt](https://github.com/dazedcat19/FMD2/files/4772853/view-source_https___lhtranslation.net_read-tensei-shitara-ken-deshita-chapter-37.txt)
[view-source_https___lhtranslation.net_read-nise-seiken-monogatari-osananajimi-no-seijo-o-uttara-michizure-ni-sareta-chapter-2.txt](https://github.com/dazedcat19/FMD2/files/4772855/view-source_https___lhtranslation.net_read-nise-seiken-monogatari-osananajimi-no-seijo-o-uttara-michizure-ni-sareta-chapter-2.txt)
[view-source_https___lhtranslation.net_read-nise-seiken-monogatari-osananajimi-no-seijo-o-uttara-michizure-ni-sareta-chapter-3.txt](https://github.com/dazedcat19/FMD2/files/4772857/view-source_https___lhtranslation.net_read-nise-seiken-monogatari-osananajimi-no-seijo-o-uttara-michizure-ni-sareta-chapter-3.txt)
[view-source_https___lhtranslation.net_read-nise-seiken-monogatari-osananajimi-no-seijo-o-uttara-michizure-ni-sareta-chapter-1.txt](https://github.com/dazedcat19/FMD2/files/4772858/view-source_https___lhtranslation.net_read-nise-seiken-monogatari-osananajimi-no-seijo-o-uttara-michizure-ni-sareta-chapter-1.txt)

**Comment by Slasar41** [comment]
Should be fixed.
