### ISSUE TITLE
[website module report/bug] Lovehug posible image download bug.

### ISSUE THREAD

**Issue by GDXN** [dazedcat19/FMD2#243]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
FMD2 downloads the chapter page images as webp instead of jpg.

**Additional context**
When I use Firefox and Chrome to download the chapter as a fullpage they are downloades as jpg and if I download the chapter page html with Free Download Manager the images are also listed as jpg. I tried to change the user-agent but the problem issue persist.

A example page with the issue: https://lovehug.net/173/36817/
html downloaded with Free Download Manager: [173-36817.zip](https://github.com/dazedcat19/FMD2/files/5742396/173-36817.zip)

**Comment by Slasar41** [comment]
It's because even though the file extensions is jpg, the server send the info as webp. (maybe the real image is in webp?)
![image](https://user-images.githubusercontent.com/28888646/103143305-ff82a680-4745-11eb-8b88-9556e67d9500.png)
You can convert it in FMD, Options -> Save to -> Image Conversion.

**Comment by GDXN** [comment]
That is weird as with Free Download Manager and also with Wget the images are downloaded as jpg, but it's also true that is possible that the real image is in webp as I tested another chapter from another manga and the download is in jpg. For me in reality is a non issue but its something that is puzzling me.

This is one of those issues that needs to be put in a faq or the wiki because it can be confusing.

**Comment by Inareous** [comment]
From the magic number on the downloaded file, the file is indeed webp.

**Comment by Slasar41** [comment]
So it's not FMD issue.
