### ISSUE TITLE
[website module request] Sleeping Knights Scanslation

### ISSUE THREAD

**Issue by JokoeSukri** [dazedcat19/FMD2#246]
Website Information

    **Name:** Sleeping Knights Scanslation a.k.a SK Scans
    **Root URL:** https://skscans.com/home
    **Directory list URL:** https://skscans.com/comics

    **Example manga info URL:** https://skscans.com/comics/143236-a-returners-magic-should-be-special
    **Example chapter URL:** https://skscans.com/comics/143236-a-returners-magic-should-be-special/1/128

**Languages :** English

Website relationship
Carbon Copy of Leviathan Scans The structural website exactly same, 
**https://github.com/dazedcat19/FMD2/blob/master/lua/modules/LeviatanScans.lua**

They Usually picked up manhua that dropped up by Leviathan Scans

**Comment by Slasar41** [comment]
Already supported https://github.com/dazedcat19/FMD2/commit/210d08f965ca5ab7674ca6b765db990e2d1fcae3

**Comment by JokoeSukri** [comment]
Oh sorry, I thought it not implemented yet, 

thanks
