### ISSUE TITLE
[MangaDex] Unable to download certain series...

### ISSUE THREAD

**Issue by shimizurei** [dazedcat19/FMD2#247]
**Prerequisite**
- [x] I'm using the latest version: v.2.0.30.0
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Win10x64

**Describe the bug**
Trying to download [The Duchess With an Empty Soul](https://mangadex.org/title/43292) from MD is proving to be quite difficult. I can access the chapters on the site fine, but every dl attempt fails. I tried on the previous FMD and FMD2, to no avail. What is wrong?

**Log**
`18:36:16:311 TTaskThread, download failed. "The Duchess With an Empty Soul" "Ch. 0050" "/chapter/1048300"` x 10+ other chapters

**Comment by Slasar41** [comment]
Try logged in your MangaDex account in FMD.

**Comment by shimizurei** [comment]
1) How would I get around the fact that I use 2FA?

2) I'm able to download other MD series without my account. Why is that?

**Comment by Slasar41** [comment]
1. Looks like you need to use cookies workaround.
2. https://github.com/fmd-project-team/FMD/issues/526#issuecomment-539684236

**Comment by shimizurei** [comment]
I didn't know about that issue.

I had actually just finished adding the cookies and was gonna close this issue when I saw your comment haha

Thanks :)
