### ISSUE TITLE
[feature request] Change link in changelog to current repo's, not previous repo.

### ISSUE THREAD

**Issue by shimizurei** [dazedcat19/FMD2#248]
Changelog still lists home for project as 

```
Free Manga Downloader
https://github.com/fmd-project-team/FMD
```

Needs to be updated.

**Comment by l-l-l-l-l-l** [comment]
Seems lke they only changed it in the about.

**Comment by Slasar41** [comment]
Done. https://github.com/dazedcat19/FMD2/commit/d1853e8968f4dff348699b2864c703a3e5cad592#diff-b40cd67182487ef24807d9c9268329d35fbd96aa2b0a9cae69e2e0d746b1c666L2
