### ISSUE TITLE
[website module request] Madokami

### ISSUE THREAD

**Issue by Trollam** [dazedcat19/FMD2#25]
**Website Information**
* **Name:** Madokami
* **Root URL:** https://manga.madokami.al/
* **Directory list URL:**
  - Manga : https://manga.madokami.al/Manga
  - Novels : https://manga.madokami.al/Novels

* **Example manga info URL:** https://manga.madokami.al/Manga/M/MA/MASH/MASHLE
* **Example chapter URL:**
  - Reader : https://manga.madokami.al/reader/%252FManga%252FM%252FMA%252FMASH%252FMASHLE%252FMashle%2520-%2520c001-007%2520%2528web%2529%2520%255BViz%255D.zip?index=0
  - Zipfile : https://manga.madokami.al/Manga/M/MA/MASH/MASHLE/Mashle%20-%20c001-007%20%28web%29%20%5BViz%5D.zip

**Additional context**
The website require the user to be logged in.

**Comment by dazedcat19** [comment]
I need an account.
The mangalist is the real issue. There's no simple way to populate it.

**Comment by dazedcat19** [comment]
Registration is closed.
I will close it for now. I will reopen it if someone can give me an account.

**Comment by alzamer2** [comment]
hi, @dazedcat19 
i plan to write lue file to add madakami to FMD2
as i have account and know some coding
can you tell me what you need and what names of function that you need them to work with fmd and type of return value the program need
