### ISSUE TITLE
[website module, request]

### ISSUE THREAD

**Issue by wow2134** [dazedcat19/FMD2#250]
**Prerequisite**
- [Y] I'm using the latest version.

- [Y] All website modules are up to date.

- [Y] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
- mangasusu website has changed.
- request module for komiktap

**Additional context**
- mangasusu.pw change to m.mangasusu.co
- request module for komiktap.in
thank you

**Comment by Slasar41** [comment]
Komiktap already supported https://github.com/dazedcat19/FMD2/commit/bda8780d4fd6f679ddfc8b9e76bcddb46482ab74

**Comment by wow2134** [comment]
I have tried using turboVPN to get into komik tap but as seen this doesn't work
![Capture](https://github.com/dazedcat19/FMD2/assets/35753907/c42e53d3-fbaf-4b07-887b-8a998e72ede8)
