### ISSUE TITLE
[bug] MangaDex language preferences

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [dazedcat19/FMD2#254]
**Prerequisite**
- [x ] I'm using the latest version.
- [x ] All website modules are up to date.

- [ x] This is not temporary server issue.

**System information**
W10 x64

**Describe the bug**
I just want to know if I'm the only one whose Mangadex preference suddenly switched to Filipino just because.

**To Reproduce**
No idea: I just opened the software, noticed that suddenly some (most) of my favourites started returning "0" chapters, went around checking and found that the preference was now "Filipino".

**Expected behavior**
I expected it to have remained exactly as I had left it, "English".

**Screenshots**

**Additional context**

**Comment by Slasar41** [comment]
Does this still happen?
