### ISSUE TITLE
[bug-website module] LoveHug : 'Download manga list from server' shows 404 error even the site is up

### ISSUE THREAD

**Issue by masaton6** [dazedcat19/FMD2#255]
**Prerequisite**
- [*] I'm using the latest version.
- [*] All website modules are up to date.
- [*] This is not temporary server issue.

**System information**
Windows 10 64bit

**Describe the bug**
For LoveHug, 'Download manga list from server' is not functioning and shows 404 error even LoveHug site is up. 

**Additional context**
Probably because of this issue, even added LoveHug manga into favorites, it is gone from favorites at next FMD2 run.

**Comment by Slasar41** [comment]
>Probably because of this issue, even added LoveHug manga into favorites, it is gone from favorites at next FMD2 run.

Works fine on my end.

>For LoveHug, 'Download manga list from server' is not functioning and shows 404 error even LoveHug site is up.

It's because there's no database in the server yet.
And the update list function is broken and need to be fixed.

**Comment by masaton6** [comment]
Hi Slasar41,

Thank you for your comments.
I re-installed FMD2 and the favorites issue are gone for new installation.

**Comment by masaton6** [comment]
Hi Slasar41,

Confirmed the issue is fixed now. Thank you very much.
