### ISSUE TITLE
[bug] can't check, view, or download converted favourites

### ISSUE THREAD

**Issue by ekoaw** [dazedcat19/FMD2#258]
**Prerequisite**
- [ X ] I'm using the latest version.
- [ X ] All website modules are up to date.
- [ X ] This is not temporary server issue.

**System information**
Windows 10 Education
Version 20H2
OS Build 19042.685

**Describe the bug**
Converted favourites and downloads from FMD1 (fmd-project-team fork) can't do any actions (Check for a new chapter, View manga info, Download all, Resume)

**To Reproduce**
1. Run `converter.exe` on FMD1 root folder
2. Copy `converted\userdata` folder to FMD2 root folder
3. Run FMD2
4. Try to Check for a new chapter or view manga info from favourites, nothing happened

**Expected behavior**
Should do the mentioned actions

**Screenshots**
My guess is because website name in `id` and `moduleid` changed from string to hashed
![Screenshot 2021-01-08 214251](https://user-images.githubusercontent.com/1841735/104029014-01e00880-51fc-11eb-8ed5-2d55c90e753b.png)

**Comment by Slasar41** [comment]
I'm trying to convert again just now and it's works just fine.
- Make sure you download it from [here](https://github.com/dazedcat19/FMD2/releases/tag/2.0.21.0).
- Make sure to download `modules.txt` too.

**Comment by ekoaw** [comment]
Ok, thanks, seems like I'm missing the `modules.txt` file.
