### ISSUE TITLE
[bug] komikcast "cannot get manga info "

### ISSUE THREAD

**Issue by Renvix** [dazedcat19/FMD2#259]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
windows 10 64bit

**Describe the bug**
manga in Komikcast cannot be opened and a window appears with the words "cannot get manga info. please check your internet connection and try it again.". although my internet is smooth and the Komikcast website can be opened from the Firefox browser without any problems.

**To Reproduce**
1. Go to tab manga info
2. Click on manga sites komikcast
3. Scroll down to manga death march kara hajimaru and select

**Screenshots**
![fmd](https://user-images.githubusercontent.com/29302760/104057099-2059fa00-5224-11eb-987d-dc9a1adc0597.jpg)

**Comment by Slasar41** [comment]
You need to do cookies workaround.

**Comment by Renvix** [comment]
is this https://github.com/dazedcat19/FMD2/issues/120#issue-709503767 how do I do it?

**Comment by Slasar41** [comment]
I haven't tried using that.
I always use [this way](https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964) for any cloudflare issue.

**Comment by Renvix** [comment]
> 
> 
> I haven't tried using that.
> I always use [this way](https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964) for any cloudflare issue.

not working

**Comment by Slasar41** [comment]
Looks like komikcast disabled the cloudflare protection and FMD can access the website normally again.
