### ISSUE TITLE
[bug] sekaikomik

### ISSUE THREAD

**Issue by fajri411** [dazedcat19/FMD2#262]
Prerequisite

 I'm using the latest version.
 All website modules are up to date.
 This is not temporary server issue.
System information
windows 10 64bit

Describe the bug
manga in Komikcast cannot be opened and a window appears with the words "cannot get manga info. please check your internet connection and try it again.". although my internet is smooth and the Komikcast website can be opened from the Firefox browser without any problems.

To Reproduce

Go to tab manga info
Click on manga sites komikcast
Scroll down to manga death march kara hajimaru and select
See error
![image](https://user-images.githubusercontent.com/26165132/104089474-5c37a280-52aa-11eb-95c8-3b2489579893.png)

**Comment by Inareous** [comment]
A little bit confusing, the title and provided image does say sekaikomik but your description refer to komikcast.

As for sekaikomik, the website owner set those particular mangas to private so fmd can't access the manga info page.

![image](https://user-images.githubusercontent.com/18087264/104092404-4c25c000-52b6-11eb-9cb0-2d7e231e3717.png)

**Comment by Renvix** [comment]
> 
> 
> A little bit confusing, the title and provided image does say sekaikomik but your description refer to komikcast.
> 
> As for sekaikomik, the website owner set those particular mangas to private so fmd can't access the manga info page.
> 
> ![image](https://user-images.githubusercontent.com/18087264/104092404-4c25c000-52b6-11eb-9cb0-2d7e231e3717.png)

can you explain what that means?
