### ISSUE TITLE
[website module request] Toonkor

### ISSUE THREAD

**Issue by enjoe842** [dazedcat19/FMD2#267]
**Website Information**
* **Name:** Toonkor / 툰코
* **Root URL:** https://tkor.ink/
* **Directory list URL:** -

* **Example manga info URL:** https://tkor.ink/%EC%9A%B0%EB%A6%AC%EB%8F%99%EB%84%A4-%EB%B9%84%EB%87%A8%EA%B8%B0%EA%B3%BC
* **Example chapter URL:** https://tkor.ink/%EC%9A%B0%EB%A6%AC%EB%8F%99%EB%84%A4_%EB%B9%84%EB%87%A8%EA%B8%B0%EA%B3%BC_1%ED%99%94.html

**Languages**
List of languages supported by the website
Korean

**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...")

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Slasar41** [comment]
Toonkor already supported and now should be fixed. https://github.com/dazedcat19/FMD2/commit/db32da581c4a136b862f9da51ff7263b0f0264f7
