### ISSUE TITLE
[feature request] Add the "Save downloaded chapters as" option in the "Save to" tab

### ISSUE THREAD

**Issue by Inpacchi** [dazedcat19/FMD2#269]
**Is your feature request related to a problem? Please describe.**
Most of the settings can be adjusted in the settings.json, but this one cannot and I'm not sure where it's saved.

**Describe the solution you'd like**
I would like to either know where it can be modified by an external script or have it added as a parameter in the settings.json

**Comment by Slasar41** [comment]
It's `"Compress"` in the settings.json.
If you select different method, the value will changed.
None = 0
ZIP = 1
CBZ = 2
PDF = 3
EPUB = 4

**Comment by Inpacchi** [comment]
Aha, no wonder I couldn't find it by looking. This is great information. Thank you so much!

**Comment by Slasar41** [comment]
I use something like [this](https://www.diffchecker.com/) and paste each changes to see what has been changed.

**Comment by Inpacchi** [comment]
Makes sense; I don't know why I didn't think of that lol. At least I know now that the settings don't necessarily correlate the way I think it does.
