### ISSUE TITLE
[bug-website module] NightComic

### ISSUE THREAD

**Issue by Trollam** [dazedcat19/FMD2#27]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 64-bit

**Describe the bug**
The manga list is not loaded, can't update manga list nor download list from server.
If I paste a manga url, it's recognised and the info are loaded but not the chapters list.

**Log**
[view-source_chapters_list.txt](https://github.com/dazedcat19/FMD2/files/4776483/view-source_chapters_list.txt)
[view-source_chapter-432_.txt](https://github.com/dazedcat19/FMD2/files/4776482/view-source_chapter-432_.txt)

**Comment by Slasar41** [comment]
I'll update the manga list database to server later.
