### ISSUE TITLE
[feature request] Generating Different Folders for Manga Title Duplicates

### ISSUE THREAD

**Issue by Res223** [dazedcat19/FMD2#270]
Hi,

Using FMD2 to archive mangas from a site and I have two mangas that share a name from but have different number of content within them. FMD2 currently generates 1 folder for both titles and populated 1 folder instead of 2.

I would like to see under "save to" a way to detect duplicates and automatically rename folders in sequence if detected as a duplicate.

%MANGA% %DUPLICATE%

so folders will appear as
<Manga> 01
<Manga> 02

if both mangas share the same name.

____

An alternative would be that when downloads detect a duplicate after the first manga, it would automatically fail so I can go back and sort it out myself.

I apologize if my lingo or terminology isn't correct or exact. But I hope this feature is possible. Thank you so much for your work and I hope you consider this request or let me know if this is already possible.

Thanks,
Res223

**Comment by Slasar41** [comment]
Is it from the same website or different website?

**Comment by Res223** [comment]
> Is it from the same website or different website?

Same website

**Comment by Slasar41** [comment]
Could you provide the urls?

**Comment by Res223** [comment]
> Could you provide the urls?

Yes, just a heads up these are R18 links.

https://hentainexus.com/view/2024
https://hentainexus.com/view/6321

**Comment by Slasar41** [comment]
I've added the magazine name to the title so it'll be different.
