### ISSUE TITLE
[bug] https://www.webtoon.xyz cant check update new chapters. shows 0

### ISSUE THREAD

**Issue by sadeghp88** [dazedcat19/FMD2#276]
**Prerequisite**
- [y ] I'm using the latest version.
- [ y] All website modules are up to date.

- [n ] This is not temporary server issue.

**System information**
win 10 enterprise 64X

**Describe the bug**
every time i check my favorites manhwa for new chapters from https://www.webtoon.xyz  it shows the current chapter column "0". but i can download from this site and i need to download it manually not by check chapter updates.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/28827241/104811042-14ff6380-580e-11eb-8ec7-518500616ae5.png)

**Additional context**

**Comment by Slasar41** [comment]
What's the number of `Max number of favorite check at the same time` in your settings?

**Comment by sadeghp88** [comment]
4. never had any problem with it before by any site.

**Comment by Slasar41** [comment]
I tried adding a bunch of random titles to favorites, set the max number to 4, and then run check for new chapters. There's no issue on my end.
