### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by YadrianX** [dazedcat19/FMD2#278]
Website request

for the integration of a new website and correction

integration:  https://lectortmo.com/
correction:  https://es.ninemanga.com/

with respect to  https://es.ninemanga.com/   does not update the manga list from the server and only downloads the first page of the manga
![001](https://user-images.githubusercontent.com/77561704/104831362-90890100-585e-11eb-835e-0be7dc756b28.jpg)

**Comment by Slasar41** [comment]
I don't understand.
Is this a feature request, a website request, or a bug website module?

**Comment by YadrianX** [comment]
una solicitud de sitio web y un módulo de sitio web con errores

website request:  https://lectortmo.com/
buggy website module: https://es.ninemanga.com/

I hope your great help thanks

**Comment by Slasar41** [comment]
NineMangaES works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/104964843-de913680-5a0f-11eb-81b9-bb911e4ee549.png)

https://lectortmo.com [TuMangaOnline] already supported.

**Comment by YadrianX** [comment]
Thanks for your help and time, I appreciate your work. There is a video where you can see how the fmd should be installed correctly.

**Comment by Slasar41** [comment]
What video?
And do you have another issue?
