### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Josexv1** [dazedcat19/FMD2#284]
I'm trying to move from 1.3.3.0 to the latest and using the Converter.exe and modules text file.

The issue is that the converter complains about having too many attached databases

```
PS D:\Software\Manga-downloader> .\converter.exe
error: TSQLite3Connection : too many attached databases - max 0
An unhandled exception occurred at $0045C2A6:
EDatabaseError: cannot rollback - no transaction is active
  $0045C2A6
  $00436E93
  $00436AAA
  $0043C4B8
```

FMD 1 is 32 bits   
converter is 32 bits   
FMD2 is 64 bits

The converter generates my fav list but not the downloaded list which i really need since i have a huge backlog.

I will probably do it manually modifying the sqlite database, but seems like nobody else had this issue.

**Comment by Slasar41** [comment]
~Try using converter 64 bit.~
~The converter doesn't care if your FMD1 is 32 bit or 64 bit.~

EDIT:
Looks like converter 32 bit have a bug.
- You have to download FMD1 64 bit
- Copy your `config`, `data`, and `works` folder from FMD1 32 bit to FMD1 64 bit folder.
- Copy converter 64 bit and modules.exe to FMD1 64 bit folder, then run it.

EDIT2:
I'm not sure about converter 32 bit having a bug.
After repeatedly running it, I got `downloadedchapters.db`, `downloads.db`, `favorites.db`, and `settings.json` in `converted\userdata` folder.

**Comment by Josexv1** [comment]
Thanks, that really helped, I manually imported the old sqlite db to the new, but your method works.

We can close the issue.
