### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by yeahal** [dazedcat19/FMD2#286]
I got the latest version FMD and FMD 1 , I tryed both coverters x32 ,x64 using modules in both 

![Error](https://user-images.githubusercontent.com/77836968/105485470-3dbfa700-5cad-11eb-8262-db7444638ec4.png)

Can you tell me what to do ?

**Comment by Slasar41** [comment]
What version is your FMD1?

**Comment by yeahal** [comment]
FMD1 : 0.9.158.0 64 bits 
![c6mQNF27kn](https://user-images.githubusercontent.com/77836968/105544066-dcbec000-5cfa-11eb-8f2f-079acee28611.png)

**Comment by Slasar41** [comment]
That's so old.
First you need to update to the latest FMD1 here: https://github.com/fmd-project-team/FMD/releases/tag/1.3.3.0
Then you run the converter again.

**Comment by yeahal** [comment]
Thakns for the help,  It worked perfecly fine 
I admire your work and fast response 
Have a great year man ^^
