### ISSUE TITLE
can't use download data fom old fmd 

### ISSUE THREAD

**Issue by rakhmat12** [dazedcat19/FMD2#287]
Try to move the work file to userdata but it's error

**Comment by Slasar41** [comment]
You have to use a converter, get it [here](https://github.com/dazedcat19/FMD2/releases/tag/2.0.21.0).

**Comment by rakhmat12** [comment]
It makes the fmd error

Pada tanggal Sab, 23 Jan 2021 01.36, Slasar41 <notifications@github.com>
menulis:

**Comment by Slasar41** [comment]
What error?

**Comment by rakhmat12** [comment]
The download check box doesn't appear and the the download data not appear
as well but the manga list did appear.

Pada tanggal Min, 24 Jan 2021 00.29, Slasar41 <notifications@github.com>
menulis:

**Comment by rakhmat12** [comment]
And the error message comes

Pada tanggal Min, 24 Jan 2021 09.12, Yusuf Rakhmat Maulana <
yusufrakhmat12@gmail.com> menulis:

**Comment by Slasar41** [comment]
What version is your FMD1?
