### ISSUE TITLE
[bug-website module] KissManga

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#29]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 2004 64-bit

**Describe the bug**
My settings for `Number of downloaded files per task...` is set to 3.
When I `Check for new chapter` first time after IP Address change, the first line will be hold waiting for cloudflare challenge to finish, but the other two line will go ahead and causing the manga to have 0 chapter.
I have to cancel after the first line working and then check again.

**Additional context**
![2020-06-18_01-26-07](https://user-images.githubusercontent.com/28888646/84937170-8efb2d00-b105-11ea-876b-b36a7b0ea4e8.gif)

**Comment by user1705** [comment]
also new chapter cannot be downloaded as they put captcha challenge for each chapter. eg: [here](https://kissmanga.com/Special/AreYouHuman2?reUrl=%2fManga%2fHenjo-Hen-na-Joshi-Kousei-Amaguri-Chiko%2fVol--014-Ch-088%3fid%3d643332)

![captcha](https://user-images.githubusercontent.com/52578858/84995571-bf32e200-b17e-11ea-9cdf-bbf0ac988dcd.png)

![failed](https://user-images.githubusercontent.com/52578858/84995922-2c467780-b17f-11ea-8714-5bdf0755ebee.png)

**Comment by Slasar41** [comment]
I have that challenge too when open the website from browser but FMD can still download it just fine.
Try stop and resuming again and again, if it's still fail then try restart your router to get a new IP.

**Comment by user1705** [comment]
i tried restarting the router and it worked. but for some reason sometimes the download does failed occasionally. hmmm

**Comment by Slasar41** [comment]
Yeah recently KissManga become troublesome and most of my manga are from them…

**Comment by dazedcat19** [comment]
the websitebypass module can only be accessed by one request per website module. If the other thread bypassing the websitebypass that mean that request receive something that doesn't regarded as a cloudflare challenge in `checkantibot.lua`. `checkantibot.lua` itself is single-threaded. other threads has to use synchronize.
You can try to reproduce the issue and log all the responses in `checkantibot.lua`. Then we can add it as a rule in 'checkantibot.lua'
add something like this in `checkantibot.lua`
```lua
print('CheckAntibot for ' .. HTTP.LastURL ..
     '\r\nResultCode: ' .. tostring(HTTP.ResultCode) ..
     '\r\nResultString: ' .. HTTP.ResultString ..
     '\r\nResponse Headers:\r\n' .. HTTP.Headers.Text
     '\r\nResponse Body:\r\n' .. HTTP.Document.ToString());
```

**Comment by Slasar41** [comment]
Sorry, at which line should I put it?
I keep getting errors.

**Comment by Slasar41** [comment]
KissManga has a new issue.
The challenge that need to be solved before accessing the chapters are now affecting FMD, can't download anymore.
Fortunately, using cookies workaround after finishing the challenge, download is working again.
Could this issue be fixed?

Edit:
I'm trying to match the default cookies in FMD to browser so I only have to solve the challenge in browser without doing cookies workaround but it's doesn't working.
![image](https://user-images.githubusercontent.com/28888646/85539154-bf7c2300-b63f-11ea-9e07-5d358de17c73.png)

**Comment by molitar** [comment]
Same problem here.

**Comment by HiP1** [comment]
seems Kissmanga changed something in their decrypt keys. maybe we have to renew them, but I can't find the boxes in the options anymore, is it done automatically in the lua now ?

log : 
22:00:53:397 ERROR: KissManga: failed to get a key to decrypt
iv          : a5e8e2e9c2721be0a84ad660c472c1f3
chko1       : mshsdf832nsdbash20asdm
chko2       : 
chko2_plus  : 
test_string : GxOaB89Kptwl/ndCxdXvKX2aiMIEURJ/KNf4gKHzcd4QA6SfgbWdLuAiMvXMNc6rVGKFQEIgxrYgrHo5zzBdtWGuy/Gpqi02QGdGz3+7rrOVIbTJqRvTAkdsT4dXolpBlM4xfOEtLBUGUUtTlIFiBJ7pMRc7fEdd2IuhlAU2fTgCDJXzdlybkmHhREL8ACmNZWHFrdT2O9p+aphATh6RcWFrKCISQ5iaernWpOJc73Q20ZjRQAtB18Plkusfx7PrGF22E2jNo8h+FrGF8VWcqiqLMtMn8OCvb0CVODKYA0o=
					
22:00:54:724 WARNING: TTaskThread, checkforfinish failed=1/1 [KissManga] "Ao no Exorcist" > "/Manga/Ao-no-Exorcist/Chapter-122?id=651248"
22:00:54:725 WARNING: TTaskThread, download failed. "Ao no Exorcist" "Ao no Exorcist Chapter 122" "/Manga/Ao-no-Exorcist/Chapter-122?id=651248"

**Comment by Slasar41** [comment]
I get that too and fixed it by rebooting the router so I have new IP Address. Then do captcha chapter challenge and copy the cookies.

**Comment by HiP1** [comment]
i did the captcha challenge, and copied the cookie, as it is a requirement now.
but i can't change my IP, unfortunately.

**Comment by Slasar41** [comment]
You can use a VPN or wait until cloudflare's session to expires, maybe a day or half.

**Comment by Inareous** [comment]
@HiP1 right now if you want to manually change the chko you could inject it directly on the lua [here](https://github.com/dazedcat19/FMD2/blob/6327a70c780ac83a361e73fb9b730fbcf660e6d9/lua/modules/KissManga.lua#L100). To piggy back on this, would be nice to have a setting to override chko value on FMD2, i think it got removed.

**Comment by HiP1** [comment]
@Inareous thanks, but the current module tries to find the keys automatically, it's a better solution when it works.

the matching string might have changed though.
from the webpage source : 
<script type="text/javascript">
  var _0x2c7e = ["\x6E\x61\x73\x64\x62\x61\x73\x64\x36\x31\x32\x62\x61\x73\x64"]; chko = chko + _0x2c7e[0]; key = CryptoJS.SHA256(chko)
</script>

**Comment by dazedcat19** [comment]
related to #50 unable to override the cookies

**Comment by HiP1** [comment]
not sure it is related. some of the encryption keys cannot be retrieved.
maybe the regex from the lua does not match anymore
from log :
00:25:35:137 KissManga: failed to get a key to decrypt
iv          : a5e8e2e9c2721be0a84ad660c472c1f3
chko1       : mshsdf832nsdbash20asdm
chko2       : 
chko2_plus  : 
test_string : GxOaB89Kptwl/ndCxdXvKZVdMCkSOht1kdXrhKVsRaM/Ylc6eMM5NVJ4XJF5Yc93g16ImX2E6NRTOdd095FQLoyeDVoUmaPg1cWJ0kLZUG53e7w1afBlaVN6wPYFa4QHacLVBblQcxpyTfwRhYxKFAKqSHwdP3Gx6gUlMARaXNB0XTTivUVWBtc1jsSUlyuxt3+3E6vkUiwm1E/fo42MphicJbGfrl32SHPdFigxf4DZ5q0BEI/Ecs7neEGyg40VyYrIHh03RwyIZ7ECXVzrQalR52s9puA+b4jazh/K52k=

**Comment by dazedcat19** [comment]
Add this line to kissmanga.lua after the error message. then post the generated file.
```lua
HTTP.Document.SaveToFile('kissmanga_newkey.html')
```

**Comment by HiP1** [comment]
Here is the file

[kissmanga_newkey.zip](https://github.com/dazedcat19/FMD2/files/4891335/kissmanga_newkey.zip)

**Comment by dazedcat19** [comment]
Oh, I forgot kissmanga module actually load two file. try this again. and post the 2 files. kissmanga_pg.html and kissmanga_lo.js. 

remove .txt
[KissManga.lua.txt](https://github.com/dazedcat19/FMD2/files/4894117/KissManga.lua.txt)

**Comment by HiP1** [comment]
here are the generated files

[kissmangafiles.zip](https://github.com/dazedcat19/FMD2/files/4898202/kissmangafiles.zip)
