### ISSUE TITLE
[bug-website module] Cannot download from https://myreadingmanga.info

### ISSUE THREAD

**Issue by Reyeselda95** [dazedcat19/FMD2#290]
**Prerequisite**
- [ X ] I'm using the latest version.
- [ X ] All website modules are up to date.

- [ X ] This is not temporary server issue.

**System information**
Windows 10
1TB HDD
250 SSD
16GB RAM
Intel core i7 8th gen

**Describe the bug**
From previous versions of FMD, at least since the last year and half or so, i've been posting an error because of unavaliability to doanload from this page correctly.
I found a workaround for the bug, that is because of the cookies of the site and, actually, putting advanced options with the cloudflare cookie it allows to download propperly, but having to F12, load page, search for the cookie tag and putting it on FMD every time is quite annoying.
Do you know if it's possilbe to fix the error in any way so we don't have to workaround everything each time somebody wants to download anything from this page?
Thank you beforehand.

**Comment by Slasar41** [comment]
Unfortunatelly the built-in cloudflare solution is still broken.
There's [this](https://github.com/dazedcat19/FMD2/issues/120) solution but looks like it broken too.
So you must do manual cloudflare workaround for now.

**Comment by Reyeselda95** [comment]
Ok, thanks for the quick response. At least I do know that you know about the issue.
I'll wait until it hopefully gets fixed in some future version ^^
Regards.

**Comment by Slasar41** [comment]
I'll close this issue for now as the module itself have no problem.
