### ISSUE TITLE
[bug] Certain chapter in MangaSee unable to download.

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD2#291]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**Describe the bug**
I try to download chapter 56 of goblin slayer from MangaSee but it keep fail. Open normally using browser works fine. Other manga also download fine.

Link: https://mangasee123.com/manga/Goblin-Slayer

**Screenshots**
![Capture](https://user-images.githubusercontent.com/40983245/105752384-2ff67400-5f82-11eb-873e-4f667f4344a1.PNG)

**Additional context**
I try using FMD 1 and it able to download the chapter properly.

**Comment by Slasar41** [comment]
Please update your website module, it should be fixed. https://github.com/dazedcat19/FMD2/commit/5333462cbb6cfe811a705b37985be14047a361de
