### ISSUE TITLE
[bug-website module] https://reaperscans.com/ manga info

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD2#296]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7
3 TB HDD
120 GB SSD
16 GB RAM
Intel core i7 1st gen

**Describe the bug**
When I double click a manga in reaperscans it becomes n/a and no manga chapter appears.
Screenshot:
![reaper](https://user-images.githubusercontent.com/24958560/106353354-21a6b000-6314-11eb-8d39-61a8c11538a3.PNG)

The website is fine too. 
Screenshot:
![reaper 2](https://user-images.githubusercontent.com/24958560/106353397-806c2980-6314-11eb-805c-ec91e9fc896b.PNG)

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/106364662-52620600-6363-11eb-81bc-fae224e45924.png)

**Comment by Souravi785** [comment]
It's working now. 

Again the same problem.

![fmd](https://user-images.githubusercontent.com/24958560/106393029-cb726380-641e-11eb-961e-fa5b5fbfd96e.PNG)

**Comment by Slasar41** [comment]
Oh, the website activated cloudflare protection.
You've to do cookies workaround for now. https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964

**Comment by Souravi785** [comment]
@Slasar41 can you reopen this issue? Cloudfare turnaround is not working for reaperscans.

**Comment by Slasar41** [comment]
There's already open issue: https://github.com/dazedcat19/FMD2/issues/449
