### ISSUE TITLE
[bug-website module] Toonily Broken

### ISSUE THREAD

**Issue by brazenvoid** [dazedcat19/FMD2#297]
**System information**
Windows 10 20H2

**Describe the bug**
FMD can't parse toonily for anything completely. New chapters are not detected, new series do not return anything while old series return information (after a long time) but no chapters. All downloads fail.

**Comment by Slasar41** [comment]
Please provide a series link that has problem.
I've tested with random series and all works fine.

**Comment by brazenvoid** [comment]
Strange. I also tried randomly but all of them didn't work. I'll get you some links.

**Comment by brazenvoid** [comment]
I tried just now, each of them didn't work. 

Note the following are are random clicks from the parsed list gotten for toonily, they may have NSFW content. 

**Only information shows, no chapters, title in the list changes to N/A (0) after requesting info:**

- https://toonily.com/webtoon/head-over-heels/
- https://toonily.com/webtoon/crime-punishment/
- https://toonily.com/webtoon/desperate-measures/
- https://toonily.com/webtoon/hahris-lumpy-star/

**Favorites**

![Screenshot 2021-01-30 233047](https://user-images.githubusercontent.com/8722533/106364748-35253b80-6353-11eb-83a9-df590429a538.png)

**Comment by brazenvoid** [comment]
I have a VPN, I tried with Romania and Sweden, I don't think its blocked in either of these location.

**Comment by Slasar41** [comment]
Ah, sorry I missread the website name.
Because the website implemented cloudflare protection and the built-in cloudflare solution in FMD is broken, you've to do cookies workaround.
Do you know how to do it?

**Comment by brazenvoid** [comment]
But it was working completely fine yesterday!

Fine, please give me a guide link, I am sure I will be able to do it.

**Comment by Slasar41** [comment]
Well looks like they activated the protection a few hours ago.
Here's the guide: https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964

Maybe I should write the workaround in wiki like FMD1: https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-PsychoPlay

**Comment by brazenvoid** [comment]
@Slasar41 I can also make that for you, if you want.

**Comment by Slasar41** [comment]
Maybe not.
There will be a new different FMD anyway that hopefully this issue will not happened.

**Comment by brazenvoid** [comment]
That's something new, where can I track progress for it?

**Comment by Slasar41** [comment]
There's a discord invite link in FMD1 repository

**Comment by brazenvoid** [comment]
Thanks!
