### ISSUE TITLE
cant download from toonily  there is no chapters to download so favorites cant check either 

### ISSUE THREAD

**Issue by darklife0000** [dazedcat19/FMD2#298]
![144](https://user-images.githubusercontent.com/77100624/106366963-dd350780-6347-11eb-9c3b-95899e4cbc6e.png)
![145](https://user-images.githubusercontent.com/77100624/106367003-31d88280-6348-11eb-8ddd-24138f9c3557.png)

**Comment by Slasar41** [comment]
See: https://github.com/dazedcat19/FMD2/issues/297
