### ISSUE TITLE
can't download from https://toonily.com and https://skymanga.co

### ISSUE THREAD

**Issue by sadeghp88** [dazedcat19/FMD2#299]
hello
recently i can't download from https://toonily.com and https://skymanga.co , please fix it
thanks a lot.

**Comment by Slasar41** [comment]
You've to do cookies workaround for now. https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964

**Comment by sadeghp88** [comment]
this one https://skymanga.co got fixed as you mentioned but the other one still doesn't work

**Comment by Slasar41** [comment]
Yeah, the website has cloudflare protection activated and the built-in cloudflare bypass in FMD is broken so you've to do cookies workaround.
