### ISSUE TITLE
Add tags to website categories

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#3]
Some websites have mixed content, example: It's in Indonesian language, have JP-H and manhwa content.
Now I confused which category should I put it?
And user should be able to search it by any content in the websites.
I suggested something like this last time : https://github.com/fmd-project-team/FMD/issues/570
Or maybe you've better ideas?

**Comment by dazedcat19** [comment]
The categories is just to group similar website, for quick look. it doesn't mean anything other than that. A website can have multiple languages and multiple content types.
If you want to make tags. then there's will be no categories.
you can try to implement that. to add separate language and tags to tmodulecontainer. the website list would have no group, just plain full list. the search would have to be separated too, search for language and/or tags.
IMO, that would be overly complicated for end user. I will not implement it. if you can make it more intuitive maybe I will consider to merge it to main branch.

**Comment by Slasar41** [comment]
I don't know how to implement it, I just want to know if FMD can do something like that.
If it'll complicated the users then I'll skip it.

How about categories it by the languange?
Example:
- English
- English-Scanlations
- English-Hentai
- English-Webcomics

But I don't know if it's a good idea to make too many categories.

**Comment by dazedcat19** [comment]
It easy to implement it. just add more property in tmodulecontainer and adjust the ui. but it is indeed overly complicated for end user. select/filter language, then tags.
You can put any value in lua module's category. FMD will pick it up and group them and sort them automatically at startup.

**Comment by Slasar41** [comment]
Alright, I'll leave the tags function for now.

I can build FMD just fine when you tell me about FLRE and PUCU last time, but now I can't build it anymore.
![image](https://user-images.githubusercontent.com/28888646/82703311-dd034900-9c9d-11ea-84bf-9fb71b532871.png)
Maybe I missing something since you've been change many things?

Also, how to generate the module ID for supporting new websites?

**Comment by dazedcat19** [comment]
the IDs can be anything unique. But to generalize it we should use UUID/GUID. lowercase, without hypens `-` and braces `{`, `}`. there's supposed to be no duplicate of UUID in the world.

if you use notepad++ download toolbucket plugins. it can generate UUID with some format. lazarus also has this feature. there's countless tool out there that can generate UUID. on windows powershell type `[guid]::NewGuid()`.

don't forget to cleanup the hypens and braces and convert it to lowercase. this is useful to speedup the sorting and searching the modules. when fmd load, it will search the ID for each download/favorite to find the right module.

**Comment by dazedcat19** [comment]
jsonini seems to be only available in fpc 3.2+. Lazarus stable has't been updated it's fpc. It still use 3.0.6 for many years now. you can try to grab that file in fpc trunk. the dependency should be minimal. I can replace that depedency with fpjson but rewriting something that already exist seems to be a waste.

https://svn.freepascal.org/cgi-bin/viewvc.cgi/trunk/packages/fcl-json/src/jsonini.pp?view=co
I just checked it. it only use fpjson and related units that should be available in fpc 3.0x. the jsnonini itself written 2 years ago. it should be usable with fpc 3.0x and lazarus stable. just copy the file in some folder that can be scanned by lazarus. in lazarus folder, components. or on fmd project itself. put it in baseunits or somewhere in included paths.

But I recommend to use fpc and lazarus trunk. compile it directly from svn. or at least use fpc 3.2 with lazarus stable. download and install fpc 3.2 then setup lazarus environment to use that version of fpc. `tools > options > environment`
ftp://ftp.freepascal.org/pub/fpc/snapshot/fixes/i386-win32
ftp://ftp.freepascal.org/pub/fpc/snapshot/fixes/x86_64-win64

**Comment by Slasar41** [comment]
I've download and install fpc 3.2 beta but there's another error when trying to build:
![image](https://user-images.githubusercontent.com/28888646/82838706-36b28000-9ef7-11ea-9d59-0c79bfe25ead.png)
Here's my environment:
![image](https://user-images.githubusercontent.com/28888646/82839150-99584b80-9ef8-11ea-9eda-43238fc3aff2.png)
There's no source folder and make.exe file in 3.2 beta so I leave it like that.

**Comment by dazedcat19** [comment]
get make.exe etc from previous stable binutils. which is 3.0.x https://svn.freepascal.org/svn/fpcbuild/trunk/install/binw32/
db should be installed by default(all) by fpc. if they're compiled correctly.
better use trunk then. directly compile everything from source. simple use svn checkout and batch script, or just install it easy with fpcupdeluxe https://github.com/LongDirtyAnimAlf/fpcupdeluxe there's many branch to choose. just choose trunk. after using fpcupdeluxe. the fpc and lazarus folder should be an svn folder with `.svn` hidden folder. so you can just use svn client to fetch new update and recompile. just install fpc and lazarus as portable with lazarus.cfg (google lazarus secondary installation). install it on non primary disk(D, E, F...). I always do it anyway. I only install primary lazarus for the stable version.

**Comment by Slasar41** [comment]
I've installed lazarus trunk and fpc trunk from fpcupdeluxe but I can't see the OPM option.
![image](https://user-images.githubusercontent.com/28888646/83217468-0ccab900-a196-11ea-8a62-b3ce4d999ec8.png)

**Comment by dazedcat19** [comment]
If you don't compile lazarus with big-ide it will not be installed by default. Just install it via `install/uninstall packages`. bid-ide will install all available packages. but I suggest just install the essentials. like codetools, leak trace, OPM, etc. Just read the details of each package.

**Comment by Slasar41** [comment]
I'm going to close this issue for now.
Thanks for the explanation!
