### ISSUE TITLE
Toonily.com Module Issue wont load the chapter list.

### ISSUE THREAD

**Issue by zillafox** [dazedcat19/FMD2#302]
windows 10. 64 bit
Latest FMD 2.0.30.0

On my FMD, Toonily in my favorite checklist won't load the chapter list. My browser can access the website just fine. I think the issue was from age verification gate.
please kindly see the attached

![from browser](https://user-images.githubusercontent.com/24423458/106446785-41c0a580-64b3-11eb-8a67-bf906d76c2cb.PNG)
![check list fmd](https://user-images.githubusercontent.com/24423458/106446789-438a6900-64b3-11eb-859a-fd156a5e5e60.PNG)

**Comment by Inareous** [comment]
Toonily now uses cloudflare protection which FMD is not equipped to deal with gracefully.

You can try using guides in #120. However cloudflare sometimes check for selenium and the solution may not work (though [playwright](https://github.com/microsoft/playwright) still work fine).

Another solution is to copy-paste cloudflare cookies manually from your browser to the FMD itself.

**Comment by Slasar41** [comment]
See https://github.com/dazedcat19/FMD2/issues/297
