### ISSUE TITLE
[bug-website module] Toonily-detected new Cloudflare challenge

### ISSUE THREAD

**Issue by kuso-ge** [dazedcat19/FMD2#304]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 Home 20H2(19042.685)
16GB 2133 MHz RAM
i5-6300HQ
FMD2 v2.0.30.0

**Describe the bug**
Toonily now has a new cloudflare protection. 

**Additional context**
**Log**
[fmd.log](https://github.com/dazedcat19/FMD2/files/5907544/fmd.log)
[page source.txt](https://github.com/dazedcat19/FMD2/files/5907563/page.source.txt)

**Comment by Slasar41** [comment]
See https://github.com/dazedcat19/FMD2/issues/297

**Comment by kuso-ge** [comment]
Oops I only checked duplicate on Open and not on Closed issues.  
Sorry about that. Thanks
