### ISSUE TITLE
[bug]Mangadex Chapters not showing up on FMD

### ISSUE THREAD

**Issue by frerouche** [dazedcat19/FMD2#306]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
From time to time, recently released chapters will not show on FMD. Sometimes for over 3 hours.
For example, last week, I think it was on the 26th's night, no release would show up on FMD until they were 2 hours and 10 to 15 minutes old on Mangadex.

**Screenshots**

**Comment by frerouche** [comment]
![fmd](https://user-images.githubusercontent.com/36459595/106634067-6701f200-654d-11eb-97d5-a89132dbb40b.png)

**Comment by Slasar41** [comment]
The JSON from the API is not directly being changed after uploading or changing a title/chapter. It is being cached and that cache is what the API is pulling info from. currently only RU chapter 79 is available in the api. They are out of sync as well sometimes.
https://api.mangadex.org/v2/manga/15553/chapters
Using this syntax will give you an insight wether the chapter is available or not through the API.

**Comment by frerouche** [comment]
Thanks for the info.
Bummer since it seems to currently be out of sync by over 4 hour and 30 minutes.
