### ISSUE TITLE
Latest chapter not detected Mangadex [bug]

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD2#307]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**Describe the bug**
Chapter 61 not detected in https://mangadex.org/title/50227

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/40983245/106700656-3b9c0780-6620-11eb-97e5-2478e9db38f7.jpg)

**Comment by Inareous** [comment]
See #306
