### ISSUE TITLE
Mangadex site issue not actually a bug "[bug] Mangadex can't get new chapter list or donwload some chapters [Site change?]"

### ISSUE THREAD

**Issue by GDXN** [dazedcat19/FMD2#318]
**This actually apperas that is a Mangadex site issue, going to close the issue when the site api servers works again correctlly to prevent issue duplicates**
---------------------------------------------------------------------------------------------------------------------------------
Don't know if its one or two bugs as they happened at the same time and can be related to the api change, new api: https://mangadex.org/thread/351011
Also it can be related to this mesage:

> Ai: Slight update: We have decided to go the route of buying a new main database server that is several magnitudes of order better than the current one and slaves. Already ordered. No ETA on how long set up will take.
>
>This purchase was made possible by the sacrifice of legacy reader server / users >_>
> https://discordapp.com/channels/403905762268545024/403926193176313857/806804455446151199

**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
W10

**Describe the bug**
Can get new chapters wen listing manga.
Some Chapters manga can't download files

**To Reproduce**

Have 1 chapter on Mangadex, list as 0 in FMD:
https://mangadex.org/title/60826/eldias-lord-megami-ni-moratta-zettai-shinanai-kyuukyoku-skill-de-nanatsu-no-dungeon-o-kouryaku-suru

22 is the last chapter at Mangadex (25 chapters), list only up to chapter 21 in FMD (24 chapters):
https://mangadex.org/title/29166/douyara-watashi-no-karada-wa-kanzen-muteki-no-you-desu-ne

List correctly but chapter 138 cant be downloaded:
https://mangadex.org/manga/19526/musuko-ga-kawaikute-shikataganai-mazoku-no-hahaoya
affected chapter
https://mangadex.org/chapter/1197116

**Comment by arbiter9605** [comment]
Its an issue with their API not showing new chapters being uploaded since their recent downtime. They are working on fixing it but til they figure what is wrong not much can be done.

**Comment by GDXN** [comment]
Thanks, updated the issue, I'm going to close the issue when mangadex works correctly again.

**Comment by azraei97** [comment]
I also want to download chapter 138 but keep fail:
https://mangadex.org/manga/19526/musuko-ga-kawaikute-shikataganai-mazoku-no-hahaoya

**Comment by Slasar41** [comment]
I decided to revert the module to use the previous API v2 link for now.
Issues like the latest chapter not showing up or some chapters can't be downloaded should be fine now. https://github.com/dazedcat19/FMD2/commit/909fe00dac3dfc033178a12cdb218fc67b53fb8d
If the API server has been fixed, I'll change it back.
