### ISSUE TITLE
[bug-website module] Web Toons

### ISSUE THREAD

**Issue by mooglestiltzkin** [dazedcat19/FMD2#32]
Web Toons website module not working. Can't download tower of god as an example. plz fix :(

**Comment by Slasar41** [comment]
Which chapter?
I can download the latest.
![image](https://user-images.githubusercontent.com/28888646/85210263-b00f8800-b368-11ea-8742-d5202b511527.png)

**Comment by Trollam** [comment]
Maybe the age gate cookies setting ?
![AgeSetting](https://user-images.githubusercontent.com/12254735/85212184-86e2fd80-b350-11ea-98ed-71337955775a.png)

**Comment by Slasar41** [comment]
@Trollam Do you have the same issue and need to put that cookies to be able to download?

**Comment by mooglestiltzkin** [comment]
@Slasar41 @trollam

trollam is correct. you had to go websites > advanced, then do that ageGatePass=true   and set to enabled for this to work. I didn't know, i just use the normal websites enabled.

If for webtoons we need this setting for it to work, maybe this should be default perhaps?

because after i did trollam suggestion, now it works.

**Comment by Trollam** [comment]
@Slasar41 Yup, some manga have an age restriction that you need to accept, otherwise the page won't load.

**Comment by Slasar41** [comment]
Please test, put it inside `lua\modules` folder and disable advanced settings.
[WebToons.zip](https://github.com/dazedcat19/FMD2/files/4810000/WebToons.zip)

**Comment by Trollam** [comment]
It seem to work properly with this module.
