### ISSUE TITLE
[bug-website module] https://reaperscans.com/comics/563929-limit-breaker cookies workaround not working

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD2#325]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7-64 bit

**Describe the bug**
I tried the workaround shown as https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964 this but not workng for me. 

![rpscans](https://user-images.githubusercontent.com/24958560/107872910-22287480-6ed8-11eb-8286-dcf764e616b0.PNG)

![rpscans 2](https://user-images.githubusercontent.com/24958560/107872934-60be2f00-6ed8-11eb-8a42-ee8dd4b2854f.PNG)

![rpscans 3](https://user-images.githubusercontent.com/24958560/107872966-af6bc900-6ed8-11eb-9c01-6d01bee33850.PNG)

How to fix this?

**Log**
[fmd.log](https://github.com/dazedcat19/FMD2/files/5977313/fmd.log)
[cf_bypass_error.log](https://github.com/dazedcat19/FMD2/files/5977315/cf_bypass_error.log)

**Comment by Inareous** [comment]
Your db is invalid. Try going to the link using your browser -> https://reaperscans.com/comics/747910-aire

A few weeks ago reaperscans decided to re-publish their manga making the old links obsolete so you'd have to update your db manually (Using `update manga list` option).

The new link is https://reaperscans.com/comics/353239-aire

**Comment by Slasar41** [comment]
Yeah, it's just an old database issue.
I've updated the database, so you can use `Update manga list` or `Download manga list from server`.
