### ISSUE TITLE
[website module request]

### ISSUE THREAD

**Issue by ratbunuts** [dazedcat19/FMD2#329]
Pls add raw website for manga. https://lovehug.net/

**Comment by Inareous** [comment]
Support for Lovehug is already provided in [FMD2](https://github.com/dazedcat19/FMD2/blob/991071a2d9ebd0773d5b8af99d54628c0a0d8f97/lua/modules/Lhscans.lua#L19).

You can add the website in Raw Section

![image](https://user-images.githubusercontent.com/18087264/108065115-1d0e2580-7090-11eb-86a3-17f4bcfbbadc.png)
