### ISSUE TITLE
[website module request]

### ISSUE THREAD

**Issue by mooglestiltzkin** [dazedcat19/FMD2#33]
I noticed that madokami doesn't seem to be an option for websites :{ in fmd1 we have that option which works by the way.

**Comment by Slasar41** [comment]
Someone already requested it https://github.com/dazedcat19/FMD2/issues/25
The reason Madokami not yet available in FMD2 is because the website module is still in pascal and need to be rewritten to lua.

**Comment by mooglestiltzkin** [comment]
thx for explanation :} Sorry for taking up your time :(
