### ISSUE TITLE
Hentainexus extension stopped working

### ISSUE THREAD

**Issue by zim267** [dazedcat19/FMD2#330]
It started from yesterday afternoon, at the morning I was still able to download some manga. It's not an issue with the website being blocked by my internet provider, as I can still open it regularly. I can still open it on the manga info, it just the chapter won't download
![image](https://user-images.githubusercontent.com/53287050/108041960-30ae9180-707a-11eb-88e7-a7b693001ebd.png)
The manga preview still work as intended, as you can see
![image](https://user-images.githubusercontent.com/53287050/108042039-42903480-707a-11eb-9afb-061eeafac456.png)
But the download won't finished :(

**Comment by AsianKR** [comment]
The download itself on Hentainexus doesnt seem to work the past 3 days. It's rather an issue with the website.

**Comment by Inareous** [comment]
This is a problem with the host site (Hentainexus) and not FMD2. FMD2 uses direct link provided by the host, while your browser will likely use the image provided by CDN.

Currently [the host ](http://images.hentainexus.com) is down, while its CDN `https://ix.wp.com` is up serving images.

A temporary fix would be to remove [this line (66)](https://github.com/dazedcat19/FMD2/blob/991071a2d9ebd0773d5b8af99d54628c0a0d8f97/lua/modules/HentaiNexus.lua#L66). From your FMD2 folder head to `lua/modules/Hentainexus.lua` and remove that line, this will set FMD2 to use link provided by CDN.

**Comment by zim267** [comment]
Oh, I see. I never bothered to download directly from the website since it's a hassle to make an account. I have tried remove the aforementioned line, but nothing have changed. I guess I'll wait until the host are up again
