### ISSUE TITLE
[bug]1stkissmanga.com download speed slow

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD2#332]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 7-64 bit

**Describe the bug**
When I download from 1stkissmanga download speed fluctuates severely, most of the time the speed is below 1/10 of my bandwidth speed. I compared the download speed to another website.

![fmd2](https://user-images.githubusercontent.com/24958560/108114109-96267080-70c2-11eb-9d3e-c8ce54744723.PNG)
![fmd3](https://user-images.githubusercontent.com/24958560/108114123-9a528e00-70c2-11eb-9354-0467f64a8950.PNG)
![speed](https://user-images.githubusercontent.com/24958560/108114494-1220b880-70c3-11eb-8e7a-068402c902ad.PNG)

My normal speed

![fmd4](https://user-images.githubusercontent.com/24958560/108115039-c7537080-70c3-11eb-861d-eca0418bb00e.PNG)

**Expected behavior**
When I download first from 1stkissmanga and manganelo, the speed most of the hovered between 700 kbp/s/550kbp/s but now it's hard to get that speed. Although I don't expect max speed all the time when the speed is so slow it's hard to use the website. Is it something that can be fixed from my side?

**Comment by Slasar41** [comment]
If another websites is normal then it's not FMD issue.
I checked by opening the chapter directly in browser and it's slow too, example: https://1stkissmanga.com/manga/the-lady-project/chapter-31/
Regarding MangaNelo, after an issue with cloudflare a few days ago, some users with different downloader also reporting downloading from MangaNelo become slower.
