### ISSUE TITLE
[website module request] Mangasusu.world

### ISSUE THREAD

**Issue by enjoe842** [dazedcat19/FMD2#334]
**Website Information**
* **Name:** Mangasusu.world
* **Root URL:** https://mangasusu.world
* **Directory list URL:**  https://mangasusu.world/manga/list-mode or https://mangasusu.world/a-z-list

* **Example manga info URL:** https://mangasusu.world/manga/black-clover
* **Example chapter URL:** https://mangasusu.world/black-clover-chapter-282hq-bahasa-indonesia

**Languages**
Indonesian

**Website relationship**
Dont know 

**Additional details**
This is a new website, not an update from [[mangasusu] updated domain #2721](https://github.com/manga-download/hakuneko/pull/2721)
Only the name is the same

**Comment by manhwalover** [comment]
**This website change**
- Root url: https://mangasusu.biz
- Directory list url: https://mangasusu.biz/manga/
- Example manga info url: https://mangasusu.biz/manga/15-minutes/
- Example chapter url: https://mangasusu.biz/15-minutes-chapter-1/

**Comment by Slasar41** [comment]
@manhwalover Create a new issue.
