### ISSUE TITLE
[bug-website module] error to download from lovehug

### ISSUE THREAD

**Issue by Dgraid12** [dazedcat19/FMD2#338]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7

**Describe the bug**
lets download some chapters but others simply show that it detects an image and then the download restarts .. on the page you can see the chapters that appear with faults

**Screenshots**
![image](https://user-images.githubusercontent.com/53473707/108475978-d96e1400-7267-11eb-8ac8-6ad1ca348e24.png)

**Comment by TienVer** [comment]
I think the failure stems from the fact that those chapters belong to series earmarked as containing adult material...and those cannot be viewed unless you're a registered user and logged in. It's the exact same requirement as when LoveHug was still LHScans.

It seems you need the following values from your LoveHug cookies (which you can get from your browser's developer tools or F12): userId, hash and PHPSESSID.

Just go into Options > Websites > Advanced, then select "LoveHug" in the scroll list and do the following:
- Set "Enabled" to "True"
- Fill the "Cookies" field with "userId=(insert number here);hash=(insert string here);PHPSESSID=(insert string here);"
- Fill the "UserAgent" field with your browser's UA
- Click "Apply"
- Restart and resume tasks.

**Comment by Slasar41** [comment]
> I think it fails because those chapters belonged to series earmarked as containing adult material...and those cannot be viewed unless you're a registered user and logged in. It was the same requirement when LoveHug was still LHScans.
> 
> It seems you need the following values from your LoveHug cookies (which you can get from your browser's developer tools or F12): userId, hash and PHPSESSID.
> 
> Just go into Options > Websites > Advanced, then selecting "LoveHug" in the scroll list and doing the following:
> 
> * Setting "Enabled" to "True"
> * Filling the "Cookies" field with "userId=(insert number here);hash=(insert string here);PHPSESSID=(insert string here);"
> * Filling the "UserAgent" field with your browser's UA.
> * Clicking "Apply"
> * Restarting and resuming tasks.

This is right, now you need to be logged in to be able to read those chapters.
Because I don't know how to add account support for LoveHug in FMD, you need to do cookies workaround.
