### ISSUE TITLE
[bug-website module] Mangadex series are blank

### ISSUE THREAD

**Issue by GelgoogGuy** [dazedcat19/FMD2#340]
Noticed it yesterday morning, but Mangadex chapters are showing blank for me. I can click read online and it'll load the chapter just fine in my browser. I also updated the manga list and tried again with no luck. Should I completely delete the Mangadex file and let it rebuild?

**Comment by Slasar41** [comment]
Check your MangaDex's language options in FMD settings.

**Comment by GelgoogGuy** [comment]
Oh JFC, I completely forgot that was a thing and it was set to Dutch. Thanks.
