### ISSUE TITLE
[website module request] komiktap.in

### ISSUE THREAD

**Issue by hachi-zy** [dazedcat19/FMD2#345]
**Website Information**

**Name:** Komiktap
**Root URL:** https://komiktap.in
**Directory list URL:** https://komiktap.in/manga/
**Example manga info URL:** https://komiktap.in/manga/ajeossi/
**Example chapter URL:** https://komiktap.in/ajeossi-chapter-64-end/

**Languages**
Indonesia

**Website relationship**
None

**Additional details**
None (most popular indonesia adult comic website)

**Comment by Slasar41** [comment]
Already supported.

**Comment by hachi-zy** [comment]
I already checked it but the domain is  **manhwa.komiktap.co** not **komiktap.in** as far as i remember

**Comment by Slasar41** [comment]
Both websites supported.
manhwa.komiktap.co = KomikTap
komiktap.in = Komiktap

**Comment by hachi-zy** [comment]
I see... well... maybe i should download the latest version because i only see KomikTap and there's no Komiktap

Thanks, sorry for the problem :)
