### ISSUE TITLE
[bug-website module] asurascans.com cannot download chapter

### ISSUE THREAD

**Issue by zartzaku** [dazedcat19/FMD2#346]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
windows 7 6 bit

**Describe the bug**
I try download https://asurascans.com/comics/solo-bug-player/. But all chapter I download is failed.

**Comment by Slasar41** [comment]
Download works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/108897427-aa311b80-7648-11eb-9534-dff6c53e5ab9.png)
But curently you need to do cookies workaround.
