### ISSUE TITLE
[bug-website module] 404 Not Found H-Sites (komiktap.in)

### ISSUE THREAD

**Issue by hachi-zy** [dazedcat19/FMD2#347]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
![image](https://user-images.githubusercontent.com/66492202/108824457-51379800-75f4-11eb-8af2-5dae9d9b2bdc.png)

**Additional context**
When i use it with my VPN on it's work, but the download speed is slow. So i wanted to know if there's a way to download this without VPN

**Comment by Slasar41** [comment]
Try to use SimpleDNSCrypt.
Since this isn't FMD issue, I'll close this.
