### ISSUE TITLE
[bug-website module] MangAs

### ISSUE THREAD

**Issue by akir42019** [dazedcat19/FMD2#35]
Can support https://mangas.in/

**Comment by Slasar41** [comment]
I can't access it.
![image](https://user-images.githubusercontent.com/28888646/85836975-a4d1b780-b7c1-11ea-94bc-12b004a64b6a.png)

**Comment by akir42019** [comment]
I do not have a problem.
![mangas_in](https://user-images.githubusercontent.com/51466748/85886180-89f84680-b7b3-11ea-97ac-2a0528469410.jpg)

it may be that your ip is blacklisted
or the website has a regional block

**Comment by Slasar41** [comment]
Region lock.
Where are you?

**Comment by akir42019** [comment]
Chile

**Comment by Slasar41** [comment]
Website already supported.
![image](https://user-images.githubusercontent.com/28888646/85896986-a16f1800-b823-11ea-94d6-1695c1d273f9.png)
But I can't download it, the image doesn't show up on my browser.
![image](https://user-images.githubusercontent.com/28888646/85897027-b186f780-b823-11ea-9662-9875c22b54b9.png)

**Comment by Slasar41** [comment]
Website already supported.
![image](https://user-images.githubusercontent.com/28888646/85896986-a16f1800-b823-11ea-94d6-1695c1d273f9.png)
But I can't download it, the image doesn't show up on my browser either.
![image](https://user-images.githubusercontent.com/28888646/85897121-df6c3c00-b823-11ea-874e-68602e460787.png)

**Comment by akir42019** [comment]
OK thanks.
View and download without problems
![boku](https://user-images.githubusercontent.com/51466748/85929161-7a92ff00-b880-11ea-8981-d51809b16925.jpg)

**Comment by Slasar41** [comment]
So FMD can download just fine on your end?

**Comment by akir42019** [comment]
boku no hero academia yes download
2D Nonsense After School! not download (0 cap)

**Comment by dazedcat19** [comment]
post the html file for the empty chapter.

**Comment by Slasar41** [comment]
@dazedcat19 The issue isn't empty chapter but some images url are encrypt in base64 on my end with a VPN.
Here's the chapter that encrypt the images url:
[view-source_https___mangas.in_manga_2d-nonsense-after-school_1_1.txt](https://github.com/dazedcat19/FMD2/files/4902243/view-source_https___mangas.in_manga_2d-nonsense-after-school_1_1.txt)
