### ISSUE TITLE
[website module request] Mangceh

### ISSUE THREAD

**Issue by akucobasaja** [dazedcat19/FMD2#351]
Website Information

    Name: Mangceh
    Root URL: https://mangceh.com/
    Directory list URL: https://mangceh.com/manga/

    Example manga info URL: https://mangceh.com/manga/worn-and-torn-newbie/
    Example chapter URL: https://mangceh.com/manga/worn-and-torn-newbie/chapter-1/

Languages
Indonesia

**Comment by manhwalover** [comment]
Cannot update chapter number after download manga list from server, please help mr.
Thanks

![image](https://user-images.githubusercontent.com/79884368/109584095-8c295680-7b33-11eb-8f68-230e8f1d1511.png)

**Comment by Slasar41** [comment]
@manhwalover I've fixed it, you can redownload the manga list.

**Comment by manhwalover** [comment]
Thanks, your the best
