### ISSUE TITLE
[website module request] Manhwaid

### ISSUE THREAD

**Issue by akucobasaja** [dazedcat19/FMD2#352]
Website Information

    Name: Manhwaid
    Root URL: https://manhwaid.co/
    Directory list URL: https://manhwaid.co/manga-genre-manhwa/

    Example manga info URL: https://manhwaid.co/manga/housekeeper/
    Example chapter URL: https://manhwaid.co/manga/housekeeper/chapter-45/

Languages
Indonesia

**Comment by akucobasaja** [comment]
![image](https://user-images.githubusercontent.com/41460162/109440088-94b25c00-7a63-11eb-815c-f3d98f960e7f.png)
number chapter cannot update automatically, must click to to load.

**Comment by Slasar41** [comment]
Looks fine on my end.
![image](https://user-images.githubusercontent.com/28888646/109540209-bc053980-7af4-11eb-9a87-1bab6ad48caa.png)
You can use my data by downloading it from server.

**Comment by akucobasaja** [comment]
all done, verry thanks
