### ISSUE TITLE
Can't download from website

### ISSUE THREAD

**Issue by hello802** [dazedcat19/FMD2#353]
- [*] I'm using the latest version.
- [*] All website modules are up to date.

- [*] This is not temporary server issue.

**System information**
Windows 10.

**Describe the bug**
Hiperdex.com i can't download any manhwa from this website.
link:-
https://hiperdex.com/manga/excuse-me-this-is-my-room-1602/

I thing the data coming from server is Null:-

Title:
N/A

Author(s):
LObeam

Artist(s):
Kook

**Comment by Slasar41** [comment]
You need to do cookies workaround.

**Comment by hello802** [comment]
Sorry for late reply my laptop showing some issue .But what is cookies workaround is something that I can do or I have to wait.And Thanks for replying.

**Comment by Slasar41** [comment]
Like this https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964

**Comment by hello802** [comment]
Thanks for replying everything is working thanks so much.
