### ISSUE TITLE
[website module request] KlanKomik

### ISSUE THREAD

**Issue by miawaw** [dazedcat19/FMD2#356]
**Website Information**
* **Name:** KlanKomik
* **Root URL:** https://klankomik.com/
* **Directory list URL:** https://klankomik.com/manga/

* **Example manga info URL:** https://klankomik.com/manga/return-to-beginning-of-the-apocalypse/
* **Example chapter URL:** https://klankomik.com/return-to-benginning-of-the-apocalypse-chapter-00/

**Languages**
Indonesia

Ty:)

**Comment by Slasar41** [comment]
Added https://github.com/dazedcat19/FMD2/commit/dd70708682d8acab103d83ceedd4df32823d84dc
