### ISSUE TITLE
[bug]hiperdex not work

### ISSUE THREAD

**Issue by jjrc28** [dazedcat19/FMD2#359]
**Prerequisite**
- [x] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jjrc28** [comment]
hiperdex not work

**Comment by Slasar41** [comment]
See https://github.com/dazedcat19/FMD2/issues/353#issuecomment-785897988
