### ISSUE TITLE
[bug-website module]https://manhuaes.com

### ISSUE THREAD

**Issue by Qizmo** [dazedcat19/FMD2#365]
**System information**
Windows 10 Home

**Describe the bug**
I add manhuaes to my list of download website.  I can "Update manga list" and "Download manga list from server" without problem.
However when I click on the manga names shown, The manga name convert into "N/A (0)"

**To Reproduce**
Double click on any manga names listed in manhuaes site.

**Expected behavior**
 name convert into "N/A (0)"

**Screenshots**
https://ibb.co/QrGSC15

**Comment by Slasar41** [comment]
Should be fixed.
You need to redownload the manga list.

**Comment by Qizmo** [comment]
Work now. Thank you very much ^^
