### ISSUE TITLE
[bug] download failed - SekteKomik

### ISSUE THREAD

**Issue by miawaw** [dazedcat19/FMD2#366]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win7 32

**Describe the bug**
Failed to download on SekteKomik:
https://sektekomik.com/manga/dragon-king-hall/ `Chapter 72-75`
https://sektekomik.com/manga/strongest-divine-doctor-mixed-city-bahasa-indonesia/ `Chapter 144-145`
https://sektekomik.com/manga/son-in-law-does-cheap-cultivation/ `Chapter 49`
https://sektekomik.com/manga/first-son-in-law/ `Chapter 28-29`
https://sektekomik.com/manga/magic-emperor/ `Chapter 165-169`

But when I checked the website, there was no problem.

Error download on SheaManga:
https://sheamanga.my.id/manga/supreme-campus-doctor/ `Chapter 68 & 69` (double download in 1 chapter) but after I checked on the website, the chapter was normal.

**Screenshots**
![Untitledhh](https://user-images.githubusercontent.com/75097226/109863082-cb6eb900-7c93-11eb-8b44-39e47efe10ad.jpg)

`Chapter 68 & 69` (double download in 1 chapter)
![IMG_20210304_024538](https://user-images.githubusercontent.com/75097226/109863183-eb05e180-7c93-11eb-9947-f1c7208a0707.jpg)

**Expected behavior**
Maybe the problem above also occurs in other comics, I hope that problem can be fixed.

**Comment by Slasar41** [comment]
SheaManga should be fixed.

**Comment by miawaw** [comment]
Thx.
How about SekteKomik?
Above, I've edited which chapters can't be downloaded.

**Comment by Slasar41** [comment]
Try open the problematic chapter on your browser to see if you can read it.
Because I can't on on my end.
![image](https://user-images.githubusercontent.com/28888646/110029097-a139fb80-7d66-11eb-8eb8-ee9693187986.png)

**Comment by miawaw** [comment]
I opened it yesterday & I had no problems with the chapters. Now just like you, I can't read it.
I just got the news, their website is currently doing a server/data migration. Could it be that this problem happened because of this?

**Comment by Inareous** [comment]
Images from SekteKomik returned 404 not found. It seems that they lost some data in their server. Unrelated to FMD.

**Comment by Slasar41** [comment]
So it's not FMD issue.
If you see the images properly but FMD still can't download it, you can report it again.
