### ISSUE TITLE
[website module request] KKJ

### ISSUE THREAD

**Issue by Trollam** [dazedcat19/FMD2#37]
**Website Information**
* **Name:** KKJ
* **Root URL:** https://kkjscans.co/
* **Directory list URL:** https://kkjscans.co/comics

* **Example manga info URL:** https://kkjscans.co/comics/794786-the-rebirth-of-an-8th-circled-wizard
* **Example chapter URL:** https://kkjscans.co/comics/794786-the-rebirth-of-an-8th-circled-wizard/1/1

**Additional context**
The website is powered by Genkan.

p.s.: How do you generate the ID in the lua file ?

**Comment by Slasar41** [comment]
Here's how to generate the ID: https://github.com/dazedcat19/FMD2/issues/10#issuecomment-636141875
Do you want to add the website by yourself?

**Comment by Trollam** [comment]
I just need to create a fork, add the change and make a pull request ?

**Comment by Slasar41** [comment]
Yes.
