### ISSUE TITLE
[bug-website module] Komikcast and Sheamanga constantly blocked by cloudflare

### ISSUE THREAD

**Issue by Enryougoku** [dazedcat19/FMD2#384]
**Prerequisite**
- [v] I'm using the latest version.
- [v] All website modules are up to date.
- [v] This is not temporary server issue.

**System information**
Windows 10 Pro

**Describe the bug**
Both websites are now blocked by cloudflare, when opening the chapter manga info "Please turn JavaScript on and reload the page"

**Additional context**
I would wish there a some module implemented to bypass these, rather than using other workaround

**Comment by Slasar41** [comment]
There's a bypass method `\lua\websitebypass\cloudflare.lua` but it's broken now.
I don't know how to fix it so you've to do workaround until someone else able to fix it.

**Comment by hachi-zy** [comment]
tambah cookie sama user agent aja gan, ane dari komikcast tembus meskipun cloudflarenya aktif, tapi ane pake FMD1 sih
