### ISSUE TITLE
[bug] cant download from mangalife the chapter folders come up empty again

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD2#385]
I'm using the latest version.
All website modules are up to date.
the site works on my browser just not on fmd and it started happening again after the previous fix, fixed the issue

the bug is that no matter which manga i download it keeps coming up with progress 1/1 and the chapters come up empty, even though there is no issue on the site itself
https://manga4life.com/

https://manga4life.com/manga/City-Of-Dead-Sorcerer
so far every chapter comes up empty on fmd

it worked after the previous fix but it stopped working all of a sudden again

**Comment by ShikenAegis** [comment]
Same issue as of last night. Module updated about 30 minutes ago, but did not fix.
