### ISSUE TITLE
[bug-website module] MangaSee

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD2#386]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**
Able to detect and read chapter list but all fail to download.
![Untitled](https://user-images.githubusercontent.com/40983245/110838403-5fb4cd80-82dd-11eb-92e3-78a620af3781.png)

**Comment by Vodes** [comment]
Mangasee & Mangalife have started messing with downloaders (Tachiyomi etc.) and this probably cant be fixed permanently

**Comment by Slasar41** [comment]
![image](https://user-images.githubusercontent.com/28888646/110859737-76afeb80-82ee-11eb-8a26-d1c7d168da92.png)
Just wait until the website owner revert it back to like before.

**Comment by Slasar41** [comment]
The fixes will work until the owner change it to something else again.

**Comment by azraei97** [comment]
That sad. It's still doesn't work though. Maybe I should wait and come back again later.

**Comment by Slasar41** [comment]
Should be fine for now.
