### ISSUE TITLE
[bug-website module] mangalife bug is back again folder comes up empty

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD2#387]
I'm using the latest version.
All website modules are up to date.
the site works on my browser just not on fmd and it started happening again after the previous fix, fixed the issue

the bug is that no matter which manga i download it keeps coming up with progress 1/1 and the chapters come up empty, even though there is no issue on the site itself
https://manga4life.com/

https://manga4life.com/manga/City-Of-Dead-Sorcerer
so far every chapter comes up empty on fmd

it worked after the previous fix but it stopped working all of a sudden again
it was working for an hour or so, and when i went back on fmd the bug came back

**Comment by jillybeans** [comment]
can you show me a screen shot of the place you get the new variable? so i can change the lua myself on my end? if not thats fine as well

**Comment by jillybeans** [comment]
nvm i found it with some trail and error.

**Comment by Slasar41** [comment]
https://github.com/dazedcat19/FMD2/issues/386
