### ISSUE TITLE
Can't download from website

### ISSUE THREAD

**Issue by hello802** [dazedcat19/FMD2#392]
i know i reopened this issue because for somedays this method worked. But now this problem happening again and that methord not working.
Am i doing anything wrong.

![Inked2_LI-min](https://user-images.githubusercontent.com/64601790/110990628-8df7e300-8399-11eb-8dfd-c769a4625bd1.jpg)
![Inked3_LI-min](https://user-images.githubusercontent.com/64601790/110990637-92bc9700-8399-11eb-840b-bde29a99eabd.jpg)
![Inked1_LI-min](https://user-images.githubusercontent.com/64601790/110990641-94865a80-8399-11eb-8b6d-fc8bbe989db8.jpg)

manhwa link:-
https://hiperdex.com/manga/omniscient-readers-viewpoint-0403/01/

**Comment by doomer23406** [comment]
>https://hiperdex.com/manga/omniscient-readers-viewpoint-0403/01/

remove the 01/ and it should work fine

**Comment by Slasar41** [comment]
> remove the 01/ and it should work fine

This is right.
You need to get the cookies from manga page instead of chapter page.

**Comment by hello802** [comment]
yap i remove  /01  from the site but still not working.
i tried these two links:-
https://hiperdex.com/manga/omniscient-readers-viewpoint-0403/
https://hiperdex.com/manga/omniscient-readers-viewpoint-0403

![1-min](https://user-images.githubusercontent.com/64601790/111018388-8149ae00-83de-11eb-9b3c-dde6dce25a51.PNG)
![2](https://user-images.githubusercontent.com/64601790/111018391-84dd3500-83de-11eb-9f40-db357f4bda45.PNG)
![3](https://user-images.githubusercontent.com/64601790/111018393-8870bc00-83de-11eb-8f4a-084b3d14f2d0.PNG)

**Comment by hello802** [comment]
hello please help me bro this is not working. what should i do i tried every and each combination but nothing working.

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/111129609-ddf8c480-85a8-11eb-8885-b68deebe1e6e.png)
![image](https://user-images.githubusercontent.com/28888646/111129674-f10b9480-85a8-11eb-9fa0-3138bd4500f4.png)

**Comment by hello802** [comment]
i am so sorry for disturbing you but i tried in my every computer. i mean 3 pcs but same error showing in ever pcs and laptops. i even changed my network .But nothing working so i redownloaded the zip from website this is what happened.

1-Clicked the link
![1](https://user-images.githubusercontent.com/64601790/111149087-72b3f000-85b2-11eb-8509-c471edfe240c.PNG)
2-Downloaded the zip file
![2](https://user-images.githubusercontent.com/64601790/111149093-747db380-85b2-11eb-9d92-75de570a2ac1.PNG)
3-No recommended websites
![3](https://user-images.githubusercontent.com/64601790/111149103-75aee080-85b2-11eb-885f-58d935880700.PNG)
4-No websites
![4](https://user-images.githubusercontent.com/64601790/111149107-7778a400-85b2-11eb-9393-2216202e9738.PNG)
5-website via url
![5](https://user-images.githubusercontent.com/64601790/111149111-78113a80-85b2-11eb-8240-c9b15f240218.PNG)

**Comment by Slasar41** [comment]
If it fresh FMD, you need to wait for the modules to finish updating.
Check Options -> Websites -> Modules

**Comment by hello802** [comment]
I don't know but some it worked after resetting everything thank you.

**Comment by Slasar41** [comment]
Glad it worked.
FMD really need to update the cloudflare bypass method.
Because I don't know how to fix it and the main dev has been missing for a few months, we're stuck using a workaround.
