### ISSUE TITLE
[bug] Impossible to resume downloads

### ISSUE THREAD

**Issue by AndreGamache** [dazedcat19/FMD2#398]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Some downloads are in the "Stopped" category and I'm unable to retry a download (right click --> "resume"). I have watched the logs, but I didn't find anything wrong :/
I have tried to donwload another manga from the same source (MangaSee) and no problem (so, no ip-ban or something like that)

**To Reproduce**
1. Go to "Stopped" category
2. Righ-click on a list item
3. Click on "resume"
4. Nothing happened

**Expected behavior**
Normally, it shoud be possible to retry the downloads 

**Screenshots**
![image](https://user-images.githubusercontent.com/80625950/111067180-4bcac080-84c3-11eb-9ec5-44eed0d98229.png)

**Comment by Slasar41** [comment]
Could you upload your `userdata` folder?

**Comment by AndreGamache** [comment]
Sure !

[userdata.zip](https://github.com/dazedcat19/FMD2/files/6137438/userdata.zip)

**Comment by Slasar41** [comment]
I use DB Browser to see your Downloads database.
![image](https://user-images.githubusercontent.com/28888646/111084629-e23fc600-8545-11eb-9bca-b37528a5a637.png)
The failed one is from MangaRock which has been shut down and MangaFox which has been renamed to FanFox.
This entries are from FMD1 and FMD2 doesn't recognize it.
You need to re-add the MangaFox one to FanFox on your favorites tab.

**Comment by AndreGamache** [comment]
Oh ok ! I thought the converter had done this job. I will try your
recommendations as soon as possible ! Thanks 👍

**Comment by Slasar41** [comment]
Ah yeah the `modules.txt` file already listed it as FanFox, it should be MangaFox as it'll be converted to FanFox by ID number.
That's why the converter failed to convert it.

**Comment by Slasar41** [comment]
I've updated `modules.txt` file if you want to run the converter again.
