### ISSUE TITLE
converter didn't convert kissmanga

### ISSUE THREAD

**Issue by HiP1** [dazedcat19/FMD2#4]
i converted from FMD1, and the kissmanga favorties i had showed up, but not the kissmanga website, so it is an empty field in the website column, and it cannot check nor download.
I guess you dont support kissmanga in your version, i cant find it in the websites list.

**Comment by dazedcat19** [comment]
No kissmanga at the moment.

**Comment by HiP1** [comment]
couldn't you just use the previous kissmanga implementation from the first FMD ? it worked but required the cookie workaround for cloudflare. Your version defeats cloudflare, so the basic lua might work ?

**Comment by dazedcat19** [comment]
there's no lua module for kissmanga

**Comment by HiP1** [comment]
oh, it's in pascal ? you can't use it ?
