### ISSUE TITLE
[website module request] add "lectormanga"

### ISSUE THREAD

**Issue by akir42019** [dazedcat19/FMD2#41]
Can support
https://lectormanga.com/

**Comment by Dgraid12** [comment]
I do not see the need to add this if there is already the one from tumangaonline, remember that they are separate but use the same database .. possibly it will result in another change in the web and more problems with compatibility

**Comment by dazedcat19** [comment]
Yeah. There's so many ripper site that use the same databases. Many even just simply link the image url to other ripper site. Those who appear first in Google search mostly low quality ripper sites. .to, .co, .today, .tl The layout maybe different but the content actually the same. I'm reluctant to add this redundant website. There's too many of them already. PR always welcome after some consideration.

**Comment by dazedcat19** [comment]
I actually looking forward to a webdriver to open a browser and wait for it for the cookies.
But, because there's no such implementation in pascal like selenium. Writing from scratch will take times.
