### ISSUE TITLE
[bug] I can't delete a record

### ISSUE THREAD

**Issue by allydevper** [dazedcat19/FMD2#412]
**Prerequisite**
-  I'm using the latest version.
- All website modules are up to date.

**System information**
Your operating system.
![image](https://user-images.githubusercontent.com/28413681/111592317-a3ed1580-8796-11eb-8a03-6aca1cb0e3cb.png)

**Describe the bug**
I can't delete a record, 

**To Reproduce**
1. I select a record
2. delete the record
3. update list from server
4. record added as new

**Expected behavior**
As I remember before, when deleting a record it would not appear again even if I updated the list.

**Screenshots**
![screen_recorder_video_2021_20_3_23_46_58](https://user-images.githubusercontent.com/28413681/111894232-1d734680-89d7-11eb-8a73-548c319fec38.gif)

**Additional context**
Tried with MangaFoxFun but is replicated in all.
I tried it in previous versions and it is the same problem
in clean version too

just as a comment,
in other versions like
Project: Free Manga Downloader
Project Page: https://github.com/riderkick/FMD
License: GPLv2
Version: 0.9.158.0

here if I can delete

Sorry for my english.
thx

**Comment by Inareous** [comment]
This looks like a weird bug, please upload the `fmd.log` file here.

**Comment by allydevper** [comment]
> This looks like a weird bug, please upload the `fmd.log` file here.

find the log

=== Log Session Started at 20/3/2021 23:54:54 by Free Manga Downloader ===
23:54:54:962 INFO: "Free Manga Downloader" started [PID:12208]
23:54:54:963 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 2.0.30.0
               Product Version   : Win64 Debug
               Host Machine      : Windows 10 64-bit Build 19041
               FPC Version       : 3.3.1
               LCL Version       : 2.1.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2020/10/06 06:07:54
               Path              : D:\fmd\fmd.exe
               Process ID        : 12208
               MainThread ID     : 16640

its all

**Comment by Tmp341** [comment]
When you update the list from the server, you again get the database file "with" that title in it. Unless you keep your own files, it is not possible. It sounds like "getting a marshmallows, removing strawberry flavored ones out, getting new package and seeing strawberry flavored ones inside makes you confused". It is still factory standard. You basically asking for what is on that site and site gives you what it has.

Unless a feature is added somehow like "banning/discarding a title hides it from future updates".

**Comment by allydevper** [comment]
> When you update the list from the server, you again get the database file "with" that title in it. Unless you keep your own files, it is not possible. It sounds like "getting a marshmallows, removing strawberry flavored ones out, getting new package and seeing strawberry flavored ones inside makes you confused". It is still factory standard. You basically asking for what is on that site and site gives you what it has.
> 
> Unless a feature is added somehow like "banning/discarding a title hides it from future updates".

i will close, but in older version this works fine. thx anyway
