### ISSUE TITLE
Import Favorites from FMD1

### ISSUE THREAD

**Issue by hachi-zy** [dazedcat19/FMD2#417]
Could you help me here
I Follow the instructions from this https://github.com/dazedcat19/FMD2/releases/tag/2.0.21.0

and according to this [post](https://github.com/dazedcat19/FMD2/issues/53), this is what is supposed to be in the converted folders:

```
settings.json (main fmd settings)
downloads.db (download list)
favorites.db (favorite list)
downloadedchapters.db (downloaded chapters history)
```
but when i run converter.exe i only get `downloadedchapters.db` and `settings.json`
![image](https://user-images.githubusercontent.com/66492202/111745615-6d5eea00-88bf-11eb-9e49-6ea9f7d52b52.png)

**Comment by Slasar41** [comment]
You have a very old FMD.
First you must update it to FMD 1.3.0.0 from here: https://github.com/fmd-project-team/FMD/releases/tag/1.3.3.0. Just copy the works folder from old FMD.
Then you can run the converter.

**Comment by hachi-zy** [comment]
It works, thank you
