### ISSUE TITLE
[bug-website module] MangaDex

### ISSUE THREAD

**Issue by metalax** [dazedcat19/FMD2#418]
**Prerequisite**
- [x ] I'm using the latest version.
- [x ] All website modules are up to date.

- [ x] This is not temporary server issue.

**System information**
Windows 7 Ultimate 64. Also tested on Windows 10 with same result.

**Describe the bug**
No chapters are visible when viewing manga Info from Mangadex, and favourites are showing as 0 chapters. The manga information is showing, as is the cover image, but the chapter list is blank. 

**Additional context**

Not sure if this is the fault, but found this on the Mangadex forum, saying the Mangadex V1 API was switched off yesterday, and that "requests have to be sent to API.mangadex.org/v2 now".
https://mangadex.org/thread/447114

**Comment by muto4013** [comment]
since i was mentioned in the mangadex thread here some questions:
Which mangas?
Did you use any av/script-blocker?
Do you use a VPN or which location are you from?
What language do you have enabled (mangadex and FMD2)
Did you use the "normal login" and is your pass in FMD2 correct ? 
Have you enabled accidental 2fa authorization ? (not supported by FMD2 (yet?)
Can you see those mangas in the browser ?

lot's of questions, i know :-)

**Comment by metalax** [comment]
> since i was mentioned in the mangadex thread here some questions:
> Which mangas?

Selecting any random manga from the list for MangaDex on the manga info page has the same effect, cover and info shows but the chapter list is blank.

Similarly, all the manga on my favourites page show as 0 chapters. And right-click>view manga info on favourites brings to the same, cover + info but no chapters. 

A sample of those on the favourites list exhibiting this behaviour.
https://mangadex.org/title/21854/boku-no-heya-ga-dungeon-no-kyuukeijo-ni-natteshimatta-ken
https://mangadex.org/title/22521
https://mangadex.org/title/26458/isekai-transporter

.. On a closer look, there is one manga on my favourites list for MangaDex that is not exhibiting the same behaviour and is showing the chapters properly.
https://mangadex.org/title/29329/itai-no-wa-iya-nanode-bougyo-ryoku-ni-kyokufuri-shitai-to-omoimasu
No idea what might be different about that one that is letting it work.

> Did you use any av/script-blocker?

I use NoScript and uBlock origin on firefox with Mangadex.org and mangadex.network whitelisted. That said, I've had them on for years and been using FMD for years without issue before this problem started a day or so ago.

Manually transfered favourites across to FMD 2, as I'd been running 0.9 of FMD which apparently doesn't work well with the converter.

edit: experimented with disabling both entirely, no change.

> Do you use a VPN or which location are you from?

No VPN

> What language do you have enabled (mangadex and FMD2)

English in both

> Did you use the "normal login" and is your pass in FMD2 correct ?

By normal you mean log in with username/password on mangadex? In which case, yes.

On FMD2 options>websites>accounts enterd username and password for MangaDex and status there is listed as Ok. pass is correct.

> Have you enabled accidental 2fa authorization ? (not supported by FMD2 (yet?)

Don't use 2fa. In additon everyones 2fa was reset by the admins following a recent hack of MangaDex. Just checked my settings on the site and no 2fa is enabled.

> Can you see those mangas in the browser ?

Yes.

> lot's of questions, i know :-)

No problem. let me know if there is anything else.

**Comment by Slasar41** [comment]
You need to download FMD 1.3.0.0, copy works folder from old FMD to that FMD, and then run the converter.

**Comment by metalax** [comment]
> 
> 
> You need to download FMD 1.3.0.0, copy works folder from old FMD to that FMD, and then run the converter.

Thanks for the advice, although not a lot of point now that I've already manually migrated over.

**Comment by eldercentipede** [comment]
same issue here. finally migrated to FMD2 to see if it was a FMD1 issue but it's still not working.

**Comment by alzamer2** [comment]
atm mangadex.org is under maintenance
so no mater what you do you will not get to any where until the site is back online
check https://twitter.com/MangaDex for updates

**Comment by azraei97** [comment]
The website under maintenance. Do you even open the website manually in browser before reporting here?

**Comment by Slasar41** [comment]
OP has legit issue because they use a very old version of FMD.
Now that issue is solved but the website went down.
I think it's better to close this.

**Comment by metalax** [comment]
> 
> 
> The website under maintenance. Do you even open the website manually in browser before reporting here?

Do you even look at timestamps? The site was up and working at the time I reported the issue.

> 
> 
> OP has legit issue because they use a very old version of FMD.
> Now that issue is solved but the website went down.
> I think it's better to close this.

My issue wasn't due to the old version. This behaviour occurs in FMD 2.

**Comment by Slasar41** [comment]
MangaDex still works fine before the website went down on my end.
Well MangaDex rewrite their website when they go back online again anyway, so the module will not work by then and need to be fixed.

**Comment by alzamer2** [comment]
when i said "atm mangadex.org is under maintenance"
i meant, module cant be fixed atm because the site is under maintenance, not that module is working fine but the site is down and fmd2 cant download from it
