### ISSUE TITLE
[bug] ManhuaPlus 404 error

### ISSUE THREAD

**Issue by xx255q** [dazedcat19/FMD2#42]
- [ ] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue. https://manhuaplus.com/ was just tested and I was able able to go to site, please confirm

**System information**
Your operating system. Win 10

**Describe the bug**

**To Reproduce**
After attempting to download list from server get Failed to finish: ManhuaPlus:404 not found

**Expected behavior**
Series list would load

**Comment by Fortiori** [comment]
Do other sites work?
Are you using a proxy or VPN?

**Comment by Fortiori** [comment]
Experiencing the same issue. Also unable to update manga list, log file shows `ERROR: LUA_ERRRUN: ?:-1: attempt to index a nil value (field '?')`

**Comment by Slasar41** [comment]
It's because there's no directory page on the website.
You need to copy the link from browser to FMD.

**Comment by dazedcat19** [comment]
@Slasar41  If a module doesn't have a mangalist then it shouldn't show up in websites selection list. assign empty category to it.
