### ISSUE TITLE
[feature request] support 2FA for mangadex login

### ISSUE THREAD

**Issue by Nandaka** [dazedcat19/FMD2#420]
**Is your feature request related to a problem? Please describe.**
Not sure if this should be considered as feature request or module bug. Mangadex now support 2FA for login.
![image](https://user-images.githubusercontent.com/836867/111778401-8ed7ca00-88ef-11eb-81b1-36bdbe9927b8.png)

But the current login form doesn't have a way to key in the 2FA OTP.
![image](https://user-images.githubusercontent.com/836867/111778468-a8791180-88ef-11eb-989b-fd6ac0cb0f81.png)

**Describe the solution you'd like**
A way to login to MangaDex if 2FA is enabled

**Describe alternatives you've considered**
Tried to use the cookie method, looks like it is working(?) but not sure for how long

**Additional context**
I'm enabling the 2FA due to recent security breach in mangadex website

**Comment by Slasar41** [comment]
There's no need to login for now.
