### ISSUE TITLE
[bug-website module]LeitorNet

### ISSUE THREAD

**Issue by Grimstonsd** [dazedcat19/FMD2#422]
**Prerequisite**
I'm using the latest version.
All website modules are up to date.

**Describe the bug**
Download won't progress 
![imagem_2021-03-19_211850](https://user-images.githubusercontent.com/71301565/111853191-b2ebd900-88f8-11eb-87cb-84f8fcd08c59.png)

**Comment by Slasar41** [comment]
You need to do cookies workaround, like this: https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964
But instead of open any title, you need to open any chapter.
