### ISSUE TITLE
[bug-website module] Asurascans.com

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD2#433]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7-64 bit System

**Describe the bug**
When I try to check a manga in FMD it disappears and this shows.
![fmd5](https://user-images.githubusercontent.com/24958560/111919466-4ddce280-8ab4-11eb-8d70-21875db24a6f.PNG)

**Comment by Slasar41** [comment]
When that happen, you need to do cookies workaround.
