### ISSUE TITLE
[website module request] ComicK

### ISSUE THREAD

**Issue by Nimesh-Bhana** [dazedcat19/FMD2#438]
**Website Information**
* **Name:** comick
* **Root URL:** https://comick.fun
* **Directory list URL:** https://comick.fun/genre/isekai

* **Example manga info URL:** https://comick.fun/comic/the-weakest-occupation-blacksmith-but-it-s-actually-the-strongest
* **Example chapter URL:** https://comick.fun/comic/the-weakest-occupation-blacksmith-but-it-s-actually-the-strongest/wZyGM-chapter-1-en

**Languages**
List of languages supported by the website
Multiple languages different languages have different support mainly engilsh
**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...")

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by SqueezedByte** [comment]
I second this request. 
Very good website.
Recently they have made an api for it to be used in tachiyomi.

**Comment by Slasar41** [comment]
I tried creating the module but some CDN's cloudflare blocked the FMD connection...
It's FMD issue.
![image](https://user-images.githubusercontent.com/28888646/120039659-7db5e280-c02f-11eb-9a3c-944274a14d8e.png)

**Comment by SonaliBendre** [comment]
[FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) may help?

**Comment by Slasar41** [comment]
@SonaliBendre I don't know how to use it and integrate to FMD.

**Comment by SonaliBendre** [comment]
[Jackett is an example using Flaresolverr
](https://github.com/Jackett/Jackett/commit/ebe05267b2c69ad1b4138a9ed11c58d6148e04d2)
It can be either used as a plugin or simply just use its [API](https://github.com/FlareSolverr/FlareSolverr#usage) assuming Flaresolverr running on the same machine or a remote server. Using flaresolverr within fmd2 isn't a good idea as with each request a browser is launched and its bad for machine with few RAM. see-# https://github.com/manga-py/manga-py/issues/413#issuecomment-874543463
![image](https://user-images.githubusercontent.com/73757361/124994040-dc28a480-e062-11eb-99c8-c6c525fd3a6a.png)
A workaround can be running Flaresolverr externally on a good server or on heroku (and heroku is free btw) and just use its API. see - #https://github.com/manga-py/manga-py/issues/413#issuecomment-876758729

Sorry but I can't help beyond this, I've no coding knowledge.

**Comment by Slasar41** [comment]
I don't understand any of those and the main dev of this project hasn't show up since last year.
