### ISSUE TITLE
[website module request] Manga-raw

### ISSUE THREAD

**Issue by xx255q** [dazedcat19/FMD2#439]
**Website Information**
* **Name:**  manga-raw
* **Root URL:** https://www.manga-raw.club/
* **Directory list URL:** https://www.manga-raw.club/browse/

* **Example manga info URL:** https://www.manga-raw.club/manga/the-great-mage-returns-after-4000-years/
* **Example chapter URL:** https://www.manga-raw.club/reader/en/the-great-mage-returns-after-4000-years-chapter-7-eng-li/

**Languages**
List of languages supported by the website
English

**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...")

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Slasar41** [comment]
Already supported.
