### ISSUE TITLE
[bug-website module] Mangasee Changed domain.

### ISSUE THREAD

**Issue by Thrieze** [dazedcat19/FMD2#44]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

Looks like they migrated to https://mangasee123.com/ I Tried to updated the Lua myself but no chapters show, they might have changed something else.

![Capture](https://user-images.githubusercontent.com/26678868/86259414-fdba9a80-bb89-11ea-9c06-eb2c75a619c7.PNG)

**Comment by HiP1** [comment]
it seems they also changed the site structure and content.

**Comment by HiP1** [comment]
the site content now changes dynamically, especially the chapter list that doesn't display all chapters but requires a click on "show all chapters" first. it seems to be angular JS

and from what I saw, it uses the same template as the new Mangalife, which doesn't work anymore too.

**Comment by molitar** [comment]
It has been fixed in FMD1 by SDXC and uploaded to the commit. Hope to see it in FMD2 soon.

**Comment by HiP1** [comment]
it seems there might still be an issue for chapters that have a dot in the number : 
20:24:33:837 LUA>DoGetPageNumber()LuaCallFunction("GetPageNumber") LUA_ERRRUN: ?:-1: attempt to concatenate a nil value
20:24:35:131 TTaskThread, checkforfinish failed=1/1 [MangaSee] "One Piece" > "/read-online/One-Piece-chapter-956.5-index-1-page-1.html"
20:24:35:155 TTaskThread, download failed. "One Piece" "Chapter 956.5" "/read-online/One-Piece-chapter-956.5-index-1-page-1.html"

**Comment by dazedcat19** [comment]
can you run it with `fmd.exe --lua-dofile` and post the log again.

**Comment by HiP1** [comment]
the first line does not appear anymore after i ran it with the argument :

08:33:01:723 WARNING: TTaskThread, checkforfinish failed=33/37 [MangaSee] "One Piece" > "/read-online/One-Piece-chapter-949.5-index-1-page-1.html"
08:33:01:725 WARNING: TTaskThread, download failed. "One Piece" "Chapter 949.5" "/read-online/One-Piece-chapter-949.5-index-1-page-1.html"
08:33:02:747 WARNING: TTaskThread, checkforfinish failed=11/12 [MangaSee] "One Piece" > "/read-online/One-Piece-chapter-956.5-index-1-page-1.html"
08:33:02:749 WARNING: TTaskThread, download failed. "One Piece" "Chapter 956.5" "/read-online/One-Piece-chapter-956.5-index-1-page-1.html"

**Comment by dazedcat19** [comment]
please test and close if ok.
one piece chapter 965.5 page 6 is broken(can't be opened in browser/missing file). so, it will show as failed.

**Comment by HiP1** [comment]
i tried other series that have dots in chapter name and it worked.
one piece seems to have 27 chapters that we can't download because of missing pages. i tried to download everything and it ended with 958/985. only two show up in the log.
