### ISSUE TITLE
[bug-website module] Mangalife not downloading chapters again

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD2#443]
**Prerequisite**
- I'm using the latest version.
- All website modules are up to date.
the website works on browser
- This is not temporary server issue.

**Describe the bug**
its not downloading the manga from mangalife on fmd. i can get the chapters and the info but nothing gets downloaded

https://manga4life.com/read-online/Slave-B-chapter-55.html

**Comment by azraei97** [comment]
No need to fix because Admin already write that he make apps unable to leach from his site temporary due to heavy load.
Now it already fixed
