### ISSUE TITLE
[bug-website module] MangaFast not downloading chapters again

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD2#445]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win10

**Describe the bug**
Can't download the manga from mangafast on fmd. i can get the chapters and the info but nothing gets downloaded

**Additional context**
https://mangafast.net/read/spirit-sword-sovereign/

**Comment by Slasar41** [comment]
Works fine on my end.
Have you read the problematic chapters on browser?

**Comment by azraei97** [comment]
Chapter 181 and ch 182. Working fine when open directly via browser. Only FMD unable to download it

**Comment by azraei97** [comment]
Chapter 181 and ch 182. Working fine when open directly via browser. Only FMD unable to download it
![Untitled](https://user-images.githubusercontent.com/40983245/112368002-96470b00-8d15-11eb-863b-a867e4d10d30.jpg)
