### ISSUE TITLE
[feature request] Global searching title from all manga

### ISSUE THREAD

**Issue by manhwalover** [dazedcat19/FMD2#448]
Please add a global search feature (search from all manga websites), because from several websites publish the same manga title but I want to find the most complete release.
![image](https://user-images.githubusercontent.com/79884368/112576775-874f7e00-8e25-11eb-8659-041930a261df.png)

**Comment by Slasar41** [comment]
You can do it on Filter tab.

**Comment by IpressKey** [comment]
Hi,

I know this is an old thread. I'm new to FMD2. May I know how to properly do this in the newest release? I tried to check the "Manga Info > FIlter >  Search in all manga sites" and  hit enter but did nothing. Any help is appreciated

**Comment by Slasar41** [comment]
@IpressKey The manga list has been downloaded?

**Comment by IpressKey** [comment]
@Slasar41 Thank you for the response and the helpful tip. I just finished downloading the manga list but still unsure how to proceed or set it up. Moreover, do I have to download the manga list from "Manga Info Tab" everytime I open the app?

**Comment by Slasar41** [comment]
Write what you want to search, enable `Search in all manga sites`, press `Filter` button.

![Image](https://github.com/user-attachments/assets/cce83453-3b60-400c-ac76-2618a6623d85)

> Moreover, do I have to download the manga list from "Manga Info Tab" everytime I open the app?

No. Manga list already saved in data folder.

**Comment by IpressKey** [comment]
> Write what you want to search, enable `Search in all manga sites`, press `Filter` button.

Thank you, Your're a lifesaver.

![Image](https://github.com/user-attachments/assets/afbfbd87-d084-4110-b063-6490e6a69849)

> No. Manga list already saved in data folder.

Sorry for asking too much. is it normal I get no search result when I press the "filter" button. Do I have to Update the Manga List as shown above, everytime?

**Comment by Slasar41** [comment]
It's because no such title in manga list.

![Image](https://github.com/user-attachments/assets/2935aa58-5c2a-40df-b891-bff73dfa4324)

You can check directly in the site what the correct title.
If you write koe no katachi it'll show up in manga list.

**Comment by IpressKey** [comment]
![Image](https://github.com/user-attachments/assets/a40eab6e-52f9-4494-9b60-1f008b627599)

Understood. Oddly enough, the manga lists will only populate when I press "download all lists from FMD server at once". I tried so many time without pressing the "download" button and it wouldn't populate just straight empty list.  After reading your latest comment, I re-open the app and it suddenly populates without pressing "download all lists from FMD server at once" now.

EDIT :- Appreciate your help and reply. Thank you
