### ISSUE TITLE
[bug-website module] Reaper Scans unable to get manga info

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD2#449]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**Describe the bug**
Nothing to say. Title and picture already enough to see the issues

**Log**
![Capture](https://user-images.githubusercontent.com/40983245/112643277-294f8480-8e7f-11eb-8e99-f3b6839e913e.jpg)

**Comment by Uroth** [comment]
I am getting the same issue. Also tried with the cookie and UserAgent workaround. No dice.

**Comment by TeepoLurking** [comment]
Same here. Tried cookie+useragent and node.JS workaround.
Hakuneko still works even without any CF workarounds, but there's one annoyance that it doesn't retrieve title name properly. But you can edit your bookmark file and fix that manually.

**Comment by OCKEYaNTO** [comment]
bump, so it doesn't go stale.

**Comment by Trollam** [comment]
The site has completely changed, maybe the cloudflare issue is no longer present.
Site : https://reaperscans.com
Manga index page : https://reaperscans.com/homepage/comics/
Title page : https://reaperscans.com/homepage/series/return-of-the-frozen-player/
Chapter page : https://reaperscans.com/homepage/series/return-of-the-frozen-player/chapter-35/
