### ISSUE TITLE
[bug-website module] asura scans random download issue

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD2#451]
- I'm using the latest version.
- All website modules are up to date.
- Check the website first with your browser
- This is not temporary server issue.

certain chapters just aren't downloading for some reason or certain mangas aren't downloading.

chapter 3 isn't downloading
https://asurascans.com/comics/return-of-the-mount-hua-sect/

chapter 53 isn't downloading
https://asurascans.com/comics/the-tutorial-tower-of-the-advanced-player/

they working on the site but are not downloading certain chapters

i think it might just be all the chapters that aren't downloading but I'm not 100% sure

**Comment by imblad3** [comment]
All asurascans chapter cannot download, It says: Please turn JavaScript on and reload the page.
![image](https://user-images.githubusercontent.com/5283753/112710071-fe057d80-8ef0-11eb-885e-e0164cb4c494.png)

**Comment by jillybeans** [comment]
doesn't work even with cookie work around

**Comment by Slasar41** [comment]
Should be fixed. You still need to do cookies workaround.
