### ISSUE TITLE
[bug-website module] KomikCast

### ISSUE THREAD

**Issue by MIRVOUS** [dazedcat19/FMD2#452]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win 7 32

**Describe the bug**
The code was changed again.

**Additional context**
Can't get manga information, can't get chapter lists, and can't download the chapter

**Comment by Slasar41** [comment]
Works fine here.
Maybe they activated cloudflare protection for a while.
When that happen, you need to do cookies workaround.
