### ISSUE TITLE
[website module request] web change domain sekaikomik

### ISSUE THREAD

**Issue by fajri411** [dazedcat19/FMD2#453]
web change domain sekaikomik
sekaikomik.com -> sekaikomik.net

**Comment by Slasar41** [comment]
Done a few days ago. https://github.com/dazedcat19/FMD2/commit/693e8940f86c0bf0f149fed06d2a1bfa86dd2e0a#diff-1fa1c6b6ac4611faca5abcba77545cccd95687ab8d263938d6390a1f88050bb8
