### ISSUE TITLE
[bug]Myreadingmanga - Not updating/downloading

### ISSUE THREAD

**Issue by leoteesh** [dazedcat19/FMD2#455]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**

Your operating system. 64-bit operating system

**Describe the bug**
I cannot download from Myreadingmanga, even when I change with the work around. The updates for this is also not working. It keeps the updates to 1
![image](https://user-images.githubusercontent.com/21075197/112751608-d41e8a80-8fc6-11eb-8d13-af738504f805.png)

I have been trying the last three days but no luck.
![image](https://user-images.githubusercontent.com/21075197/112751646-f3b5b300-8fc6-11eb-83b4-e6339d19ad24.png)

![image](https://user-images.githubusercontent.com/21075197/112751581-b7825280-8fc6-11eb-94d0-7588cca22397.png)

To Reproduce

    Go to '...' started FMD2 as usual
   Change the work around for Myreadingmanga

    Expected behavior
    It should update and download automatically

Could you please advise?
Many thanks

**Comment by Slasar41** [comment]
Same case with issue https://github.com/dazedcat19/FMD2/issues/449
FMD still get cloudflare page even with using a workaround.
I don't know anyone else who can fix it.
I worry this issue will spread to other websites that use cloudflare protection.

**Comment by leoteesh** [comment]
Hi,

This was working for a while but now it stopped again.
When trying to use the workaround, I cannot find "__cfduid" when I press F12 - is anyone else having the same issue?

**Comment by WhoAreYouPeople** [comment]
I think I see what the issue is in the cloudflare module, I'm gonna try and fix it over the weekend.

**Comment by WhoAreYouPeople** [comment]
I have gotten some of the unimplemented webdriver features working. Still a work in progress though.

**Comment by Slasar41** [comment]
@WhoAreYouPeople Good luck.
This issue also affecting many websites.

**Comment by WhoAreYouPeople** [comment]
Thank you,  it seems like the clearance cookie wasn't actually being dumped so I'm working on that now. Do you know which pascal module calls the cloudflare.lua file?

**Comment by WhoAreYouPeople** [comment]
Further investigator looks like there are some checks to aspects of the header that lead to the request getting the error box 1000s message. I have a test program I'm working on to try and create an acceptable header.

**Comment by Slasar41** [comment]
I don't know anything about pascal, but I know how to build FMD.
Let me know if there's a need to modify the pascal source code.

**Comment by WhoAreYouPeople** [comment]
I got it working, in python. So the major changes are I think FMD is using python library requests to reach out, in order to support http2 that needs to be replaced with httpx. Luckily httpx and requests have almost the same syntax. Also the header order has to match the browser and include matching data. I am still working on multiple cookie support which is sometimes required.

I have uploaded a documented version of the script I am using to do this. If you could help me with modifying pascal source code I think we can get it working.

https://github.com/WhoAreYouPeople/metatest

**Comment by WhoAreYouPeople** [comment]
Also if you can help me with the pascal one more time I can integrate my metadata saver for cbz.

**Comment by Slasar41** [comment]
Thanks for the work.
What I need to do?

**Comment by WhoAreYouPeople** [comment]
Not a problem, I'll be glad to see it work. The code needs to be changed so that an http2 connection is being initiated, currently it makes a http/1.1 request. I think currently the python module "requests" is being used and that just needs to be swapped to "httpx". That looks to be it. The rest of the header isnt actually needed. i just retested it.

**Comment by WhoAreYouPeople** [comment]
I have updated my code to reflect this. All that work and all thatactually mattered was a change from http1.1 to 2

**Comment by WhoAreYouPeople** [comment]
Actually one last thing. 

This is actually all that is required to get a successful response. Just the user agent and the cookie.

    headers ={'Cookie' : 'cf_clearance=COOKIE',
'User-Agent' : 'USERAGENT'}

Sent metatest.py header
Host: WEBSITE
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: cf_clearance=COOKIE
User-Agent: USERAGENT


But this is what fmd2 sends.

Connection: keep-alive
Cookie: cf_clearance=COOKIE
User-Agent: USERAGENT
Accept-Encoding: gzip, deflate, br
DNT: 1
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Charset: utf-8

It looks to be the additional information as well that is leading to the request getting blocked


My original commit of metatest.py included all this info and had it sent to match the ordering. If we want to match the keep the additional information we just have to insure it is ordered correctly and matches the browser. Like this:

headers = OrderedDict({'Accept' : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
'Accept-Encoding' : 'gzip, deflate, br',
'Accept-Language' : 'en-US,en;q=0.5',
'Alt-Used' : 'DOMAIN',
'Cache-Control' : 'max-age=0',
'Connection' : 'keep-alive',
'Cookie' : 'cf_clearance=COOKIE',
'Host' : 'DOMAIN',
'Referer' : 'https://EXAMPLE.COM/',
'Sec-Fetch-Dest' : 'document',
'Sec-Fetch-Mode' : 'navigate',
'Sec-Fetch-Site' : 'same-origin',
'Upgrade-Insecure-Requests' : '1',
'User-Agent' : 'USERAGENT'

**Comment by WhoAreYouPeople** [comment]
So,
1. httpx instead of requests
2. Either less header info, or matching ordered header info

I hope that's clear sorry for the word pile

**Comment by Slasar41** [comment]
Thanks for the information.
Do you know what and where to change in the pascal code?

**Comment by WhoAreYouPeople** [comment]
I do not, I dont know what file is actually making the call. And I cant search the repo because it's a forked repo and those cant be searched in github. Do you know how to search a project in lazarus?

**Comment by Slasar41** [comment]
You can search the whole project by using Notepad++.
![image](https://user-images.githubusercontent.com/28888646/161166952-ebfee752-d876-4cb9-b60f-9027c7b25299.png)

**Comment by WhoAreYouPeople** [comment]
@Slasar41 you found it! Nicely done! I will open this up tomorrow. Unless do you have it sorted? Either way we can totally get this working! Thanks for the work.

**Comment by Slasar41** [comment]
I haven't done anything. I worried it'll introduce a new bug if I mess up.

**Comment by WhoAreYouPeople** [comment]
Oh I get that, I feel the same way, something that fixes the ERROR_BOX_1000s might break something else. You definitely have a better grasp of the program then me though, so I doubt you'd introduce a bug. I'll start plugging away at it afterwork. Hopefully all that is required is minor tweaking. Please let me know if you come up with anything, the help would be greatly appreciated.

**Comment by WhoAreYouPeople** [comment]
So I managed to change the header, and make a HTTP 2.0 connection but the issue now is I cant figure out how to cause an ALPN h2 negotiation. Which looks to be the only thing that separates the FMD2 request from firefox and my python program.

Somewhere in this is the solution I think.
http://synapse.ararat.cz/doc/help/
http://www.ararat.cz/synapse/doku.php/public

**Comment by Slasar41** [comment]
Yeah, sorry I can't help.
I don't understand anything. :3
I've already ask people in the [FMD's Discord server](https://discord.gg/cXKKgw3) for more help.

**Comment by WhoAreYouPeople** [comment]
No problem, I dont know how synapse really works either. But I did try the trunk version instead. Thank you for reaching out! I didn't know there was a discord, hopefully someone will know what to do.

**Comment by Slasar41** [comment]
Just tested again and now the site can be accessed from FMD by just doing cookies workaround now.
![image](https://user-images.githubusercontent.com/28888646/194682298-e05d1f80-daf7-4c80-895d-11c1c0bef299.png)
