### ISSUE TITLE
[bug-website module] MangaSee broken again

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD2#456]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**
Can't detect any chapter. Website working fine

**Log**
![Untitled](https://user-images.githubusercontent.com/40983245/112760780-c26ece80-902a-11eb-85bf-1af5dd3de8b0.png)

**Comment by jillybeans** [comment]
same with mangalife

**Comment by jillybeans** [comment]
it seems to work with the cookie workaround at least for mangalife. im assuming it may work with mangasee as well

**Comment by Slasar41** [comment]
Yeah seems like MangaLife & MangaSee activated cloudflare protection so you need to do cookies workaround.

**Comment by azraei97** [comment]
It seen that it work fine again without any cookies workaround. So it just system glitch?

**Comment by Slasar41** [comment]
If you access the website and get a cloudflare page for a few seconds, then workaround is needed.
Just now I'm doing the workaround to update my MangaSee favorites.
