### ISSUE TITLE
Where "Download manga list from server" is downloaded from?

### ISSUE THREAD

**Issue by formigao** [dazedcat19/FMD2#458]
Basically i want to know when was this database last updated. 
should i download from server?
manually update ?

If i've updated one site last week and try to update now again it could be a fast server download or a slow manual one.

BUT if the database from server is 1month old its going to backfire... and i will need to manual update 4 week of changes now.

Can we have a date from last databases updates? on our client and on servers?

maybe even deny a server download if the local one is more recent.

**Comment by Slasar41** [comment]
The databases are from here: https://github.com/dazedcat19/FMD2-DB
I'm only update regularly some of them. Other users can help update it by making a pull request.
We have a nice organized list with a date and manga count before with [FMD1](https://github.com/fmd-project-team/FMD-WebsiteDatabases) but I'm too lazy to make it for FMD2.
