### ISSUE TITLE
[bug-website module] Batoto

### ISSUE THREAD

**Issue by HiP1** [dazedcat19/FMD2#46]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
can't access Batoto from FMD, seems they changed the cloudflare challenge to a new one.

**Additional context**

**Log**
02:24:09:611 WebsitBypass[clounflare]: detected the new Cloudflare challenge, not supported yet
https://bato.to/series/69561

**Comment by HiP1** [comment]
seems the latest updatz fixed it
or batoto changed something

**Comment by dazedcat19** [comment]
https://github.com/dazedcat19/FMD2/commit/deac3193d092196aee69bde2fa6e14cb4d84352e

**Comment by HiP1** [comment]
it's back :
19:22:23:264 WebsitBypass[clounflare]: detected the new Cloudflare challenge, not supported yet
https://bato.to/series/62942
