### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Renvix** [dazedcat19/FMD2#461]
**Prerequisite**
- [x] I'm using the latest version.
- [ ] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 64bit

**Describe the bug**
FMD cannot be opened, an error appears "Can not load WebP codec library"

**Expected behavior**

**Screenshots**
![fmd error](https://user-images.githubusercontent.com/29302760/113133135-86fe1b00-9249-11eb-9765-1560c815d40e.jpg)

**Comment by Slasar41** [comment]
Try replace it with this: https://github.com/dazedcat19/FMD2/blob/master/dist/x86_64-win64/libwebp.dll

**Comment by Renvix** [comment]
> 
> 
> Try replace it with this: https://github.com/dazedcat19/FMD2/blob/master/dist/x86_64-win64/libwebp.dll

Thanks
