### ISSUE TITLE
Blank Website on Imported FMD1 Favorites 

### ISSUE THREAD

**Issue by Plegmatis** [dazedcat19/FMD2#462]
I tried to import my favorites from FMD1(1.3.2.0) 64 bits using latest converter to my latest FMD2(2.0.31.0) 64 bits. The import works but there are about 600 out of 2300 manga with blank website. I noticed some of blank website manga are from mangahere while there are mangahere listed on some manga.
![mangga](https://user-images.githubusercontent.com/26659986/113220659-c5c5bc80-92ad-11eb-94d6-6f40f4e5eca9.png)

**Comment by Slasar41** [comment]
Try download DB Browser, open `userdata\favorites.db` with that program and then see the `moduleid` column with the missing website name.

**Comment by Plegmatis** [comment]
it's works, turn out moduleid for some manga still site names ("MangaHere" etc) instead hash
i need to update it manually, thanks @Slasar41
