### ISSUE TITLE
[bug] Cannot download/update from Bato.to

### ISSUE THREAD

**Issue by noering** [dazedcat19/FMD2#467]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Windows 7

**Describe the bug**
Chapter lists and favorites not working, user agent work around failed too.

**Screenshots**
![01](https://user-images.githubusercontent.com/3715548/113494963-bd70ba00-9517-11eb-8430-c292b8b1b662.JPG)
![02](https://user-images.githubusercontent.com/3715548/113494995-1b050680-9518-11eb-8110-cb6369d78d62.JPG)
![03](https://user-images.githubusercontent.com/3715548/113494997-1cceca00-9518-11eb-9955-e1af0473ed76.JPG)

**Comment by Slasar41** [comment]
Same case with issue https://github.com/dazedcat19/FMD2/issues/449

**Comment by Sakurahime08** [comment]
Hope you can update Bato.to :)

**Comment by HiP1** [comment]
@Slasar41 can you try by adding the URLs to https://batotoo.com/ and https://comiko.net/ to the lua ?
i think those point to the same server, but they are not protected.
I could replace the url in the lua, and it seemed to work, and i downloaded a whole bunch of chapters from a manga.
maybe other modules that don't work also could be fixed by adding mirrors ?

**Comment by Slasar41** [comment]
@HiP1 I just tested and only batotoo.com url is working, comiko.net is the same like bato.to.

Yes, you can try it if the template is the same but doesn't have the protection.

**Comment by HiP1** [comment]
@Slasar41 I changed my local lua and i could get the website manga list updated, load the chapters, download chapters, and use favorites. so it should be ok to add it to the main code, i think.
i'll let you do it, as you are certainly cleaner and more competent than me :)

**Comment by Slasar41** [comment]
Mirrors that's working have been added.
Users can transfer from Bato.to to one of these websites.

**Comment by HiP1** [comment]
@Slasar41 thanks ! I think this pretty much closes all issues with batoto for now.
if we can find mirrors for other websites with issues like this, it could help. maybe one exists for mangasee that would allow to avoid using the workaround and could update the manga list too :D

**Comment by HiP1** [comment]
is there a way to convert all the favorites we have on batoto to one of the mirrors without selecting them all again ?

**Comment by Slasar41** [comment]
@HiP1 The mirror of MangaSee is MangaLife and it's still working without applying any workaround.

**Comment by HiP1** [comment]
@Slasar41 OMG thanks ! I never knew, even though I actually use Mangalife xD

**Comment by Slasar41** [comment]
I'm able to access bato.to with a VPN connection from Philippines.
![image](https://user-images.githubusercontent.com/28888646/186888526-ee0aba06-c261-4bed-a124-052be3a085d2.png)

**Comment by Slasar41** [comment]
Looks like FMD can access the site even without a VPN now.
