### ISSUE TITLE
[bug] Tumangaonline repeatedly downloads

### ISSUE THREAD

**Issue by Dgraid12** [dazedcat19/FMD2#47]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7 ULTIMATE SP1

**Describe the bug**
I close fmd2 and when I run it again and check the favorites, download all the manga chapters in TMO that I have marked

and if I download them and they all finish, I close it again and when I open it, it asks to download all the chapters again

**Screenshots**
![001](https://user-images.githubusercontent.com/53473707/86409309-a2ba9d80-bc86-11ea-843c-7f1cccd334cc.png)

![002](https://user-images.githubusercontent.com/53473707/86409312-a4846100-bc86-11ea-9a88-debdf3c33cb8.png)

**Comment by dazedcat19** [comment]
manual download and favorite download are using different downloaded chapters database. tho, the favorite download will be added to the main downloaded chapter list.

**Comment by Dgraid12** [comment]
> manual download and favorite download are using different downloaded chapters database. tho, the favorite download will be added to the main downloaded chapter list.

but when I download everything that I update in favorites and close and reopen the program, they are downloaded again

**Comment by dazedcat19** [comment]
I don't really understand this. can you elaborate more?
you can check the downloaded chapters in favorites.db with sqlite db browser or something like that. compare it with the new found chapter urls. if the chapters is dinamically created by the server (it will be different each time). then it will be hard to solve.

**Comment by Dgraid12** [comment]
> I don't really understand this. can you elaborate more?
> you can check the downloaded chapters in favorites.db with sqlite db browser or something like that. compare it with the new found chapter urls. if the chapters is dinamically created by the server (it will be different each time). then it will be hard to solve.

Now that you say it, it seems to be that, yesterday because I was busy I left several chapters open without loading, viewing them page by page ... and when I wanted to put it in cascade mode, the chapter did not load ... I had to update it with Ctrl + R to load it the chapter, possibly the page if you do them randomly

**Comment by dazedcat19** [comment]
I just checked it. the chapterlist is static urls. My favorite check working just find. check the permission of your favorites.db. make sure it written properly when closing fmd.
