### ISSUE TITLE
[bug] MangaPark.net "We are checking your browser... mangapark.net"

### ISSUE THREAD

**Issue by AltPlus248** [dazedcat19/FMD2#474]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10.

**Describe the bug**
Can't get chapters to load from MangaPark.net

**To Reproduce**
1. Go to 'Manga Info'
2. Click on 'a manga or paste a url to a manga'
3. Scroll down to 'where info and chapters are supposed to load'
4. See error 'title says "We are checking your browser... mangapark.net" and no chapters load'

**Expected behavior**
When trying to connect to a manga on MangaParknet, it is unable to load info or chapters.

**Screenshots**
![image](https://user-images.githubusercontent.com/68253192/113612456-7d8ffc80-9615-11eb-9b67-2773ed89df68.png)

**Additional context**
Its been like this for a few days now.

**Comment by Slasar41** [comment]
Same case with issue #449

**Comment by Playcool92** [comment]
Just logged in to report the same problem, saw this thread, please guys, someone look into this.
Now that Mangadex is down temporary, it is hard to find an website that has decent scans....

**Comment by kazenoade** [comment]
i think mangapark change the domain to this https://v3.mangapark.net/

**Comment by Playcool92** [comment]
> i think mangapark change the domain to this https://v3.mangapark.net/

Yes, I have seen and accessed v3 version of them before, but the fact remains, as it stands, this useful software cant be used in one of the most resourceful manga websites out here, which is even worst, when the other, MangaDex is down for a few more weeks.

**Comment by Qizmo** [comment]
A question please.


> 
> 
> i think mangapark change the domain to this https://v3.mangapark.net/

How do I load from this v3? I try open it in FMD2 but it said "URL not supported". There is also no this website in option.

**Comment by AltPlus248** [comment]
MangaPark updated to version 3 (whatever that means). The new version is using the regular URL now https://mangapark.net/ but the problem is still the same as it was before.

**Comment by Slasar41** [comment]
They use Batoto-like template now.
I'm trying to move the code to Batoto module but it's say this:
![image](https://user-images.githubusercontent.com/28888646/136351921-cfe55a69-a10d-40a0-a838-4e0ee51cca35.png)
And I can't find the cookies to do a workaround.
