### ISSUE TITLE
[bug] Mangakakalot.fun and Mangafox.fun can't download chapter files

### ISSUE THREAD

**Issue by Uzi08** [dazedcat19/FMD2#475]
Pre-requisite:

- [/ ]  I'm using the latest version.
- [/ ] All website modules are up to date.
- [/ ]  This is not temporary server issue.

System information
- Windows 10

Bug:
Mangakakalot.fun and Mangafox.fun can't download chapter files but when i view the site, the chapter is there and can be read on site.

Screen shots:
![image](https://user-images.githubusercontent.com/82005999/113645086-cc42a280-96b8-11eb-8236-dbec3ce93b6e.png)

![image](https://user-images.githubusercontent.com/82005999/113644885-550d0e80-96b8-11eb-96bb-96f5d782cc1b.png)

![image](https://user-images.githubusercontent.com/82005999/113644719-f34ca480-96b7-11eb-9bb8-07e6062101d0.png)

**Comment by Slasar41** [comment]
Same case with issue https://github.com/dazedcat19/FMD2/issues/466

**Comment by GeckoPrime** [comment]
I'm having the same issue, is there a fix to this yet?

**Comment by xpndkt** [comment]
Same issue

**Comment by Akheron11** [comment]
same issue here

**Comment by ghost** [comment]
Same issue

**Comment by Akheron11** [comment]
> Same case with issue #466

already tried using cookies + user agent but didn't work. and using the selenium + node.js didn't open the firefox. tried using selenium + python, it open firefox but no response.

**Comment by Akheron11** [comment]
Yesterday I could download chapter from mangakakalot.fun again, but just now when I tried to download again, the same problem come back. :-(
