### ISSUE TITLE
[bug] Readcomicsonline 'chaptername' folder error.

### ISSUE THREAD

**Issue by EpicLunchBox** [dazedcat19/FMD2#48]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7 Profesional SP1.

**Describe the bug**
I think i just found a bug (actually like 2) on this page. I will try to explain them clearly.

First of all, when I click on a comic to download it, sometimes shows the cover, sometimes dosen't. I will noticed that this happens depending of the comic (as shown in the screenshoots). Furthermore it doesn't shows the chapter names like usual, only the numbers, so when I download 'x' chapter of 'y' comic, the foldername of that comic results on someting like %CHAPTER% or %NUMBERING% depending of wich config I choose.

**Screenshots**
![001](https://user-images.githubusercontent.com/29029681/86427584-250b8780-bcb0-11ea-9dfb-6b95f6b5c8dd.jpg)
![002](https://user-images.githubusercontent.com/29029681/86427593-276de180-bcb0-11ea-9a8f-224a87cc6ac0.jpg)
![003](https://user-images.githubusercontent.com/29029681/86427599-29d03b80-bcb0-11ea-97a7-e4656c48281f.jpg)
![004](https://user-images.githubusercontent.com/29029681/86427774-b4b13600-bcb0-11ea-802e-604159807ad3.jpg)

**Comment by dazedcat19** [comment]
Please test and close if ok.
