### ISSUE TITLE
[website module request] Manga18fx

### ISSUE THREAD

**Issue by manhwalover** [dazedcat19/FMD2#481]
**Website Information**
* **Name: Manga18fx** 
* **Root URL: https://manga18fx.com/**
* **Directory list URL: https://manga18fx.com/manga-genre/manhwa**

* **Example manga info URL: https://manga18fx.com/manga/lowlife**
* **Example chapter URL: https://manga18fx.com/manga/lowlife/chapter-50**

**Languages**
English and Korea (RAW)

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manhwalover** [comment]
![image](https://user-images.githubusercontent.com/79884368/113951511-e659bd80-983d-11eb-9d8d-7d49851935e7.png)
Can't download manga list, this manga title empty and database ID **7f1b637a525940db9459f1cbf2f7cfc3** not found from https://github.com/dazedcat19/FMD2-DB.

**Comment by Slasar41** [comment]
Added.
