### ISSUE TITLE
[bug] Small problem with ManhuaScan

### ISSUE THREAD

**Issue by hmslima** [dazedcat19/FMD2#486]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not a temporary server issue.

**System information**
Kubuntu 20.04 _(Wine 6.0)_
I am using the 64bit version of FMD

**Describe the bug**
List of ManhuaScan is not automatically downloaded, it gives a 404 error message, **however**, if you select the option `Update manga list`, the list is downloaded, and then you can download the mangas. As you can see, this problem can be solved by the user, but it shouldn't happen, many unexperienced people will think that it's impossible to download mangas from ManhuaScan through FMD, and I love this program, I want it to be perfect.

**Steps to Reproduce**
1. Activate the website ManhuaScan (`Options` → `Websites`)
2. Select the website ManhuaScan in the tab `Manga Info`
3. FMD will ask "Do you want to download manga list from the server?"
4. Yes
5. FMD gives the error message: "Failed to finish" "ManhuaScan: 404 Not Found"
6. _I repeated all of these steps with a new installation of FMD_

**Comment by Slasar41** [comment]
I've uploaded the manga list to the server.

The users can copy the url from browser and paste it to the url box in Manga Info tab.
Sometimes I don't have the time and forgot to add it to the server.
And anyone can help to contribute the manga list [here](https://github.com/dazedcat19/FMD2-DB) by creating a pull request.
