### ISSUE TITLE
hiperdex not work

### ISSUE THREAD

**Issue by jjrc28** [dazedcat19/FMD2#487]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jjrc28** [comment]
Sorry for bothering but this is my favorite page. thanks for your help.

**Comment by Slasar41** [comment]
Just wait.
Your issue is still open. https://github.com/dazedcat19/FMD2/issues/479
