### ISSUE TITLE
Lost some websites

### ISSUE THREAD

**Issue by arifsyahbani** [dazedcat19/FMD2#49]
WIndows 10 ver 1909
![lost](https://user-images.githubusercontent.com/45502806/86467007-ccdf8e80-bd5e-11ea-9c71-1cf4c31cbb68.jpg)
![image](https://user-images.githubusercontent.com/45502806/86467065-ec76b700-bd5e-11ea-9987-7bd40f170d0e.png)

after updating to fmd 2.0.16, i notice some of website list are gone.

**Comment by dazedcat19** [comment]
Not all websites are supported. make a new website support request instead.
