### ISSUE TITLE
[bug-website module] PMScans not working

### ISSUE THREAD

**Issue by cuanim** [dazedcat19/FMD2#490]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
PMScans isn't working which I doubt is due to the site url being changed to https://reader.pmscans.com/
It's also showing URL not supported when I am pasting this link https://reader.pmscans.com/manga/ahiru-no-sora/ into the Input URL here box.

**Comment by cuanim** [comment]
Thanks for the quick response!

**Comment by 27136773** [comment]
Some mangas and chapters are not available on the new domain, so it makes sense to still keep the Madara website support up and running...

e.g.

Madara: https://www.pmscans.com/manga/big-order/ (available)
MangaStream: https://reader.pmscans.com/manga/big-order/ (not available)

Madara: https://www.pmscans.com/manga/i-am-the-sword-king/ (8 chapters)
MangaStream: https://reader.pmscans.com/manga/i-am-the-sword-king/ (1 chapter)

----

![image](https://user-images.githubusercontent.com/27136773/114265550-a9362c80-99f1-11eb-8862-8f076f4ac7a3.png)

**Comment by Slasar41** [comment]
I see. I'm only access the old rooturl and it immediately redirect to the new one so I just assume the Madara site doesn't exist anymore.
Well the old one will eventually be transfered to the new one so I'll just leave it unless the users wants the old one to still be supported too.
