### ISSUE TITLE
[website module request] [hentai.money]

### ISSUE THREAD

**Issue by serveral1** [dazedcat19/FMD2#491]
**Website Information**
* **Name:** hentai.money
* **Root URL:** https://hentai.money
* **Directory list URL:** https://hentai.money/1

* **Example manga info URL:** https://hentai.money/book/830194867237683230
* **Example chapter URL:** https://hentai.money/book/830194867237683230/1

**Languages**
List of languages supported by the website
English
**Website relationship**
None that I'm aware of.

**Additional details**
Site UI is very barebones. Came across it via google search, so I don't know who may be hosting the content or if there's any more information pertaining the website's existence in reddit or relevant image boards.

**Comment by formigao** [comment]
donwloading works fine but i cant update the database

**Comment by Slasar41** [comment]
It's broken and need to be fixed.
