### ISSUE TITLE
[website module request] earlymanga[dot]org

### ISSUE THREAD

**Issue by hesoyamma785** [dazedcat19/FMD2#497]
**Website Information**
* **Name: Earlymanga** 
* **Root URL:https://earlymanga.org**
* **Directory list URL:https://earlymanga.org/manga**

* **Example manga info URL:https://earlymanga.org/manga/i-have-a-dragon-in-my-body**
* **Example chapter URL:https://earlymanga.org/manga/i-have-a-dragon-in-my-body/chapter-334**

**Languages**
English

**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...")

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Slasar41** [comment]
https://github.com/dazedcat19/FMD2/commit/8b5d772f82293b9cce5ce4f49e100912b5d811b4
