### ISSUE TITLE
I can't open any files from MangaDex to put them to download or get anything from MangaFox and MangaKakalot to download[bug]

### ISSUE THREAD

**Issue by GeckoPrime** [dazedcat19/FMD2#498]
**Prerequisite**
- [yes ] I'm using the latest version.
- [yes ] All website modules are up to date.
Website loads fine in my browser
- [ yes] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
When I try to open any manga on MangaDex and all my chapters updates from MangaFox and MangaKakalot just keep saying failed now.

**To Reproduce**
1. Go to 'MangaDex'
2. Click on 'Any manga'
![Screenshot (1)](https://user-images.githubusercontent.com/62570331/114308477-38a31480-9ab2-11eb-84f1-5e11d3106926.png)
![Screenshot (3)](https://user-images.githubusercontent.com/62570331/114308564-69834980-9ab2-11eb-8c30-a77329fb7386.png)

**Expected behavior**
I expected it to show me the chapters for download

**Screenshots**

**Additional context**

**Comment by Tyranical** [comment]
At least check the website, Mangadex is down until they fix security issues.

**Comment by Maxwell12347842** [comment]
mangadex got hacked. you can't download anything or use mangadex since they have shut down their service currently. they re-develope their whole website to fix issues and implement new stuff.

**Comment by Slasar41** [comment]
- MangaDex is fixed.
- Your title from MangaKakalot moved to Manganato and works fine.
- Which MangaFox, MangaFoxClub or MangaFoxFun?

**Comment by GeckoPrime** [comment]
MangaFoxFun

**Comment by GeckoPrime** [comment]
And thanks c:

**Comment by Slasar41** [comment]
Same issue as https://github.com/dazedcat19/FMD2/issues/475.
