### ISSUE TITLE
[bug-website module] Manhuascan

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD2#51]
**Prerequisite**
- [x] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Unable to download list even the download from server fails.

**Log**

**Comment by dazedcat19** [comment]
@Slazar41
I don't even know where the complete mangalist is from their website.

**Comment by Slasar41** [comment]
This? https://manhuascan.com/manga-list.html?listType=allABC
Yeah updating manga list doesn't work, I don't know where the issue.
