### ISSUE TITLE
[bug] hiperdex.com can't download chapter files

### ISSUE THREAD

**Issue by jjrc28** [dazedcat19/FMD2#514]
**Prerequisite**
- [ ] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jjrc28** [comment]
hiperdex.com not work

**Comment by Slasar41** [comment]
Use cookies workaround.
