### ISSUE TITLE
[bug] hiperdex not work

### ISSUE THREAD

**Issue by jjrc28** [dazedcat19/FMD2#515]
**Prerequisite**
- [ ] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jjrc28** [comment]
hiperdex is not working

**Comment by Slasar41** [comment]
When it's not working, use cookies workaround.
