### ISSUE TITLE
[bug] es.leviatanscans.com

### ISSUE THREAD

**Issue by rs3mk** [dazedcat19/FMD2#518]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Change system to Madara

**Comment by Slasar41** [comment]
Done. https://github.com/dazedcat19/FMD2/commit/01b495478fec4869130291b08e2d6acd96154e74
