### ISSUE TITLE
[bug]Myreadingmanga.info - Error in downloads

### ISSUE THREAD

**Issue by leoteesh** [dazedcat19/FMD2#52]
**Prerequisite**
- [ ] I'm using the latest version.
- [ ] All website modules are up to date.
 Website is working
- [ ] This is not temporary server issue.

**System information**
Your operating system.
![image](https://user-images.githubusercontent.com/21075197/86942885-a1351d80-c13d-11ea-88cb-71fcbf513168.png)

**Describe the bug**
Manga downloaded from the above is not working. Getting error messages.  I can view the manga in managinfo

**To Reproduce**
1. Go to '...' manga link
2. Click on '....' download

**Expected behavior**
Once click on download, should expect the manga to download

**Screenshots**
![image](https://user-images.githubusercontent.com/21075197/86942770-75199c80-c13d-11ea-83ed-abf77b78e364.png)

**Additional context**

I am not sure if I have filled this form correctly but could you please help?

Many thanks

**Comment by Slasar41** [comment]
Should be fixed, please test.

You should use `Website module report` for reporting website issue next time.
Fill the box with an `x`.

**Comment by dazedcat19** [comment]
You should also put the manga link and chapter so developer can check it right away. sometimes the bug only happened in some manga or chapter.
