### ISSUE TITLE
[bug]Manhua Scans- download error

### ISSUE THREAD

**Issue by leoteesh** [dazedcat19/FMD2#525]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Your operating system. 64-bit operating system

**Describe the bug**
Since a few days ago I am getting download error from Manhuascans and downloads are not working. 

**To Reproduce**
1. Go to '...' start FMD as usual
2. Click on '....'  wait for the update and download

**Expected behavior**
A clear and concise description of what you expected to happen. Should download automatically but Error download message received.
Website is working fine.

**Screenshots**

![image](https://user-images.githubusercontent.com/21075197/116788750-535e1d00-aaa3-11eb-95bb-452ef3990f7d.png)

Can you please advise?
Thanks so much

**Comment by Slasar41** [comment]
Have been fixed. https://github.com/dazedcat19/FMD2/commit/e95ef9a47748f1e3978b94e15dcce22d6caae161
