### ISSUE TITLE
[bug] Mangakakalot.fun can't download chapter files

### ISSUE THREAD

**Issue by Akheron11** [dazedcat19/FMD2#526]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7

**Describe the bug**
Mangakakalot.fun can't download chapter files but when i view the site, the chapter is there and can be read on site.

**Additional context**
I already tried using cookies + user agent but didn't work. And tried using the selenium + node.js +firefox but it didn't open the firefox. And lastly, I tried using selenium + python + firefox, and it only open firefox but no response.

**Comment by Slasar41** [comment]
No need to open another issue. https://github.com/dazedcat19/FMD2/issues/475
Until someone able to fix it, the website will stay broken.
