### ISSUE TITLE
[bug] JavaScript for asurascans.com

### ISSUE THREAD

**Issue by Qizmo** [dazedcat19/FMD2#528]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 Home

**Describe the bug**
When trying to load manga from https://asurascans.com/, it is always blank with "Title: Please turn JavaScript on and reload the page."

**To Reproduce**
1. Go to 'asurascans.com'
2. Click on 'any manga'
3. See error

**Expected behavior**

**Screenshots**
<a href="https://ibb.co/SJ9BMYD"><img src="https://i.ibb.co/x3R6B9K/Delete.png" alt="Delete" border="0"></a>

**Additional context**

**Comment by Slasar41** [comment]
Use cookies workaround. https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964

**Comment by Qizmo** [comment]
Still doesn't work.

<a href="https://ibb.co/6WXgvFV"><img src="https://i.ibb.co/CHPhJQN/Delete1.png" alt="Delete1" border="0"></a>

<a href="https://ibb.co/KVxXts9"><img src="https://i.ibb.co/9yHNx4q/Delete2.png" alt="Delete2" border="0"></a>

The loading of manga is still the same as in the first picture.
