### ISSUE TITLE
Support for MangaDex v5's MVP API 

### ISSUE THREAD

**Issue by 81322068** [dazedcat19/FMD2#529]
As we know MangaDex went down for a long time. Today they have made their MangaDex v5's API open beta live to the public, so if possible I would want support for that and be able to access it thorough FMD's interface

**Additional context**
API Documentation: [here](https://api.mangadex.org/docs.html)
Commits in tachiyomi-extension if it helps: [here](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/715bdcccc147a77ca09091ab239325ba2879c87c) and [here](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/9a45dc2f8e1a390e4d445114ad7f9d2a5569b3c1)

**Comment by Slasar41** [comment]
Yeah, just wait for it.
![image](https://user-images.githubusercontent.com/28888646/117284157-bf1ffb80-ae90-11eb-9e6a-8b209c7a6be9.png)

**Comment by L0Ck3D-cmd** [comment]
\o/ thanks so much, Slasar41. I will waiting \o/ (i'm using FMD2)

**Comment by Slasar41** [comment]
The API is still not final.
![image](https://user-images.githubusercontent.com/28888646/120694655-abd66f00-c4d4-11eb-83af-b0b7f23548d0.png)

**Comment by GlassedSilver** [comment]
The site is back online, not sure if the API is now at a more established point as well?

That being said, if you‘re waiting for them to be done with it, you might wait forever, since all they promise is that if there’s breaking changes they will notify in advance, which I think is reasonable given that no software ever truly is done and perfect - except for our beloved Hello World of course. /s ;)

**Comment by Slasar41** [comment]
Update:
![image](https://user-images.githubusercontent.com/28888646/121066171-ca4daa80-c7f3-11eb-9c45-ea0683072734.png)

**Comment by Slasar41** [comment]
Update:
Tested with FMD1 and download is functional.
![image](https://user-images.githubusercontent.com/28888646/121754097-f0e64b00-cb3d-11eb-9fa3-350fef940d92.png)
![image](https://user-images.githubusercontent.com/28888646/121754157-13786400-cb3e-11eb-8cb1-28e5638a8d2d.png)
Old favorites are still not working as the data need to be migrated first.
SDXC is working on it.

**Comment by GlassedSilver** [comment]
@Slasar41 good taste in manga, mate :)

**Comment by ivanm48** [comment]
I tried downloading with FMD1 and it doesn't work, it just shows an empty chapter list for any manga I click.

When I try FMD2 it shows an error message and that I should check my internet connection.

**Comment by Slasar41** [comment]
The module has been finished for FMD1.
He'll port it to FMD2 and I'll merge it.

**Comment by Slasar41** [comment]
I'll update the module.
The first check of the favorites will eventually find all chapters which you need to "download" (simply add the found new chapters to downloads and delete the jobs afterwards).
For anyone that was up-to-date when MD went down, it should mostly be safe to add and delete the found new chapters.

**Comment by frerouche** [comment]
Just checking to be sure, but is it normal that FMD2 still uses the old manga ID scheme in manga info?
The picture above shows it's using the new ID scheme for FMD1.

**Comment by Slasar41** [comment]
Yes, the old favorites data still have the old manga id.
That's where the mapping function come.
FMD will detect the old manga id and request to the API to provide the new manga id and save it to `\userdata\mangadex_v5_mapping.txt`.
If you add a new favorite, FMD will save the new manga id and the mapping function will not be used.

**Comment by Sakurahime08** [comment]
> 
> 
> I'll update the module.
> The first check of the favorites will eventually find all chapters which you need to "download" (simply add the found new chapters to downloads and delete the jobs afterwards).
> For anyone that was up-to-date when MD went down, it should mostly be safe to add and delete the found new chapters.

Question - Will it be permanently like this? I'm not really sure which in my list is not up to date. I've relocated a lot of folders expecting only the new uploads will be downloaded. Is there no chance of retrieving the data before? 😅 just curious 

Thank you!

**Comment by SDXC** [comment]
> Question - Will it be permanently like this? I'm not really sure which in my list is not up to date. I've relocated a lot of folders expecting only the new uploads will be downloaded. Is there no chance of retrieving the data before? sweat_smile just curious

FMD stores the chapter links to compare if a chapter already has been downloaded. Because FMD uses a new URL format, this comparison doesn't work anymore and flags all chapters as new. BUT only on the first check.

What you can do in a roundabout way: Use a DB tool to get the links of the downloaded chapters and use the legacy endpoint of the MD API to retrieve the new ID and safe the new URL in the database. But this is much more effort than it's actually worth.

**Comment by Sakurahime08** [comment]
Thanks! How about existing Mangadex tasks paused in the tasklist before MD went down? I have some titles to be resumed for download but won't resume when prompted with new MD. Is there a way to fix it? Thanks!

**Comment by Slasar41** [comment]
@Sakurahime08 Try use this [script](https://github.com/elliotcraft79/fmd_mangadex_converter).

**Comment by Sakurahime08** [comment]
> 
> 
> @Sakurahime08 Try use this [script](https://github.com/elliotcraft79/fmd_mangadex_converter).

Thank you! But it didn't work - previous tasks won't resume. But new ones are working properly. Any other fixes?

**Comment by Sakurahime08** [comment]
> 
> 
> @Sakurahime08 Try use this [script](https://github.com/elliotcraft79/fmd_mangadex_converter).


Is there an alternative way to fix this? Thanks! The script is not working for me @Slasar41
