### ISSUE TITLE
Favorites from FMD1

### ISSUE THREAD

**Issue by leoteesh** [dazedcat19/FMD2#53]
Hi,

Could you please help me in converting my favorites and history from the previous FMD1 to this one?
i have tried to use the converter, but it did not work. I keep getting blanks. 
I have also tried to copy and paste the "works" folder but that also did not work/

![image](https://user-images.githubusercontent.com/21075197/86943650-9c249e00-c13e-11ea-8315-0034a27d5844.png)
 i have tried again and now getting the below message

![image](https://user-images.githubusercontent.com/21075197/86949118-1c023680-c146-11ea-9b78-9d41368bdbeb.png)

Any help will be much appreciated.

Many thanks

**Comment by Slasar41** [comment]
- Close FMD1
- Place converter.exe and modules.txt in FMD1 folder
- Run converter.exe
- There will be a new folder called `converted`
- Copy the inside of that folder to FMD2 folder

**Comment by leoteesh** [comment]
Thank you - i managed to get my favorites but not the download history. Is there a way to also get this?

**Comment by dazedcat19** [comment]
Files below should be present if you follow above instruction correctly.
```
settings.json (main fmd settings)
downloads.db (download list)
favorites.db (favorite list)
downloadedchapters.db (downloaded chapters history)
```
