### ISSUE TITLE
Can not load WebP codec library

### ISSUE THREAD

**Issue by Ksetrar** [dazedcat19/FMD2#532]
I just downloaded FMD and it is showing this error
`Unhandled exception!
Application       : Free Manga Downloader
Version           : 2.0.31.0
Product Version   : Win64
Host Machine      : Windows 7 64-bit Build 7601
FPC Version       : 3.3.1
LCL Version       : 2.1.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2021/03/21 14:33:22
Path              : C:\Users\User\Desktop\fmd_2.0.31.0_x86_64-win64\fmd.exe
Process ID        : 5448
MainThread ID     : 5840
Thread ID         : 5840
Time              : 08-05-2021 19:59:56.816
Exception Object  : 0000000003369180
Exception Class   : EInOutError
Message           : Can not load WebP codec library "C:\Users\User\Desktop\fmd_2.0.31.0_x86_64-win64\libwebp.dll". Check your installation.
`

**Comment by Slasar41** [comment]
Try replace it with [this](https://github.com/dazedcat19/FMD2/blob/master/dist/x86_64-win64/libwebp.dll).

**Comment by Ksetrar** [comment]
Works fine now
