### ISSUE TITLE
[feature request] Persistently highlight completed series in favorites

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#54]
**Is your feature request related to a problem? Please describe.**
It's currently nightmarish trying to remove completed series from favorites, since you only see status during chapter scanning.

**Describe the solution you'd like**
Make the highlight stays until the next update.

**Comment by dazedcat19** [comment]
I actually forgot about adding this field. But it need to change the database once again, because there's no such field. And I'm reluctant to add such soon to be deprecated code. that only run one time only.
