### ISSUE TITLE
[bug-website module] Sekaikomik

### ISSUE THREAD

**Issue by manhwalover** [dazedcat19/FMD2#543]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7 Pro, 64-bit

**Describe the bug**
Failed to download comics.
On the tab **manga info** there are no problems, all chapters appear. But when the download fails everything, only downloading empty chapter folders.
I use ISP ICON+ (http://www.iconpln.co.id/), because it fails I also use the Freegate proxy tool (http://dit-inc.us/freegate.html).
I try to access the website using a web browser, everything works normally, all images appear.

**Additional context**
![image](https://user-images.githubusercontent.com/79884368/118747030-73ebec80-b883-11eb-8aeb-c7ac951c019c.png)
![image](https://user-images.githubusercontent.com/79884368/118747208-c88f6780-b883-11eb-8777-df319e114e9d.png)
![image](https://user-images.githubusercontent.com/79884368/118747243-d80eb080-b883-11eb-86e5-25134ac94455.png)

**Log**
[fmd.log](https://github.com/dazedcat19/FMD2/files/6505473/fmd.log)

**Comment by Slasar41** [comment]
You need to do cookies workaround: https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964.
But instead of open any title, you need to open any chapter.
