### ISSUE TITLE
[website module request] hentaimimi

### ISSUE THREAD

**Issue by rakhmat12** [dazedcat19/FMD2#555]
Name: HentaiMimi
**Root URL:**https://hentaimimi.com/
**Directory list URL:**https://hentaimimi.com/
**Example manga info URL:**https://hentaimimi.com/view/7716
**Example chapter URL:**https://hentaimimi.com/view/7716#lg=1&slide=0
Languages
English

**Comment by Slasar41** [comment]
Already supported.

**Comment by PainMa** [comment]
I have a question about that website, i dont know if thats the right place to ask tho :/ 
I use google chrome and when I look at the pages its way to big for my screen, is there a way to crop the pages or atleast scroll down each page without my mouse wheel? 
Sorry for my bad english and for probably asking in the wrong thread.
