### ISSUE TITLE
[bug-website module] Manganelo, now manganato, borked favorites list.

### ISSUE THREAD

**Issue by alatnet** [dazedcat19/FMD2#558]
**Prerequisite**
- [x] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Win 10

**Describe the bug**
Looks like when manganelo changed to manganato, it borked my favorites list.  Seems that they had changed where everything is and the format of the url.  instead of it being "/manga/\<wierd id\>" or "/manga/\<title\>" or even "/manga/\<wierd id\>/\<title\>" it's now just "/manga-\<wierd id\>". 
Just letting you know about this as I have to go through my entire favorite list in a db editor and fix them...  thank god for some scripting.

**Comment by alatnet** [comment]
Bit of a powershell script to, hopefully, pull all the manga from the site, can easily import it into a sqlite database if needed:

> Write-Host "Getting Page: 1"
> $obj = ((Invoke-WebRequest -Uri 'https://manganato.com/genre-all').Links | Where-Object {$_.class -like "genres-item-name*"})
> [System.Collections.ArrayList]$obj2=@()
> 
> foreach($html in $obj){
> 	$obj2.Add(
> 		[pscustomobject]@{title=$html.title; link=$html.href; lpath=([System.Uri]$html.href).LocalPath; apath=([System.Uri]$html.href).AbsolutePath}
> 	)
> }
> 
> for ($i=2;  $i -le 1239; $i++){
>     Write-Host "Getting Page: $i"
> 	$obj = ((Invoke-WebRequest -Uri ('https://manganato.com/genre-all/'+$i)).Links | Where-Object {$_.class -like "genres-item-name*"})
> 	foreach($html in $obj){
> 		$obj2.Add(
> 			[pscustomobject]@{title=$html.title; link=$html.href; lpath=([System.Uri]$html.href).LocalPath; apath=([System.Uri]$html.href).AbsolutePath}
> 		)
> 	}
> }
> 
> $obj2 | Export-Csv -Path '.\export.csv'
> $obj2 | Sort-Object -Property 'title' | Export-Csv -Path '.\sorted.csv'

Edit: updated script with local and absolute path separated from the link.
Edit2: just noticed that the script doesnt separate the local and absolute path from the first page. XD

**Comment by alatnet** [comment]
So after properly importing the csv file from the script above into the favorites database temporarily, found and modified a sql script to automatically update all of my favorites that are manganato.

> UPDATE favorites
> SET
>     (link) = (SELECT export2.lpath FROM export2 WHERE LOWER(export2.title) = LOWER(favorites.title) AND favorites.moduleid='fa8bb4d1ceea4c8fa0e98c00755f95d4')
> WHERE
>     EXISTS (
>        SELECT *
>        FROM export2
>        WHERE LOWER(export2.title) = LOWER(favorites.title) AND favorites.moduleid='fa8bb4d1ceea4c8fa0e98c00755f95d4'
>    )

modify where necessary.  module id might not be the right one.
not all entries will be updated, though it gets most of them.

EDIT: this will also work with the downloads database and fix any chapters that didnt download.

**Comment by Slasar41** [comment]
Thanks for the script.
I'll leave it for a while so other users can use it too.

**Comment by alatnet** [comment]
Well... looks like some of my favorites are borked again... looks like they are moving some to readmanganato.com.
Im guessing the module might need to do a dual check on manganato.com and readmanganato.com to see which one will return a result.

Edit: looks like it's there in the module. But gonna take a look at it.
https://github.com/dazedcat19/FMD2/blob/master/lua/modules/MangaKakalot.lua

**Comment by Slasar41** [comment]
I just replace all `manganato.com` url to `readmanganato.com` url.
The manga page will still load fine after replacing it.
Maybe you need to do that to your script too.

**Comment by alatnet** [comment]
looks like it, funny thing is, downloads work fine. XD
just got the script update and favorites are working again.  fast work man.

**Comment by 7godeohs** [comment]
I was looking into this issue earlier, wondering if I'd need to migrate my favorites once again, when I came upon the issue listed in the issue section, and say that you had already been working on it, and had a resolution.   I just wanted to say that the community and what you all contribute to it is amazing.

Thanks for all the work you put into this great program.

**Comment by millenopan** [comment]
hello, was still a bit confused exactly what to do in order to fix the favorites list here, and was wondering if this was something that's going to be updated soon too, thanks for everyone's work!

**Comment by alatnet** [comment]
@millenopan So, to fix your favorites list like i have, i run the powershell script to pull all of the manga's that manganato has listed in their website under "https://manganato.com/genre-all", may have to adjust the for loop depending on how many "pages" of manga that page has.  The script creates two csv files, an unsorted and sorted list of all the mangas with columns of title, link, lpath, and apath.  you can view that in excel if you'd like to see what the data is.
afterwards, i used [SQLite Database Browser](https://sqlitebrowser.org/) to open the "favorites.db" file that is in the "userdata" folder within the free manga downloader folder.
with the database open, i import one of the csv file (doesnt matter which, both contain the same data and the database doesnt care which) into the database with the option "Column names in the first line" checked.
then i click on the "Execute SQL" tab and copy and paste the sql script in the second post into there adjusting things like "export2" and the module id so as to find the right data and to not mangle other favorites.  click play, wait a while, and it should fix manganato favorites.
finally i run "drop table export;" to remove the imported csv file (primaraly to clear space and to make it "normal") and click on the "Write Changes" button at the top.

**Comment by Tmp341** [comment]
Same happened on another site before (forgot which one), i manually changed all with SQLite Database Browser.

**Comment by Nimesh-Bhana** [comment]
Just wanted to know @alatnet what did you mean by things other then "export2" and what is it meant to be. Thanks in advance.

**Comment by alatnet** [comment]
@Nimesh-Bhana what i mean by other than "export2" is what the table is named when you import the csv file that was created using the powershell script.
usually when you use SQLite Database Browser, it imports csv file into a table that has the same name as the filename of the csv file.  In this case, the powershell script creates two files named "export.csv" and "sorted.csv" that when imported using SQLite Database Browser the table would be named "export" or "sorted" depending on which you import, unless you change the table name.

**Comment by Slasar41** [comment]
I'll close this.
