### ISSUE TITLE
[bug-website module] Manganato manga list

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD2#559]
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 7-64 bit 

**Describe the bug**
Can't access manga info from the new manganato. I downloaded the list from server and it's still not working.
![image](https://user-images.githubusercontent.com/24958560/120032019-6a991780-c01b-11eb-83d4-c32cb302f510.png)

**Comment by Slasar41** [comment]
I've updated the manga list. you can redownload it.

**Comment by Souravi785** [comment]
@Slasar41 Can you check this? Manganato url change for some mangas

![image](https://user-images.githubusercontent.com/24958560/120085121-44e14080-c0f7-11eb-8141-7cbfac37b631.png)
![image](https://user-images.githubusercontent.com/24958560/120085144-6e9a6780-c0f7-11eb-82c9-dae4b11a7169.png)

**Comment by Slasar41** [comment]
Looks like I need to force just use `readmanganato.com` url instead of `manganato.com` for the module.
The manga page with `manganato.com` url can be renamed to `readmanganato.com` url and it's still working.

**Comment by Slasar41** [comment]
@Souravi785 Should be fixed. Redownload the manga list.
