### ISSUE TITLE
[bug-website module] ManhuaID

### ISSUE THREAD

**Issue by MIRVOUS** [dazedcat19/FMD2#566]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win-7 32

**Describe the bug**
Module not work anymore

**Additional context**
just shown this, without chapter off course
![manhuaid](https://user-images.githubusercontent.com/45929526/120112291-6990f300-c19f-11eb-9f45-36369bd726f8.PNG)

**Comment by Slasar41** [comment]
There's no series with that title in the website. Copying the link from browser to FMD still works.
Meaning the database is already old, can't even access the manga list in the website to get the new list <https://manhuaid.com/lists>.
I'll fix the manga info and download.
