### ISSUE TITLE
[Website module report] Manhuas.net unable to list or download chapters

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD2#57]
**Prerequisite**
- [x ] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
unable to list or download chapters on manhuas.net

**Comment by Slasar41** [comment]
@dazedcat19 This issue only happen on FMD2. Works fine on FMD1.
I don't know where's the issue.
