### ISSUE TITLE
fixed, not a FMD2 issue - [bug-website module] LoveHug fails to download a chapter [i'm going to close in a couple of hours]

### ISSUE THREAD

**Issue by GDXN** [dazedcat19/FMD2#570]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [ ] This is not temporary server issue.

This happens in LoveHug with the chapter 56 `https://lovehug.net/1473/53394/` from Isekai wa Smartphone to Tomo ni `https://lovehug.net/1473/`, I think that is related to image links as the images are hosted in: `https://ihlv1.xyz` where in another chapter that I tested that downloaded ok they are hosted in `https://s2.ihlv1.xyz`

PD. There can be more chapter affected and this issue is semi-permanent as sometimes after a couple days the images can be served from another server and them they work.

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/120278328-58e79680-c2df-11eb-9f03-fd2e2814787d.png)
But the manga title is missing.

**Comment by GDXN** [comment]
The bug is weirder than I thought:
My system is W10
app dir: `D:\[APP]\fmd_W64\`
folder save: `downloads\Isekai wa Smartphone to Tomo ni [RAW]` 
chapter 56 of Isekai wa Smartphone to Tomo ni fails to download to `D:\[APP]\fmd_W64\downloads\Isekai wa Smartphone to Tomo ni [RAW]`
But if I alter the patch preventing `]` as last character in that same exact position in any way it works making it like this full download patchs:
`D:\[APP]\fmd_W64\downloads\Isekai wa Smartphone to Tomo ni [RAWa
D:\[APP]\fmd_W64\downloads\Isekai wa Smartphone to Tomo ni [RAW]a
D:\[APP]\fmd_W64\downloads\Isekai wa Smartphone to Tomo ni [RAW
D:\[APP]\fmd_W64a\downloads\Isekai wa Smartphone to Tomo ni [RAW]
D:\[APP]\fmd_W6\downloads\Isekai wa Smartphone to Tomo ni [RAW]`
this hapens where the original file name in the server is like `eeb8d857480840b714ad49dee317cd73039.jpg`
but if its like `0325_6012247ae291c.jpg` it dosn't happen

**Comment by Slasar41** [comment]
Is there something in the log?

**Comment by GDXN** [comment]
Investigating more it was not FMD2 caused, the culprit was the antivirus (Avast) and adding an exception fixed it (folder exception). This is one of those WTF issues where the culprit is not obvious and all of the initial clues point in other direction.

 Slasar41, Thanks for telling that in your end it worked as it make me extend the issue evaluation procedure. Can you add to the report wizard to try to run FMD2 with the antivirus disabled to evaluate the issue?

 Slasar41, I'm going to close the issue in a couple of ours if you don't closed it, I don't close immediately in case you want to answer.

**Comment by GDXN** [comment]
The log was disabled and now I tried to reproduce enabling the log and disabling the antivirus exception and it worked... I'm going to be on the watch for if the issue reappears.

**Comment by Slasar41** [comment]
So now the antivirus isn't at fault anymore and FMD still can store the manga just fine?

I'll close the issue as it's not FMD issue.
