### ISSUE TITLE
[bug]NineMangaES

### ISSUE THREAD

**Issue by akir42019** [dazedcat19/FMD2#574]
Prerequisite
Name: NineMangaES
Root URL: https://es.ninemanga.com
Directory list URL: https://es.ninemanga.com/category/
Example manga info URL: https://es.ninemanga.com/manga/Kumo+Desu+ga-+Nani+ka%3F.html
Example chapter URL: https://www.gardenmanage.com/statuses/4930881.html

System information
Windows 10 Pro 21H1

Describe the bug
It does not download or load

Additional
![Sin título NineMangaES](https://user-images.githubusercontent.com/51466748/120381044-f21ea900-c2ef-11eb-93e2-d6cb31c8bd09.jpg)

**Comment by Slasar41** [comment]
You should't put too many connection number for updating manga list.
I've updated the manga list to server so you can use that instead.
