### ISSUE TITLE
[website request] comichub

### ISSUE THREAD

**Issue by joeb2000** [dazedcat19/FMD2#575]
I have to keep manually adding it back to madara.lua every time there is an update. So I thought I could put in a simple request to just have it added permanently.

The website is https://comichub.net

I have no idea how you all determine the website id string, so I just copied one and changed a number in it. 
Everything works perfectly when I just add this line in my madara.lua under the "cat = English" section.

AddWebsiteModule('76b33c241c0d44a6b4a5b8dd86ec7752', 'ComicHub', 'https://comichub.net')

**Comment by Slasar41** [comment]
Redirected to https://comiconline.org so I'll add that.
