### ISSUE TITLE
[bug]NineMangaES

### ISSUE THREAD

**Issue by akir42019** [dazedcat19/FMD2#576]
Prerequisite
Name: NineMangaES
Root URL: https://es.ninemanga.com
Directory list URL: https://es.ninemanga.com/category/
Example manga info URL: https://es.ninemanga.com/manga/Kumo+Desu+ga-+Nani+ka%3F.html
Example chapter URL: https://www.gardenmanage.com/statuses/4930881.html

System information
Windows 10 Pro 21H1

Describe the bug
It does not download or load.
Using the updated manga list from the server.

Additional
![Sin título NineMangaES](https://user-images.githubusercontent.com/51466748/120536085-bba96280-c3b1-11eb-9613-14686598ab41.jpg)
![Sin título NineMangaES_b](https://user-images.githubusercontent.com/51466748/120536123-c532ca80-c3b1-11eb-8b96-93a1438bbea1.jpg)

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/120694293-39fe2580-c4d4-11eb-9fbf-ffed85655c9c.png)
![image](https://user-images.githubusercontent.com/28888646/120694395-58642100-c4d4-11eb-9faa-0b0dcfca276e.png)
Maybe you enabled advanced website options for NineMangaES?

**Comment by akir42019** [comment]
Thanks for the help.
I managed to correct my problem.
Delete the files "lua.json, lua_repo.json" from the "userdata" folder and update the lua modules. 
![Sin título2](https://user-images.githubusercontent.com/51466748/120865889-e1bf3600-c55c-11eb-928d-aa2018ec39e0.jpg)
