### ISSUE TITLE
[bug] Toonily - Title & Chapters missing

### ISSUE THREAD

**Issue by Tyranical** [dazedcat19/FMD2#578]
**Prerequisite**
- [Y] I'm using the latest version.
- [Y] All website modules are up to date.

- [Y] This is not temporary server issue.

**System information**
W10

**Describe the bug**
The display where chapters should appear is empty and the titles are replaced by N/A. I have set both the user agent the cookies sent from my browser and pasted them into the Advanced entry for the site. It can still get the other information fine, authors, artists, genres and summary all appear.

**Comment by Darthagnon** [comment]
Is this ```https://toonily [dot] com``` (NSFW)? I haven't had any luck with that website. EDIT: I've requested support in HakuNeko (https://github.com/manga-download/hakuneko/issues/3944)

**Comment by Slasar41** [comment]
Try [this](https://github.com/dazedcat19/FMD2/issues/736#issuecomment-926173134).
