### ISSUE TITLE
[bug] Converter does not work and I am unable to update

### ISSUE THREAD

**Issue by TimidScript** [dazedcat19/FMD2#581]
**System information**
Windows 10x64bit

**Describe the bug**
There are two errors. First one is unable to import old settings from FMD1 to FMD2 and second unable to udpate. 

Issue 1)
Tried to convert old FMD to new FMD2 using converter_x86_64-win64 and then tried converter_1386-win32. It gives me error. 

For win32 version I get:
`error: Can not load SQLite client library "R:\FMD\sqlite3.dll". Check your installation.`

For win64 version I get:
`error: TSQLite3Connection : near "COLUMN": syntax error`

It creates some converted data, I copy the content of converted directory and then run FMD2 but my download history is completely missing. If I look at "downloadedchapters.db" its 172KB big and it seems to have some content inside. 

Issue 2)
Nothing is being updated. It does not update at all. I just downloaded latest version of FMD2 and I get failure when it updates. Example:

```
modules/MangaZuki.lua FAILED*
modules/MangaZukiRaws.lua FAILED*
modules/ManHuaGui.lua FAILED*
modules/ManhuaID.lua FAILED*
modules/ManHuaTai.lua FAILED*
modules/ManhwasMen.lua FAILED*
modules/MerakiScans.lua FAILED*
modules/MethodScans.lua FAILED*
```

**Comment by Slasar41** [comment]
Which version is the FMD1?

If you see FAILED status, just press yes and FMD will download them.
You can see the progress at Options -> Websites -> Modules.

**Comment by TimidScript** [comment]
The update works, it seems I had to leave it on for a lot longer.

FMD1 Version is 0.9.158.0. Tried again and it still fails to import from FMD1.

**Comment by Slasar41** [comment]
That version is too old.
You need to download the latest FMD1 from [here](https://github.com/fmd-project-team/FMD/releases), copy `works` folder from v0.9.158 to v1.3.3, and then run the converter.

**Comment by TimidScript** [comment]
Thank you, it works. Just let you know that copying the "works" folder alone didn't seem to work. I had to override the old version 0.9 content with the 1.3 and then converter worked.

**Comment by Slasar41** [comment]
Noted.
Glad it's worked.
