### ISSUE TITLE
[bug-website module] Mangasee and Mangadex issues.

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD2#582]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**Describe the bug**
Mangasee and Mangadex official website working properly but FMD2 unable to get any manga information from it.

![Untitled](https://user-images.githubusercontent.com/40983245/121097173-24fffa00-c826-11eb-9cbe-7fee5a588697.png)

**Comment by azraei97** [comment]
> Checked the logs on my install and it seems like it's cloudflare blocking to the site. Getting error 1020

I don't think it cloudflare issues because adding cookies to FMD was not work. Tachiyomi also has same issues but they update it few hours ago. Now it work again in Tachiyomi.

FMD2 still no update for MangaSee

**Comment by Slasar41** [comment]
MangaSee issue is the same like ReaperScan issue.
Looks like to fix it need to change some code in the FMD pascal code which I don't have the knowledge.
The main dev is already missing for almost a year.

For MangaDex see this issue: https://github.com/dazedcat19/FMD2/issues/529.

**Comment by azraei97** [comment]
@SDXC unable to fix mangasee? I always download manga using my computer. Leave it few hours then transfer it to my phone due to slow internet connection. Download using Tachiyomi in phone just gonna wasting my phone battery and storage.

**Comment by formigao** [comment]
domain changed too https://mangasee123.com/

dont know if its related but this domain stoped working at the same time FMD did : https://mangaseeonline.us/

**Comment by Slasar41** [comment]
@azraei97 SDXC just want to create a new version of FMD using different language.
![Screenshot_20210609-152538800 (1)](https://user-images.githubusercontent.com/28888646/121402425-129bd280-c984-11eb-97e5-6c592954364b.jpg)

**Comment by JLChamberlain** [comment]
Hope we get a module update for MangaSee soon as most series I have listed as favourite is from MangaSee.

**Comment by molitar** [comment]
> 
> 
> Hope we get a module update for MangaSee soon as most series I have listed as favourite is from MangaSee.

In Discord saying that it's the FMD code itself so it needs a rewrite and that it is not a module. So far now if you want MangaSee looks like an app like Tachiyomi on Android is it for now.

**Comment by formigao** [comment]
> > Hope we get a module update for MangaSee soon as most series I have listed as favourite is from MangaSee.
> 
> In Discord saying that it's the FMD code itself so it needs a rewrite and that it is not a module. So far now if you want MangaSee looks like an app like Tachiyomi on Android is it for now.

what discord? looks like fmd really needs to be redone... this problem is spreading like cancer... everyday a new site start having the same problem....

**Comment by Slasar41** [comment]
MangaSee is working again for now.

**Comment by Slasar41** [comment]
I'll close it.
MangaDex already has an open issue.
If the issue occur again, please create an issue just for MangaSee.
