### ISSUE TITLE
[bug-HitomiLa] incomplete downloads

### ISSUE THREAD

**Issue by Dgraid12** [dazedcat19/FMD2#583]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7 ULTIMATE SP1

**Describe the bug**
Manga are not downloaded in full

**Screenshots**
![image](https://user-images.githubusercontent.com/53473707/121251211-9ebed480-c874-11eb-958c-9e1f0c30ce94.png)

**Additional context**
I did the test with several titles and only 1 was completely downloaded

**Comment by Rhisk** [comment]
i can confirm this too.

**Comment by Slasar41** [comment]
Please provide a link for the failed one.

**Comment by Dgraid12** [comment]
> Please provide a link for the failed one.

this worked: 
https://hitomi.la/manga/suteki-na-kanojo-espa%C3%B1ol-855398.html

these 2 didn't work:
https://hitomi.la/doujinshi/bache-ni-bacchiri-omakase!---%C2%A1d%C3%A9jaselo-todo-a-bache!-espa%C3%B1ol-1927497.html
https://hitomi.la/doujinshi/batsu-game-de-yankee-onna-ni-kokuttemita-espa%C3%B1ol-1103570.html
