### ISSUE TITLE
Unable to download from mangasee

### ISSUE THREAD

**Issue by ivanm48** [dazedcat19/FMD2#589]
Prerequisite

 I'm using the latest version.
 All website modules are up to date.
 This is not temporary server issue.

Describe the bug
Mangasee official website working properly but FMD2 unable to get any manga information from it.

When I click on any series it doesn't show the list of chapters, the series description or the cover, it just shows an error message: 
"Cannot get manga info. Please check your internet connection and try again"

The website works just fine when I open it through my browser and it doesn't require any captcha.

**Comment by HiP1** [comment]
before it was because there was a new cloudflare challenge, like for Batoto.
but now, we get a "17:34:53:311 WebsitBypass[cloudflare]: Cloudflare has blocked this request (Code 1020 Detected)
https://mangasee123.com/manga/Ayakashi-Triangle"
seems like cloudflare is blocking our requests.

**Comment by ivanm48** [comment]
> before it was because there was a new cloudflare challenge, like for Batoto.
> but now, we get a "17:34:53:311 WebsitBypass[cloudflare]: Cloudflare has blocked this request (Code 1020 Detected)
> https://mangasee123.com/manga/Ayakashi-Triangle"
> seems like cloudflare is blocking our requests.


That's strange because I can go to the site just fine, doesn't show anything out of ordinary like Cloudfare but when I try to open some series in FMD2 it's like it doesn't exist.

**Comment by Slasar41** [comment]
I talk a bit in this issue: https://github.com/dazedcat19/FMD2/issues/582#issuecomment-857088425

**Comment by HiP1** [comment]
> I talk a bit in this issue: [#582 (comment)](https://github.com/dazedcat19/FMD2/issues/582#issuecomment-857088425)

I don't think it's the same. I often checked the log, and it was always about a new cloudflare challenge before. And now it is immediately blocked by cloudflare. Something changed after it was resolved. It lasted a day 😁

**Comment by Slasar41** [comment]
Nah it's the same.
The owner made some changes on the website that made the request from FMD get blocked.
And FMD got cloudflare 1020 page instead of website page.
Some code in FMD need to be changed so cloudflare will accept FMD request again.

More website will be like this and soon FMD won't be usable again.

**Comment by HiP1** [comment]
> Nah it's the same.
> The owner made some changes on the website that made the request from FMD get blocked.
> And FMD got cloudflare 1020 page instead of website page.
> Some code in FMD need to be changed so cloudflare will accept FMD request again.
> 
> More website will be like this and soon FMD won't be usable again.

Interesting. How do they recognize FMD even with the user agent changed? Is there a specific item in FMD requests?

**Comment by molitar** [comment]
> 
> 
> > Nah it's the same.
> > The owner made some changes on the website that made the request from FMD get blocked.
> > And FMD got cloudflare 1020 page instead of website page.
> > Some code in FMD need to be changed so cloudflare will accept FMD request again.
> > More website will be like this and soon FMD won't be usable again.
> 
> Interesting. How do they recognize FMD even with the user agent changed? Is there a specific item in FMD requests?

I wonder about the same thing.  Evidently they need to do a rewrite of something in FMD but it still has not been done. Right now I would imagine other sites would request the same thing if we do not get a new Release soon.  If this happens it will be time to move to a new downloader that is updated more often as this one has not had a new exe in quite some time now.

**Comment by JLChamberlain** [comment]
Does anyone know of an alternative for MangaSee for SJ titles? I've currently added the series with MangaPlus as the source but all the double-page spreads are split on MangaPlus whereas the ones that got uploaded to the MangaSee have the pages joined.

**Comment by molitar** [comment]
> 
> 
> Does anyone know of an alternative for MangaSee for SJ titles? I've currently added the series with MangaPlus as the source but all the double-page spreads are split on MangaPlus whereas the ones that got uploaded to the MangaSee have the pages joined.

Nope we just got to hope the sites that was using it as there source realizes and stops using them.  Too many other sites was ripping off of MangaSee so that is why they started doing that crap.

**Comment by JLChamberlain** [comment]
For those looking for an alternative just use [Manga4Life](https://manga4life.com). Just search MangaLife in the listed website and select it, like MangaSee it uploads rips from MangaPlus and has all double-page spreads already joined.
