### ISSUE TITLE
[bug-website module] nhattruyentranh.com and nettruyentop.com

### ISSUE THREAD

**Issue by DejaSentj** [dazedcat19/FMD2#592]
**Describe the bug**
Tried to download Manga from this website but the error when download some a lot chapters and it was mostly come from the host 

http://truyentemp.com

This chapter
http://www.nettruyentop.com/truyen-tranh/chi-ton-chu-thien/chap-2/273194
http://nhattruyentranh.com/truyen-tranh/chi-ton-chu-thien/chap-2/273194
host 
http://truyentemp.com/data/images/13885/273194/001.jpg?data=net

can you solve this problem

thanks

**Comment by Slasar41** [comment]
It should be fine after changing the GetPageNumber function in `\lua\modules\TruyenChon.lua` to be like this:
```
function GetPageNumber()
	TASK.PageLinks.Clear()
	if HTTP.GET(MaybeFillHost(MODULE.RootURL, URL)) then
		local x = CreateTXQuery(HTTP.Document)
		local v for v in x.XPath('//div[@class="page-chapter"]/img/@data-original').Get() do
			TASK.PageLinks.Add(v.ToString():gsub('^//', 'https://'))
		end
	else
		return false
	end
	return true
end
```
But FMD still won't download it...

**Comment by DejaSentj** [comment]
Look like it has been protect by CloudFlare because 

when you click on this link it will not gonna load the file because the "access denied"
http://truyentemp.com/data/images/13885/273194/002.jpg?data=nht

but if you load the website and open the image in new tab and when you come back to that link it will be available to access this time. 
http://nhattruyentranh.com/truyen-tranh/chi-ton-chu-thien/chap-2/273194

Load the whole chapter and has to open single image in new tab to get the access from Cloudflare for all the file

I really hope to can do something about this but due to lack of experience so... can you help here?

**Comment by Slasar41** [comment]
Found the issue.
I'm trying to add `https://` to the image urls instead of just `http://`.
