### ISSUE TITLE
[bug] hiperdex.com yesterday was hiperdex2.com today is hiperdex.com again

### ISSUE THREAD

**Issue by jjrc28** [dazedcat19/FMD2#596]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jjrc28** [comment]
hiperdex.com has problems, thank you por your help.

**Comment by bloodsign** [comment]
Ah dammit, you're right. 

For now you go to your fdm folder:
fdm_2.0.30.0_x86_64-win64>lua>modules

Look for a file "Madara.lua" and find and change hiperdex2.com back to hiperdex.com

**Comment by bloodsign** [comment]
@Slasar41  
Sorry man, it seems hiperdex2 went back to hiperdex again. 
Not sure though if it's gonna stay that way or they are gonna go back and forth.

**Comment by jjrc28** [comment]
thank you
