### ISSUE TITLE
[bug-website module] Mangadex Favorites status

### ISSUE THREAD

**Issue by LetMeGitDat** [dazedcat19/FMD2#599]
I know Mangadex was recently fixed but all my favorites are now downloading from chapter 1 rather than new updates only. This is a massive problem for larger collections. Is there any way to reconcile "Completed" downloads with the new ones?

Example
The last downloaded chapter was: chapter 831

Instead of downloading from c832 to current

It starts from chapter 1 to current... FOR ALL favorites

**Comment by Slasar41** [comment]
See: https://github.com/dazedcat19/FMD2/issues/529#issuecomment-862720097
