### ISSUE TITLE
[bug] 8Muses not exist in website list

### ISSUE THREAD

**Issue by ghost** [dazedcat19/FMD2#60]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

Updated to latest version today. I downloaded fmd2 long time ago but today i tried to use it.

**System information**
Windows 10 Pro 2004

**Describe the bug**
I can see 8Muses module in modules list but i can't see 8muses in website list.

**To Reproduce**
1. Go to Websites -> Modules
2. You can see modules/8Muses.lua
3. Go to Websites -> Websites
4. Search for 8Muses
5. No result

**Comment by dazedcat19** [comment]
It's intended. Website module without manga list doesn't appear in website list.
8-Muses manga list on the website is like a directory with uncertain deep. which we can't populate it yet. I'll not work on it. Just make a PR if you want to.
Just copy paste the link in manga info, or use drag n drop feature.
