### ISSUE TITLE
[bug] Manga18.us - Title, Chapters missing and unable to download

### ISSUE THREAD

**Issue by enjoe842** [dazedcat19/FMD2#603]
**Prerequisite**
- [ √] I'm using the latest version.
- [ √] All website modules are up to date.

- [√ ] This is not temporary server issue.

**System information**
Windows 10 Pro 21H1 build 19043.1055

**Describe the bug**
The display where chapters should appear is empty and the titles are replaced by N/A. 

The website works just fine when I open it through my browser and it doesn't require any captcha or cloudflare ddos protection.

I have try to set both the user agent the cookies sent from my browser and pasted them into the Advanced entry for the site. It can still get the other information fine, authors, artists, genres and summary all appear.

**Comment by Geese1** [comment]
I've been having this issue with multiple modules: Bato.to, MangaHere, Fun Manga, etc.

Usually for me, after I click on the title and nothing shows up in the right hand pane (no chapters, and no cover image either), the title disappears from the left pane as well.
