### ISSUE TITLE
[website module request] [bug-website module] VoidScans

### ISSUE THREAD

**Issue by Nicolas-Le-Groignec** [dazedcat19/FMD2#616]
**Website Information**
* **Name:** VoidScans
* **Root URL:** https://voidscans.net/
* **Directory list URL:** https://voidscans.net/manga

* **Example manga info URL:** https://voidscans.net/manga/series/Legend
* **Example chapter URL:** https://voidscans.net/manga/read/Legend/Chapter%2053

**Languages**
English

**Website relationship**
I think it's the new url of https://voidscans.com/

**Additional details**
Login and password are now required, but it's very easy to register a new account.
I think some limitations are present, maybe it will be safer to put limits on requests (like mangadex)

I used the template for the module request because of the url change and the login and password requirement.

**Comment by Slasar41** [comment]
I can't access both URLs.

**Comment by Nicolas-Le-Groignec** [comment]
Apparently the translator team using voidscans was project time, they moved to another website, and completely scrapped the voidscans site ...
I don't know if i should create another issue so:

* **Name:** Project Time
* **Root URL:** https://ptscans.tw/
* **Directory list URL:** https://ptscans.tw/manga
* **Example manga info URL:** https://ptscans.tw/manga/series/50
* **Example chapter URL:** https://ptscans.tw/manga/read/50/53
The images appear to be low quality on paged mode, they seem better on long strip

**Comment by Slasar41** [comment]
We already support ProjectTime https://github.com/dazedcat19/FMD2/blob/3df8bf694173107f7cac1707922569869c8f1b45/lua/modules/ComiCake.lua#L14 but looks like it can't be accessed anymore. Maybe that's the new URL?

**Comment by Nicolas-Le-Groignec** [comment]
> but looks like it can't be accessed anymore. Maybe that's the new URL?

Yep, they made an announcement on their discord for the migration.
