### ISSUE TITLE
[bug-website module] NineMangaES is not walking

### ISSUE THREAD

**Issue by djgerman10** [dazedcat19/FMD2#62]
As the title says, I can't download from NineMangaES. but in the web browser the page is walking perfectly.

![n](https://user-images.githubusercontent.com/48584512/87230446-93260d80-c386-11ea-8781-272d62c17b6a.png)
![z](https://user-images.githubusercontent.com/48584512/87230450-96b99480-c386-11ea-8a7a-a17960f8b76c.png)
![zxxk](https://user-images.githubusercontent.com/48584512/87230453-97522b00-c386-11ea-9d5c-80286eb3ce0a.png)

**Comment by dazedcat19** [comment]
It's working fine here. Download also working fine.
Check your firewall/proxy/vpn.

![img-20200712-104128](https://user-images.githubusercontent.com/59296763/87237730-65939f80-c42c-11ea-8701-da529130bce1.jpg)

**Comment by djgerman10** [comment]
I solved it by downloading the NinemangaES module again.
**Thank you very much**
