### ISSUE TITLE
[bug]  incomplete downloads for hitomi.la

### ISSUE THREAD

**Issue by rosmontis2154** [dazedcat19/FMD2#623]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
win 10 x64

**Describe the bug**
doesn't download all images

**Additional context**
i am downloading the webp's
i think the common.js is changed

**Comment by Rhisk** [comment]
i can confirm.
