### ISSUE TITLE
[Ask] What to do about MangaDex different translations?

### ISSUE THREAD

**Issue by xpndkt** [dazedcat19/FMD2#624]
i wish to download all, or just select the one with good translation, but if i just select all and download it, it will only overwrite the other chapter,(poor english sorry)
for example, there are 3 chapter 1 with different translation, i wish to select the good translation only, but i dont know which one to select, but if i just select 3 of them and download it, it will only overwrite

what im doing right now is, just select one for now and download the other one later after i downloaded and renamed the files so it wont overwrite it when downloading the other chapter 1 (or any double chapter)

so wont it be better if we know what translation we are to download? [this only my suggestion, thanks]
![image](https://user-images.githubusercontent.com/78377464/125460336-d657be00-15c0-41a3-b319-6d0d992ce345.png)

![image](https://user-images.githubusercontent.com/78377464/125460460-722bc7f5-fa4f-4546-9506-dca83dd8b403.png)

**Comment by amit34521** [comment]
Options -> Websites -> Options -> Show Scanlation Group Under mangadex settings
this should help

**Comment by xpndkt** [comment]
> Options -> Websites -> Options -> Show Scanlation Group Under mangadex settings
> this should help

thanks, didnt really know there was something like thta
