### ISSUE TITLE
[feature request] Auto-download new chapters

### ISSUE THREAD

**Issue by Anonym121** [dazedcat19/FMD2#633]
Once you have downloaded a manga, it would be useful to have a way to mark it so that whenever there are new chapters that haven't been downloaded yet, FMD2 does it automatically.
Or at least, the program checks and tells you which mangas have new chapters in the DB you downloaded them from.
I know this is easier said than done.

**Comment by l-l-l-l-l-l** [comment]
Technically speaking, Favorites does exactly that. It looks for new chapters of your favorited series, alerts you and gives you the option to either directly download them to your selected download folder or queue them for download to your selected download folder...

**Comment by Slasar41** [comment]
This?
![image](https://user-images.githubusercontent.com/28888646/126379284-18ea8ffc-b569-44e2-bbae-9fd65af90c09.png)

**Comment by majora2007** [comment]
I think what they mean, at least this is what I want, is an option to just download without alerting me the user. For example, say I'm away from my PC for a week, it'd be nice as new chapters on my Favorite lists are released, they just download without waiting for me to explicitly see the prompt.

Edit: Nevermind, Slasar41's comment does work. Check automatic download after finish checking.
