### ISSUE TITLE
can't update modules

### ISSUE THREAD

**Issue by zinsser901224** [dazedcat19/FMD2#637]
![image](https://user-images.githubusercontent.com/69717616/126709561-36746d9e-7e38-4c15-b456-5888adbf653b.png)
i can't update modules.i've typed vpn settings but it don't work.i've got module files manually but i don't know which folder to put them in.

**Comment by Slasar41** [comment]
Do you still have the issue?

**Comment by zinsser901224** [comment]
> Do you still have the issue?

Yes the problem remains.

![image](https://user-images.githubusercontent.com/69717616/126893144-6e935c0f-1e1e-4317-94fe-70c7d1b1a3dd.png)

**Comment by Slasar41** [comment]
Could you create a file in `lua\modules` folder?

**Comment by zinsser901224** [comment]
> Could you create a file in `lua\modules` folder?

First, there is no Lua folder in the root directory. Should I create a new folder and name it 'Lua'?
Secondly, should I copy the files under the 'Lua' folder on GitHub to this folder?
I have created the 'Lua' folder and copied the files under it. But reopening the program it still prompts that it cannot be updated

**Comment by Slasar41** [comment]
Yeah, FMD need to verify the modules and that need to be downloaded by FMD itself.
So if you download the modules manually and put them in lua modules, FMD can't verify them.

Could you try move FMD folder to different place?
Maybe FMD can't write in the current location.

**Comment by zinsser901224** [comment]
> Yeah, FMD need to verify the modules and that need to be downloaded by FMD itself.
> So if you download the modules manually and put them in lua modules, FMD can't verify them.
> 
> Could you try move FMD folder to different place?
> Maybe FMD can't write in the current location.

I can write files in LUA folder.
I run FMD as an administrator, but I still can't update.

**Comment by Slasar41** [comment]
Have you tried moving FMD folder to a different drive?

**Comment by zinsser901224** [comment]
> Have you tried moving FMD folder to a different drive?

Yes.I copy the folder from f:\ to d:\ (HDD to SSD) and the problem remains.

**Comment by Slasar41** [comment]
Try with a fresh download of FMD.
