### ISSUE TITLE
[bug-website module] Mangadex Mapping Issue Under Wine

### ISSUE THREAD

**Issue by Velgen** [dazedcat19/FMD2#638]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**

Linux Pop!_OS 20.04

**Describe the bug**

For some reason it appears the mapping function of the Mangadex plugin does not function under Wine. Have had everything work perfectly for over a year now under Wine, but ran into this a few days ago after finally trying to check my Mangadex favorites after I initially checked if it was functioning on June 22nd. Guessing the old URLs were still functional at that time because it is no longer able to update the status of those favorites, but if I manually put in the new URL to "Manga Info" I can download and add to my favorites just fine. Also I hopped over to my Windows drive and everything functioned normally. Even tried checking the status after the Windows run hoping it was maybe a first run issue.

**Additional context**

Rather than additional context this is more a question/suggestion why doesn't the module simply update the old favorites URL to the new URL after first run, or would it be possible to make a utility to update the favorites database with the new URLs? Since this is a Wine issue I am doubtful this will be a high priority/worth the trouble of fixing, but I personally even if on Windows would prefer my favorites to be using the updated urls vs checking a mapping function every single time it's checking the favorite status.

**Comment by Slasar41** [comment]
Need to use a converter tool to change the ID in the database.
Try this: https://github.com/elliotcraft79/fmd_mangadex_converter
