### ISSUE TITLE
Is there any way to run fmd2 on linux without emulating?

### ISSUE THREAD

**Issue by djgerman10** [dazedcat19/FMD2#64]
Is there any way to run fmd2 on linux without emulating?

The only reason why I don't switch to Linux is because of fmd, which is only compatible with Windows.
is there any way to compile this application for linux.

**Comment by dazedcat19** [comment]
Just try to compile it with lazarus with linux. I already put some defines for windows specific. But some other might need adjustment. There's nothing much in the source code for os specific beside io stuff.
Use fpc and lazarus trunk.

**Comment by typhoe** [comment]
Just to say, while a native linux version of FMD would be great, it works fine in Wine!

I have used it like this for a few years now and it works perfectly.

```cd /path_to_fmd/ && wine fmd.exe```

**Comment by Banh-Canh** [comment]
I had the same idea and made a docker image out of it (wine + FMD2), using xvfb/x11vnc/novnc, if you want to try it. You can access FMD2 GUI with your browser: https://github.com/Banh-Canh/docker-FMD2
I will try to compile it before putting it in the container now though

**Comment by xx255q** [comment]
@dazedcat19 can this be closed
