### ISSUE TITLE
[bug-website module] myreadingmanga is returning N/A

### ISSUE THREAD

**Issue by WhoAreYouPeople** [dazedcat19/FMD2#640]
**Prerequisite**
- [ X] I'm using the latest version.
- [ X] All website modules are up to date.

- [ X] This is not temporary server issue.

**System information**
OS: Arch Linux 
Kernel: 5.13.4-zen1-1-zen

**Describe the bug**
Seems like myreadingmanga changed their website a little. I think it's cloudflare, but I'm not sure. I'm noticing there looks to be a few more cookie entries then there was before. The download path populates correctly, but no chapters are listed and the title is N/A. Thank you.

**Comment by Slasar41** [comment]
I can still access it with cookies workaround.

**Comment by WhoAreYouPeople** [comment]
Yeah it's an annoying one. No combo of cookies sent seem to work.

**Comment by Slasar41** [comment]
Which manga?

**Comment by WhoAreYouPeople** [comment]
I can't supply any examples, but it didn't work with any manga. I tested the most recent manga and when I realized there were issues I tried one I and previously checked info for and they did not work either.

**Comment by WhoAreYouPeople** [comment]
Hi update for anyone else who needs this. So its not an issue with FMD its an issue with the cookies that MRM has. During normal use the browser should just have the normal cf_cleareance cookie and that's all you need to supply to FMD. BUT if there is a hcaptcha page it will be three parts to the cookie. Only give FMD the new cf_clearance cookie. The other two parts will break cause the N/A error.
