### ISSUE TITLE
[bug-website module] MyReadingManga

### ISSUE THREAD

**Issue by WhoAreYouPeople** [dazedcat19/FMD2#649]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Arch Linux 5.13
Wine 32bit prefix

**Describe the bug**
When downloading multiple manga at once if MyReadingManga has to load a page there will be a little gif in place of the page. The gif is of a cat sort of sitting down and wagging its tail. Is it possible to have FMD retry a download if it gets that cat gif? Because currently the cat gif gets counted as the page. I don't know of FMD can be made to compare the download images hash and retry if it matches the cat gif hash. But if it can I can provide the hash. Thank you.

**Comment by Slasar41** [comment]
Provide link example.

**Comment by WhoAreYouPeople** [comment]
Sure thing. I believe that it occurs with this link. Sorry for sending you to not the best site in the world. Thanks for looking into the issue.
https://myreadingmanga.info/ariki-eiko-underskin-eng/

**Comment by Slasar41** [comment]
Well now it's my turn getting N/A.
I've read your comment in the last issue and just apply `cf_clearance` cookies but it's still not working.

**Comment by WhoAreYouPeople** [comment]
What are the three parts of the cookie again? I may have commented the wrong one? Of all the times to not be able to trigger the hcaptcha page. Oh should have specified on the last issue, did you set the user agent as well?

**Comment by Slasar41** [comment]
I don't get hcaptcha page and all the times I'm doing it is copying all the cookies and user agent to FMD and it's works fine.
The different now is currently I'm running Windows 11. Not sure if that the cause.

**Comment by WhoAreYouPeople** [comment]
Oh my lord I forgot. It doesn't work on Windows. I forgot that was an issue. Let me send a screenshot of my working settings when I get home.

**Comment by WhoAreYouPeople** [comment]
Okay back. So without the hcaptcha what I am supplying is
user agent
and
cookie: cf_clearance and __cf_bm

**Comment by Slasar41** [comment]
Not sure if it because I use Windows 11 or Microsoft Edge Canary, but I'm using Windows 10 and Microsoft Edge Stable now and I can use full cookies like usually.

I'll update the module.
