### ISSUE TITLE
Error validating /contentRating/0 on Mangadex [bug]

### ISSUE THREAD

**Issue by Maxwell12347842** [dazedcat19/FMD2#650]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
If you click on a manga that has nsfw / adult content on it, it removes the entry from the list of mangas in the manga list entry the server has. the log says 'error: Error validating /contentRating/0: Does not have a value in the enumeration ["safe","suggestive","erotica","pornographic"]' - also "MangaDex: Legacy ID Mapping has been executed."

**To Reproduce**
1. Go to 'Manga Info'
2. Click on a Manga from the List of the Mangadex Server (updated list)
3. Manga you clicked gets removed automatic from the list
4. Log shows errors mentioned

**Expected behavior**
Mangas won't get auto removed from the list & no errors are thrown

**Comment by Maxwell12347842** [comment]
hello?

**Comment by Slasar41** [comment]
I've updated the manga list. Try redownload from server.

**Comment by Maxwell12347842** [comment]
> I've updated the manga list. Try redownload from server.

now it seems to work, thanks!
