### ISSUE TITLE
[bug] No Modules in the latest release

### ISSUE THREAD

**Issue by Akouniza** [dazedcat19/FMD2#651]
Hi everyone !

- [Yes] I'm using the latest version. (release)
- [I don't know ] All website modules are up to date.

**System information**
Your operating system.
Windows 10 Pro

**Describe the bug**
I downloaded FMD2 in release section but nothing seems to appears in module

**Expected behavior**
Have downloading choices ?

I don't really know. I guess i want something to appear?

**Comment by Slasar41** [comment]
Check Options -> Websites -> Modules.

**Comment by Akouniza** [comment]
Thanks, i already checked but nothing updated even with Check Update button

Did i need to manually Build the sourcecode ? 

![image](https://user-images.githubusercontent.com/42040156/127753328-a8737dad-001c-40ab-a504-b6c324cc68e4.png)

**Comment by Slasar41** [comment]
That's weird.
Try these files, put them to `userdata` folder and reopen FMD.
[userdata.zip](https://github.com/dazedcat19/FMD2/files/6911904/userdata.zip)

**Comment by Akouniza** [comment]
Okay so i put the files in userdata folder like this:

![image](https://user-images.githubusercontent.com/42040156/127763937-005ca500-18dc-45b9-96e4-5a291e26ade7.png)

After that the modules showed up but nothing was downloading:

![image](https://user-images.githubusercontent.com/42040156/127764230-c66fcbe0-f76a-4d50-81d6-c258b78d4a8f.png)


I searched a bit trough the different issues why the updates weren't downloading, so i found that i needed to create a `lua/modules` folder.



After creating it and opening FMD in administrator the problem still persists, it cannot download files. 
So i tried something, i directly downloaded the 'fmd-master' and put the lua folder of it in the directory, at first the modules seemed to work but nothing appeared else than in 'modules'.

Thanks for taking the time !

**Comment by Akouniza** [comment]
Update for everyone, I tried on my vm (VMware workstation) and it worked? 
Weird! So I did something, i tried on another disk of my physical computer, it didn't worked so, I partitionned one of my disks and somehow it worked.

I guess Windows and his weird problems... 

Thanks for your time.
