### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by thorio2002** [dazedcat19/FMD2#655]
**Prerequisite**
- [ yes] I'm using the latest version.
- [yes] All website modules are up to date.

- [yes ] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**

**To Reproduce**
1. Go to 'SamuraiScan'
2. Click on 'manga name'
3. View error

**Expected behavior**
That will show the information of the manga and the chapters that can be downloaded.

**Screenshots**
https://ibb.co/TLQZyCS

**Additional context**
no new manga appear and the SamuraiScan manga list is not refreshed.

site example
https://samuraiscan.com/
https://samuraiscan.com/bl/star-martial-god-technique/
https://samuraiscan.com/bl/star-martial-god-technique/capitulo-464/

**Comment by Slasar41** [comment]
Should be fine.
