### ISSUE TITLE
[website module request] ColoredCouncil

### ISSUE THREAD

**Issue by Kayizoku** [dazedcat19/FMD2#656]
**Website Information**
* Name: *ColoredCouncil* 
* Root URL: *https://coloredcouncil.moe/*
* Directory list URL: *https://coloredcouncil.moe/series/*

* Example manga info URL: *https://coloredcouncil.moe/read/manga/OnePiece/*
* Example chapter URL: *https://coloredcouncil.moe/read/manga/OnePiece/1/1/*

**Languages**
List of languages supported by the website: English

**Website relationship**
The domain is a copy of: https://guya.moe/

**Comment by theincognito-inc** [comment]
Yes. Eagerly waiting for this, if anybody could help :)

**Comment by Slasar41** [comment]
Added https://github.com/dazedcat19/FMD2/commit/636e5093b87fbd753a703dfc84d35905270aaed0
