### ISSUE TITLE
[bug] Cannot download manga from Welovemanga

### ISSUE THREAD

**Issue by PanzerIVF** [dazedcat19/FMD2#658]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
WeLoveManga is not downloading. Everytime I try to redownload it, it still can't download from the site.

**Expected behavior**
Everytime I download from Welovemanga sites, it just not read it..

**Screenshots**
![fmd_2021-08-05_12-50-37](https://user-images.githubusercontent.com/22032292/128298230-77947992-eb1d-4220-a60d-83c2e0c452b0.png)

**Comment by Slasar41** [comment]
You need to login in Options -> Websites -> Account.

**Comment by TienVer** [comment]
I have a similar problem, though this is only limited to series with adult/risqué content.

FMD2 will, for example, download updates to [_Hell Mode - Yarikomi Suki no Gamer Wa Hai Settei no Isekai de Musou Suru_](https://welovemanga.net/827/), but not to [_The Café Terrace of the Goddesses_](https://welovemanga.net/1436/).

I tried activating the Account option as advised above, but the mature series still won't download. FMD2 lists my account credentials (email + password) as "OK", though. Don't know if welovemanga now requires more cookie parameters (there are more of them now compared to the old LoveHug, where PHPSESSID, hash and UserID were the only params needed)...


EDIT:
There seems to be a problem with the website itself; even after logging in, adult-earmarked chapters still cannot be viewed. Case in point, [Risou no Himo Seikatsu](https://welovemanga.net/727/): on my browser, I am perfectly logged in but am always redirected back to the series profile when I click on **_any_** of the chapter links. "Vanilla" (read: PG) series, on the other hand, remain perfectly legible. Maybe the webmaster broke something in the code...

**Comment by Slasar41** [comment]
I haven't tested it but if even the browser can't show the images, then it's a server issue.

**Comment by TienVer** [comment]
Tested it on multiple browsers (Edge 92, Firefox 90, Chrome 92, Vivaldi 4.1) and multiple R/NC17-rated series - same result, I get redirected to the profile page regardless of the chapter link I click. PG series are fine.

It's definitely the website/server code and/or the permission system that is borked. Unless they implemented a new user point/karma/merit system we don't know of yet.

**Comment by TienVer** [comment]
Downloads are working again as of this morning as is the website permission system.
