### ISSUE TITLE
[website module request] WeLoMa

### ISSUE THREAD

**Issue by micederX** [dazedcat19/FMD2#661]
**Website Information**
* **Name:** WeLoMa
* **Root URL:** https://weloma.net/
* **Directory list URL:** https://weloma.net/manga-list.html

* **Example manga info URL:** https://weloma.net/125/
* **Example chapter URL:** https://weloma.net/125/4217/

**Languages**
Japanese

**Website relationship**
Copy of WeLoveManga (of the Lhscans family)

**Additional details**
Uses the same template as WeLoveManga, though the specific series' numbers are different.  Just to test it, I tried adding an entry for this to the Lhscans.lua file in the same places as WeLoveManga, and it seemed to work.

**Comment by TienVer** [comment]
I'd just like to point out that it'd be worth the while to make a separate entry for weloma.net - compared to WeLoveManga, there is no age gate on mature/adult series; everything is viewable (and therefore downloadable) even without a user account.

Case in point (Isekai Yurutto Survival Seikatsu, ch.43):
https://weloma.net/344/61489/ (no age gate)
https://welovemanga.net/807/59688/ (age gate, which redirects the user to series profile even when logged in)

The only question is whether the site will last and be able to successfully draw the WeLoveManga uploaders over to itself, given the recent (and still unfixed) hiccups on the original site.
