### ISSUE TITLE
[bug-website module] Kissmanga new cloudflare challenge?

### ISSUE THREAD

**Issue by HiP1** [dazedcat19/FMD2#67]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Your operating system.
Windows 10
**Describe the bug**
seems kissmanga has a new cloudflare challenge, when i check favorites and when i download chapters
**Additional context**

**Log**
23:20:28:563 WebsitBypass[clounflare]: detected the new Cloudflare challenge, not supported yet
https://kissmanga.com/Manga/Black-Clover
23:24:50:965 WebsitBypass[clounflare]: detected the new Cloudflare challenge, not supported yet
https://kissmanga.com/Manga/Mairimashita-Iruma-kun/Vol--015-Ch-129----Let-s-Get-It?id=656946

**Comment by molitar** [comment]
The reason why I quit using Kissmanga at all. it's gotten ridiculous.. I'll use MangaDex for most of my stuff now.

**Comment by HiP1** [comment]
indeed, it seems like they actually want us to go to their website instead of directly downloading without seeing the ads :p

**Comment by molitar** [comment]
> 
> 
> indeed, it seems like they actually want us to go to their website instead of directly downloading without seeing the ads :p

Yep and now I just use Mangadex.. screw Kissmanga and all the porn ads with malware on the redirects.. They do not even care that the ads have malware.

**Comment by HiP1** [comment]
cloudflare challenge seems to be ok now.
but kissmanga seems to ask for the human challenge every two chapter download now... :D Guess it's time to drop them

**Comment by HiP1** [comment]
Kissmanga was shut down by copyright owners, it seems :D
on the hompage : "All files are taken down by copyright owners. The site will be closed forever. Thank you for your supports."
