### ISSUE TITLE
kissmanga .in doesnot updating[bug]

### ISSUE THREAD

**Issue by DrPolash** [dazedcat19/FMD2#670]
**Prerequisite**
- [✔] I'm using the latest version.
- [✔] All website modules are up to date.

- [✔] This is not temporary server issue.

**System information**
Processor	Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz   2.60 GHz
Installed RAM	8.00 GB
System type	64-bit operating system, x64-based processor

**Describe the bug**
Kissmanga .in mangas are not updating its red and chapt. showing 0. 
when i try to add manga through manga info it shows N/A

**Screenshots**
![Screenshot (65)](https://user-images.githubusercontent.com/88780792/129032556-7ec5401a-9773-4d4c-b7de-404d8904cef2.png)

**Comment by Slasar41** [comment]
Works fine here.

**Comment by hesoyamma785** [comment]
I also have the same problem like this friend of mine.
Could you re-check this problem again?

**Comment by Slasar41** [comment]
@hesoyamma785 Yeah, it's not working because cloudflare.
You can create a new issue.
