### ISSUE TITLE
[bug] Mangadex chapter numbering when including OneShot

### ISSUE THREAD

**Issue by hypomaniak** [dazedcat19/FMD2#671]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 7 64b

**Describe the bug**
Some mangas on Mangadex have a chapter named OneShot. When others chapters are added, the oneshot takes a number in continuity, where previous versions of FMD would name the file as OneShot.

**To Reproduce**
1. Go to 'https://mangadex.org/title/d61f38e8-a4dd-4b6d-8957-3291f37c335c'
 At the moment I write these lines, the series contain the OneShot and chapters 1 2 and 3.
2. See the chapter list in FMD, the OneShot is listed as Chapter 4.

**Expected behavior**
Previous versions of FMD would name that chapter OneShot, and not insert a wrong number in the title.

**Additional context**
My settings for naming rules are
![image](https://user-images.githubusercontent.com/24497455/129071176-866c5468-0c6a-4b6b-a39c-bc0b5e34cc76.png)

Ideally, the OneShot chapter should appear as number 1,
But even if it's in the last position, I would expect it to be named as "0004 - OneShot [MangaDex].zip" instead of "0004 - Ch. 004 [MangaDex].zip"

**Comment by Slasar41** [comment]
FMD get the data from MangaDex's API.
When I check the API of [that manga](https://api.mangadex.org/manga/d61f38e8-a4dd-4b6d-8957-3291f37c335c/feed?limit=500&offset=0&translatedLanguage[]=en&order[chapter]=asc), I don't see the API providing the title of Oneshot chapter. It's just an empty string instead.

**Comment by Slasar41** [comment]
Which is the best way?
![image](https://user-images.githubusercontent.com/28888646/129413501-6fcab328-93c1-418c-8a1b-eb81b84639e8.png)
![image](https://user-images.githubusercontent.com/28888646/129413503-43665feb-6b71-4ff3-a8c1-fcf69db0226d.png)

**Comment by hypomaniak** [comment]
I am in favor of the first one, but both are good results.

Thank you.
