### ISSUE TITLE
[bug-website module]Fanfox

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD2#677]
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 7-64 bit
**Describe the bug**

Can't stop or remove download from fanfox. When I try, FMD stops responding.
![image](https://user-images.githubusercontent.com/24958560/129469066-a3da350d-d1e4-4192-a858-7294223b0d6d.png)
![image](https://user-images.githubusercontent.com/24958560/129469091-38416764-c659-4cf9-bc35-10b50fee5adc.png)

**Comment by Slasar41** [comment]
Works fine on my end.
Able to download all available chapters without an issue.
