### ISSUE TITLE
[bug-website module] Manytoon

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD2#679]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Able to retrieve title, cover, and details but no chapters.  Chapters show 0. If I click read online it opens properly to the correct manga's but all manga show 0 chapters when you click on them for detail.  The problem seems to be intermittent and after many attempts it was able to pull up chapters. 

any ideas why and how this could of happened?  Took me about 15 minutes of trying until it worked.

**Comment by billyboy999** [comment]
Mangadex is not working either. Can pull series info but can't list any chapters. 

A complete reinstall seems to fix the issue.

**Comment by molitar** [comment]
After redoing my entire FMD 2.0 install because other sites stopped working I can no longer get manytoon.me to work at all.  All show 0 chapters after doing an Update Manga List.

**Comment by Slasar41** [comment]
Fixed. https://github.com/dazedcat19/FMD2/commit/694c946a3a765600983a7503ecb186fa5d819f64
