### ISSUE TITLE
[bug-LoveHeaven] downloads do not complete

### ISSUE THREAD

**Issue by Dgraid12** [dazedcat19/FMD2#68]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7 ULTIMATE 64 Bits SP1

**Describe the bug**
The downloads work fine, but when you get to the last page of the chapter, stop downloading.

**Screenshots**
![image](https://user-images.githubusercontent.com/53473707/87568729-1cde1f80-c694-11ea-9a20-cfc32e215cca.png)

**Additional context**
apparently there was some change in the page, before putting to download those 2 manga, I download all the chapters that I have in favorites on the page loveheaven

**Comment by Slasar41** [comment]
Should be fixed.
For why FMD suddenly have many updated chapters at once, that because loveheaven have changed all the link of the chapter and FMD recognized it as a new chapter.
