### ISSUE TITLE
[bug-website module] Immortalupdates Cloudfare workaround not working.

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD2#683]
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 7-64 bit system

**Describe the bug**
Workaround for Immortal updates is not working. It was fine till yesterday but now I'm checking the chapters are like this:
![image](https://user-images.githubusercontent.com/24958560/130028425-62c3082f-d965-4ab0-b15e-6edf59aad5ce.png)
![image](https://user-images.githubusercontent.com/24958560/130028452-7a47f73f-b217-4fee-95ed-8d1417a5aee5.png)

**Comment by Slasar41** [comment]
Same issue as https://github.com/dazedcat19/FMD2/issues/667.
