### ISSUE TITLE
[bug-website module] Can't download from manhwahentai.me

### ISSUE THREAD

**Issue by Plegmatis** [dazedcat19/FMD2#684]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win 10 64bit

**Describe the bug**
Manhwa from manhwahentai.me getting 0s when checking on favorites

**Additional context**
- I can open and read manhwa from the website normally on browser.
- I tried copy paste the link from browser it shows the manhwa description but the chapters didn't show. 
- I tried cloudfare workaround and didn't work.

**Log**

**Comment by Slasar41** [comment]
Works fine here.
