### ISSUE TITLE
[bug ]hiperdex does not correctly update the manga in favorites

### ISSUE THREAD

**Issue by jjrc28** [dazedcat19/FMD2#685]
**Prerequisite**
- [ ] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jjrc28** [comment]
when you check for a new chapter it doesn't update all just a few

**Comment by Slasar41** [comment]
Please provide the titles.
