### ISSUE TITLE
[bug-website module] Manga18.club - Title, Chapters missing and unable to download

### ISSUE THREAD

**Issue by enjoe842** [dazedcat19/FMD2#686]
**Prerequisite**
- [Yes] I'm using the latest version.
- [Yes] All website modules are up to date.

- [Yes] This is not temporary server issue.

**System information**
Windows 7 SP1.

**Describe the bug**
- The display where chapters should appear is empty and the titles are replaced by N/A.
- The website works just fine when I open it through my browser and it doesn't require any captcha or cloudflare ddos protection.

![Untitled](https://user-images.githubusercontent.com/33560815/130310157-7933b0dd-3f72-4618-863d-f6b5d7dbff4e.png)

**Comment by enjoe842** [comment]
anyone know where the problem is?

**Comment by hesoyamma785** [comment]
I also have the same problem so if anyone know how to fix this problem please tell us

**Comment by ghost** [comment]
do we have fix?
