### ISSUE TITLE
[Possible Temporary][bug-website module] LHtranslation site changed [Waiting Status Confirmation]

### ISSUE THREAD

**Issue by GDXN** [dazedcat19/FMD2#687]
### **Warning, the change appear that is temporary**

**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

The site have changed now is made in WordPress, the basically all have changed.

The new links for the manga are: 

* **Directory list URL:** https://lhtranslation.net/manga/
* **Example manga info URL:** https://lhtranslation.net/manga/nito-no-taidana-isekai-shoukougun-saijaku-shoku-healer-nano-ni-saikyou-wa-cheat-desu-ka/
* **Example chapter URL:** https://lhtranslation.net/manga/nito-no-taidana-isekai-shoukougun-saijaku-shoku-healer-nano-ni-saikyou-wa-cheat-desu-ka/chapter-15-1/

**Comment by arbiter9605** [comment]
they switched templates to use one of Madara.lua. Just tested by doing some edits to lua's and it works. They have changed URL structure so old one was "https://lhtranslation.net/manga-nito-no-taidana-isekai-shoukougun-saijaku-shoku-healer-nano-ni-saikyou-wa-cheat-desu-ka/" so instead of a / it was a - between manga and the name of the manga.

**Comment by Slasar41** [comment]
I thought it's only temporary and will change back to old website?

**Comment by arbiter9605** [comment]
i don't know but its possible its temporary. Their site was down for a few days now its back with this. According to discord the site got hacked. 

Edit: looks like it is only temporary til they get things fixed on old one likely to keep pushing releases and not have to sit on them for undetermined amount of time.
"https://lhtranslation.net/manga/the-new-lh-website-and-you/chapter-1-stuffs-still-broken/"

**Comment by GDXN** [comment]
Yes, actually it appears that is temporary. I thing that I hurried to much.
For now I think that is good to leave the issue open until they finalize to fix their site.
