### ISSUE TITLE
add support for website [komiktap]

### ISSUE THREAD

**Issue by MIRVOUS** [dazedcat19/FMD2#69]
**Website Information**
* **Name:** komiktap
* **Root URL:** "https://komiktap.net/"
* **Directory list URL:** "https://komiktap.net/a-z-list/"

* **Example manga info URL:** "https://komiktap.net/manga/a-rank-boukensha-no-slow-life/"
* **Example chapter URL:** "https://komiktap.net/a-rank-boukensha-no-slow-life-chapter-15-bahasa-indonesia/"

**Additional context**

**Comment by Slasar41** [comment]
Added https://github.com/dazedcat19/FMD2/commit/bda8780d4fd6f679ddfc8b9e76bcddb46482ab74
