### ISSUE TITLE
[bug-website module] MangaDex fails to check favorites or download chapters

### ISSUE THREAD

**Issue by acg5159** [dazedcat19/FMD2#696]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
```
               Application       : Free Manga Downloader
               Version           : 2.0.31.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit Build 19043
               FPC Version       : 3.3.1
               LCL Version       : 2.1.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2021/03/21 14:33:22
```

**Describe the bug**

- Favorites are failing to download from MangaDex.

- When looking through the 'Managa Info' list, the chapters get reset to "(0)" when trying to read Info and nothing shows up in the bottom right box:
![image](https://user-images.githubusercontent.com/75958158/131177426-aa5aea14-5124-4fe8-aa5c-6fcfdba7ffa8.png)

**Additional context**
Accessing through Chrome has no issues, but accessing through Firefox was not working (though I do not really use Firefox much).

**Log**
Only the following line is showing up: [fmd.log](https://github.com/dazedcat19/FMD2/files/7069024/fmd.log)
```
15:16:30:888 INFO: MangaDex: Legacy ID Mapping has been executed. The new ID is: 
```

**Comment by Slasar41** [comment]
Check your MangaDex language settings in FMD options.

**Comment by acg5159** [comment]
@Slasar41, Thank you. not sure how that got changed. I have not touched those settings in a while.
