### ISSUE TITLE
[bug] 64-bit lua memory leaks

### ISSUE THREAD

**Issue by dazedcat19** [dazedcat19/FMD2#7]
If you notice in 64-bit version. The allocated memory keeps rising without going down. There's seems to be a problem with the 64-bit lua c api itself. Haven't found the solution yet.

**Comment by HiP1** [comment]
doesn't seem to leak for me, it stays at around 190 MB in the taskmanager

**Comment by dazedcat19** [comment]
there's memory leaks report in heaptrc. for every lua's cfuntion call.

**Comment by dazedcat19** [comment]
It will leak if lua call function which call another function. but only on 64-bit windows. I tried lua 5.1, 5.2, 5.3, 5.4 and luajit. all produce the same leaks. the leaks isn't much. around 5 to 10mb after running for 10 hours with a lot of downloads. can be a bug in heaptrc. but it make it hard to debug for the real memory leaks.

64bit fmd with around 100 downloads and 100 favorites should be using about 30mb at startup. And should be stay that much on idle. when running downloads it can raise to  > 100mb with a lot of threads and fast connection. the majority is the downloaded image that keep in memory. but all should be freed when download stopped and the memory usage should be back down close to its startup.

this one cause memory leaks:
```
function doMaybeFillHost(...);
begin
...
end;

function _maybefillhost(L: Plua_handle): integer; cdecl;
begin
   doMaybeFillHost(...);
end;
...
lua_register(L, 'MaybeFillHost', @_maybefillhost);
```
