### ISSUE TITLE
[bug] Mangadex hard limit broken!

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD2#70]
**Prerequisite**
- [x ] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
I got banned because the Mangadex hard limit is broken.  I had to go to a VPN and set limits again.  I set limits and when it updated FMD2 the limits were gone once again on Mangadex the limits are not properly saving and the hard limit built in is not working either. 

**Expected behavior**
hard limits to save

**Comment by McChickn** [comment]
I'm getting banned from MangaDex too, frequently. Sometimes I can download, other times I'm banned (servers not responding to any requests) before downloading the first page. Either the one, or the other, nothing in between. 
I have no idea why, no clue what this "hard limit" thing is, or if that's the cause.
