### ISSUE TITLE
[bug-website module] Mangadex not loading chapters anymore

### ISSUE THREAD

**Issue by Worrend** [dazedcat19/FMD2#718]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Windows 10 64 Bit last Update

**Describe the bug**
Untill yesterday I was using mangadex.org without problems but this evening I am unable to download anything from it,
The manga summary load but the list with the manga chapters remain totally emtpy. (No chapters appear)

**Additional context**
Browsing the site with a web browser works fine

**Log**
[fmd.log](https://github.com/dazedcat19/FMD2/files/7150294/fmd.log)

**Comment by Slasar41** [comment]
Should be fixed. https://github.com/dazedcat19/FMD2/commit/188fa5aa279c189990aa2b068314e9dd73a52bb7
