### ISSUE TITLE
[bug] Readcomiconline do not download

### ISSUE THREAD

**Issue by sutam1** [dazedcat19/FMD2#72]
![image](https://user-images.githubusercontent.com/59839681/87904499-68921f80-ca2c-11ea-8e5e-f95011381966.png)
Readcomiconline do not download. I have tried several times, but of almost 500 comics only 50 did download. Can you look on it? Thanks. Your program makes my life better. Good job.

**Comment by Slasar41** [comment]
Because the cloudflare's captcha need to be solved and FMD doesn't support auto solving it yet, you've to do cookies workaround and then the download will works again.

**Comment by ragna0011** [comment]
i have the same issue and i got no idea how to fix it..i really need help

**Comment by Slasar41** [comment]
Copy the cookie and user-agent from browser to FMD like in this example:
![image](https://user-images.githubusercontent.com/28888646/88418372-a8328000-ce0d-11ea-99b6-15adabcf3a85.png)

**Comment by ragna0011** [comment]
im sorry but idont know how to find cookies..and up to now, i still cant download T_T pls need help, specifically instructions

**Comment by Slasar41** [comment]
@ragna0011 Open readcomiconline website -> press F12 -> Network tab -> select the first one, copy the cookies and user-agent (see screenshot from mine above)
in FMD, go to Options -> Websites -> Advanced -> readcomiconline, change Enabled option to True, paste the cookies and user-agent from browser
then press Apply
