### ISSUE TITLE
[bug-website module] LHtranslation site changed [Confirmed change]

### ISSUE THREAD

**Issue by GDXN** [dazedcat19/FMD2#720]
Update on #687, as notified the change of the site to the new site using madara has been made definitive, but the old site is accessible on https://archive.lhtranslation.net/, I propose to fork it making the old site renamed as "LHtranslation Archive" and create a new module id for the new "LHtranslation" site.

> Website update
> Some one has to break the news.
> After long internal debates, the decision has been made that we're going to continue the current system.
> I'll be continuing to work on the new website's system and slowly add features where possible.
> 
> Archive
> This also means the old site will be discontinued as of today.
> A back-up is temporarily available through https://archive.lhtranslation.net/
> Note, I cannot guarantee the safety nor security of that version of the website.
> 
> If you decide to use it, proceed with caution and don't download/execute anything from that version of the site. The old website will NOT return any time soon. 
> (Though I am working on a massive re-write of it for the sake of archiving things)
> 
> Everything that used to be on the archive will be moved over to the new site over time.
> 
> RSS/Update Feed
> Now, for the RSS fans under us. You should update your feed urls to:
> https://lhtranslation.net/feed/manga-chapters
> This is the new system's feed for new releases.
> 
> Speaking of new releases, some of you nerds probably already use this. But we've been working together with Kenmei, Kenmei is a cross-site manga tracker that helps you keep track of releases MAL style.
> https://www.kenmei.co/ the same release feed from above is used for this.
> 
> User accounts & website plans
> In other news, I'm working on allowing you guys, gals, and apace helicopters to make accounts again.
> This will be a phased trial roll-out, meaning that we'll slowly open more spots up for people to create accounts as we bolster security and add feature requests.
https://discordapp.com/channels/359107239056769044/359154036580155412/886345239286132746

**Comment by HiP1** [comment]
+1
And it's a pity that they are not adding the new releases to the archive version of the site. :(

**Comment by HiP1** [comment]
oh I didn't see that it was added already xD
