### ISSUE TITLE
[bug-website module] LeviatanScans

### ISSUE THREAD

**Issue by jokosablenk** [dazedcat19/FMD2#722]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win 10 Home.

**Describe the bug**
Leviatan Scans not loading chapter lists.

**Additional context**
Checking new chapters from the favorites tab gives zero chapters.

**Comment by Trollam** [comment]
Do you encounter this bug on manga hosted on bilibilicomics ?
If you don't know, can you give me the name of a manga who do not load ?

**Comment by jokosablenk** [comment]
not the bilibili one. 

all the manhwa/manga like Trash of the Count's Family

![ss](https://user-images.githubusercontent.com/36765223/134602910-6f6c19ca-8441-4a63-b1d0-9e7bf37c73e9.png)

**Comment by Jerrk** [comment]
i know flamescans and leviatanscans change their URLs quite often and that might be the problem here

**Comment by alatnet** [comment]
Yea, im experiencing the same thing, i think they are randomizing the number in the url to prevent FMD and other apps from downloading from their servers.

Possible solution would be to update the manga list from the server and applying the new url to the favorited manga, though that is not ideal...

**Comment by alatnet** [comment]
I may have found a fix!
Remove the numbers!
Example:
https://flamescans.org/series/1635480122-a-returners-magic-should-be-special/
to
https://flamescans.org/series/a-returners-magic-should-be-special/

**Comment by jokosablenk** [comment]
yeah, updating manga list fix the issue, and yeah it's not ideal.
