### ISSUE TITLE
[feature request] Import favorites directly from mangadex

### ISSUE THREAD

**Issue by Jerrk** [dazedcat19/FMD2#767]
**Is your feature request related to a problem? Please describe.**
I'm following over 1000 series and i would like to add all of them to my favorites on FMD

A good chunk is read through mangadex and i have a sizeable reading list on my mangadex account.
and i would hope that in the future it would be possible to import your entire reading list from mangadex into FMD.

**Describe the solution you'd like**
The ability to import the reading list from your account on mangadex.org

**Describe alternatives you've considered**
i've considered adding all my favorites to FMD one by one, and if this suggestion gets shot down i'll probably get around to it over the next year or two :roll_eyes: .

Not sure theres any other ways to do such a bulk import and searching the issues i couldnt really find anything.

**Additional context**
i saw some issues talking about possibly adding mangadex account support in the future, and i just wanted to suggest another item for that list if it ever materializes.

**Comment by Slasar41** [comment]
Does MangaDex able to show all titles with the url?
If so, you can use the Drop Box feature in FMD, Options -> View.
Drag all titles from browser to the drop box.

**Comment by Jerrk** [comment]
> 
> 
> Does MangaDex able to show all titles with the url? If so, you can use the Drop Box feature in FMD, Options -> View. Drag all titles from browser to the drop box.

they don't explicitly show you all their urls somewhere but what you said got me thinking.

i first tried to figure out the API myself but i couldnt find any guides that really just showed what to do. something to do with this maybe? https://api.mangadex.org/docs.html#operation/get-manga-status
i tried postman but i couldnt get the auth to work for some reason.

then eureka, i realised that neko probably has this API thing figured out already so i went into my neko app and marked all of my reading list -> share -> and then save as .txt file. This gave me a .txt file with the URL of each manga on my reading list.
i opened that .txt file in firefox, i highlighted the entire list, and dragged it onto the drop box.

It is now adding 1700 entries as we speak :grin: 

not sure if there is an easier way to do this but this definitely did work.

this also works with sites other than mangadex if you've got tachiyomi, just mark all the desired titles, and share to a txt document and drag it onto the dropbox.
