### ISSUE TITLE
[Feature Request] Redownload function?

### ISSUE THREAD

**Issue by springfield67** [dazedcat19/FMD2#78]
So I was directed from https://github.com/riderkick/FMD/issues to here. Not sure how much has changed since the FMD I had and FMD2, but from what I see, there's no redownload function. 

To put it simple, can we have a function to redownload tasks once they're marked as Completed? Like, let's just say someone forgot to delete old manga that they had downloaded in their download folder. (Not me, of course. Asking for a friend.) Halfway through downloading new batch of manga, the person suddenly remembered, but then, the new batch was mixed in with the old one. So yeah, deleted the whole thing with the intent of keeping the download folder had only the new stuff, just to realize there is no redownload function. My friend's stuck with a list of 50 manga marked as Completed as their status with no way to change (Aside from manually re-add them one by one like how the people of old do). It would be nice if we could right click the tasks and set their status to Queue or In progress like with Disable and Enable.

Or maybe there's already that function but I don't know about. If so, would be appreciated to be guided on how to do it.

**Comment by Slasar41** [comment]
Implemented in the next release. https://github.com/dazedcat19/FMD2/commit/b9b9ce22ff810389b80a60918b300c717abc1505
