### ISSUE TITLE
Kissmanga errors.

### ISSUE THREAD

**Issue by HiP1** [dazedcat19/FMD2#8]
I saw you added Kissmanga, thanks !
I enabled it in the options.
then when i tried to download the manga list, i get this error message :
![image](https://user-images.githubusercontent.com/3578646/82745687-8bcf8400-9d87-11ea-8096-d7c154097c07.png)

and in the favorites that i converted, the rows for kissmanga are still empty in the website column :
![image](https://user-images.githubusercontent.com/3578646/82745760-43649600-9d88-11ea-81fc-94444cf60c86.png)

**Comment by HiP1** [comment]
but i can update the manga list. :)
and it did display the mangas of the site after a long time.
but when i try to download from there, it fails with default settings and with the cookie workaround from the first FMD. though i could not find where to input the keys and chko, i'm guessing you included those in the lua.

**Comment by Slasar41** [comment]
The database for KissManga isn't uploaded to the server yet, that's why its give 404 error.

I think you need to run the converter tool again to properly display KissManga in the website column.
Or use DB Explorer application to manually edit it.

**Comment by dazedcat19** [comment]
edit "modules.txt" for the converter and add manually kissmanga id. then run the converter. or run simple sql script `update "downloads" set "moduleid"="<kissmangamoduleid>" where "moduleid"="KissManga"` like so. just google it try and error.

**Comment by HiP1** [comment]
@dazedcat19 where do i find the kissmanga id ?
and what about the download problem ?

**Comment by HiP1** [comment]
@dazedcat19 i added the id that was in the lua, it worked. but it still won't download.
maybe you should update the converter files in the next release :)

**Comment by dazedcat19** [comment]
there's no download problem here

**Comment by HiP1** [comment]
weird. when i try to download a whole chapter, it shows it tried to get only 1 page overall but fails.
do i have to use a workaround with cookie or anything ?

**Comment by HiP1** [comment]
tried many combination with or without cookie/user agent workaround, nothing worked.

**Comment by HiP1** [comment]
but when i did the convert to add the kissmanga id, i only copied the favorites.db file, maybe i need the other files ?

**Comment by dazedcat19** [comment]
as long as you can open view manga info than it's fine. look at the log. it's a cloudflare issue or what. there's a possibility your ip got banned.

**Comment by HiP1** [comment]
i can view the chapters in a regular browser, so i dont think i was banned.
no mention of cloudflare in the log. just that the thread fails ?

![image](https://user-images.githubusercontent.com/3578646/82934134-4da2b200-9f8b-11ea-82ce-bb5772518660.png)

**Comment by Slasar41** [comment]
@HiP1 I can download it just fine.
![image](https://user-images.githubusercontent.com/28888646/82940024-68dae500-9fbe-11ea-9768-c6a1740f3a01.png)

**Comment by HiP1** [comment]
@Slasar41 thanks ! you're not using anything in particular ? just the default install ?

**Comment by HiP1** [comment]
i tried from a completely new install, without any history conversion, just added kissmanga from the websites in the options, and it didn't work.

**Comment by dazedcat19** [comment]
Enable log to file. Edit kissmanga.lua after line 73 `local body = HTTP.Document.ToString()` add `print(tostring(body))`
try again then post your log file.

**Comment by Slasar41** [comment]
I try fresh install in different PC and I'm unable to download from KissManga too, but I can still download it in another PC even though it's share the same network.

Here's my log.
[fmd.log](https://github.com/dazedcat19/FMD2/files/4687246/fmd.log)

**Comment by dazedcat19** [comment]
Update the modules. post again the log if failed.

**Comment by HiP1** [comment]
the new lua fixed it for me, the download now works.
thanks a lot !

**Comment by Slasar41** [comment]
Same here, it's works fine now.
Thanks!
