### ISSUE TITLE
[bug] Favorites check skips MangaDex favorites that have finished publication.

### ISSUE THREAD

**Issue by IgnatiusC** [dazedcat19/FMD2#81]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Favorites check skips manga on MangaDex that have finished publication but not scanlation.

**To Reproduce**
1. Add a manga that has finished publication but not scanlation to favorites.  (e.g. https://mangadex.org/title/323/moon)
2. Check for new chapters on favorites 

**Expected behavior**
Downloader downloads new chapters

**Comment by dazedcat19** [comment]
It working just fine.
There's no codes that skip the finished favorites. It only for cosmetic and an option to delete it after the check. Look at `uFavoritesManager.pas`.
