### ISSUE TITLE
[bug-website module] WebToons: Only the last 10 chapters of every title get listed

### ISSUE THREAD

**Issue by McChickn** [dazedcat19/FMD2#85]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**Describe the bug**
All titles on webtoons.com are affected, as long as they have more than 10 chapters, which are then listed on more than one page. Parsing of the main title page with the last 10 chapters works fine, so do all the other chapter list pages if I test them seperately (minor script change required for that since the script as it is removes the last part of the url starting with "&page="). The xpath to grap the number of chapter list pages seems fine to me as well, and since manually setting this number in the script doesn't help, I'm guessing that's probably not the issue either. So in the end, I couldn't figure out what the problem could be.

**Additional context**
I tested with one completed title with high number of chapters - Soul Cartel, https://www.webtoons.com/en/fantasy/soul-cartel/list?title_no=72 - the chapters are listed on 23 pages. Issue is present for every single other title too though.

Also, I do remember this mudole working a few weeks ago.

**Log**
Logs contain no useful info on this.

**Comment by dazedcat19** [comment]
Give an example of the affected titles. I tested with titles that has about 50-100 chapters. they all listed just fine.

**Comment by Slasar41** [comment]
I tested with Soul Cartel and it's listed just fine.
![image](https://user-images.githubusercontent.com/28888646/90429700-5f11db00-e0f0-11ea-9335-f6974b455c95.png)
Maybe this is a regional thing?
Like in this [issue](https://github.com/dazedcat19/FMD2/issues/32) which is works fine on my end but not for another users and need to add some cookie to make it works again.

**Comment by McChickn** [comment]
I feared it would be like that. I did look at the code and didn't really find any reason why it wouldn't work either. It just doesn't, for me.

![SC_WT_FMD2](https://user-images.githubusercontent.com/32773704/90540932-2e7a8180-e182-11ea-97c2-a579c6fd97ce.jpg)

 So that leaves me to debug this myself. Any easy way to make FMD2 output the html it tried to parse to a log so I can try to look at what might have failed?

**Comment by dazedcat19** [comment]
> Edit `WebToons.lua`
> Add new line after line 12. `HTTP.Document.SaveToFile('webtoons_getinfo.html')`
> Restart fmd if you don't run it with `--lua-dofile`
> Open the manga info
> It will create a file `webtoons_getinfo.html` in the root of fmd folder
> Post the file

**Comment by McChickn** [comment]
So I added after line 12: `HTTP.Document.SaveToFile('webtoons_getinfo1.html')`
and after line 22: `local i = 2`
plus after line 29: 
```
HTTP.Document.SaveToFile('webtoons_getinfo'..i..'.html')
i=i+1
```
I get 2 files, as I expected, the second one, webtoons_getinfo2.html, is not the response I wanted. It seems to be the age verification page, which apperently exists, I just didn't know. 

So the cookie thing doesn't work?

**Comment by McChickn** [comment]
So I added after line 12: `HTTP.Document.SaveToFile('webtoons_getinfo1.html')`
and after line 22: `local i = 2`
plus after line 29: 
```
HTTP.Document.SaveToFile('webtoons_getinfo'..i..'.html')
i=i+1
```
I get 2 files, as I expected, the second one, webtoons_getinfo2.html, is not the response I wanted. It seems to be the age verification page, which apperently exists, I just didn't know. 

So the cookie thing doesn't work?

**Comment by McChickn** [comment]
So I added after line 12: `HTTP.Document.SaveToFile('webtoons_getinfo1.html')`
and after line 22: `local i = 2`
plus after line 29: 
```
HTTP.Document.SaveToFile('webtoons_getinfo'..i..'.html')
i=i+1
```
I get 2 files, and as I expected, the second one, webtoons_getinfo2.html, is not the response I wanted. It seems to be the age verification page, which apparently exists, I just didn't know/remember. 

So the server responds to me properly, it just ignores that age verification cookie that fmd should have set?

**Comment by McChickn** [comment]
Updating to new version failed somehow, so I reinstalled. 
Seems to work fine again now, thx.
