### ISSUE TITLE
1stkissmanga & kissmangaIN FAILED

### ISSUE THREAD

**Issue by Gensmyawk** [dazedcat19/FMD2#9]
it failed when updating.. 
![Untitled](https://user-images.githubusercontent.com/65871509/82764655-f8f41f80-9e42-11ea-83af-004a26a2430e.png)

but still can see the episodes..
but cant auto download when there are new episodes
![ad](https://user-images.githubusercontent.com/65871509/82764721-80da2980-9e43-11ea-9386-215390ec8913.png)

**Comment by dazedcat19** [comment]
we don't really maintain the mangalist. feel free to make a pr. https://github.com/dazedcat19/FMD2-DB
just add it to your favorites.
