### ISSUE TITLE
[bug-website module] HitomiLa

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#96]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 2004 64-bit

**Describe the bug**
- I can download it with FMD1 but not with FMD2.
Example: https://hitomi.la/doujinshi/gokuraku-chou-%7C-paradise-butterfly-english-1721880.html, https://hitomi.la/doujinshi/hiru-wa-krillin-no-tsuma-english-913408.html
- FMD removed `:` character from the URL. Example: https://hitomi.la/doujinshi/marionette-queen:4.0.0-english-793574.html

**Comment by Slasar41** [comment]
@dazedcat19 The download still doesn't working properly.
FMD got the page number `0/33` but there's no connection and eventually it'll error.
```
03.43.22.247 WARNING: TTaskThread, checkforfinish failed=33/33 [HitomiLa] "Gokuraku Chou | Paradise Butterfly" > "/reader/1721880.html"
03.43.22.248 WARNING: TTaskThread, download failed. "Gokuraku Chou | Paradise Butterfly" "Gokuraku Chou  Paradise Butterfly" "/reader/1721880.html"
03.43.45.468 WARNING: TTaskThread, checkforfinish failed=33/33 [HitomiLa] "Gokuraku Chou | Paradise Butterfly" > "/reader/1721880.html"
03.43.45.469 WARNING: TTaskThread, download failed. "Gokuraku Chou | Paradise Butterfly" "Gokuraku Chou  Paradise Butterfly" "/reader/1721880.html"
```

**Comment by dazedcat19** [comment]
I can download just fine. what image urls you got?
open the `downloads.db` or put `print(TASK.PageLinks.Text)` before `return true` on `getpagenumber` function.

**Comment by Slasar41** [comment]
Tested again and now downloaded just fine. Thanks!
