### ISSUE TITLE
[bug-website module] [Nartag] *Does not load information*

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#981]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

W 10  21H1 x64

### Describe the bug

It does not load the information or the chapters, it would have to be seen if it also does not download the chapters in question.

![image](https://user-images.githubusercontent.com/70826672/165645029-e81bd734-4055-4a70-964f-dfafbfd874a1.png)

WEB:
https://nartag.com

_**The Module in FMD is found as "TraduccionesAmistosas"**_
![image](https://user-images.githubusercontent.com/70826672/165645436-05ad86f4-d730-4b77-a38c-d55fa13f121e.png)

### Log

view-source:https://nartag.com/bl/el-renacimiento-de-un-doctor/

**Comment by horacio881** [comment]
Es un problema de cookies, aca dejo como solucionarlo:

https://github.com/dazedcat19/FMD2/issues/956

**Comment by CloudBladed** [comment]
Gracias, se me olvidaba que podia hacer eso.
